In [1]:
# Refer to Workshop 4 slide -  and Archive vs. Buffer  server & storage
# Archive - typically the selection will be a big data storage - distributed storage
# Buffer - typically the selection will be a high-performance n-arity datastore

# Both are SQL servers for reason of prototyping - and infrastructure (this is what's available)

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import sys
import os
from IPython.core.display import display, HTML

In [3]:
# Erik_bedmasterFileIDs = pd.read_csv('Erik_bedmasterFileIDs.csv',header=None)
# Erik_bedmasterFileIDs.columns = ['fileID']
# Erik_bedmasterFileIDs
# table = Erik_bedmasterFileIDs

In [4]:
import numpy as np
f = open('C:/Users/wg984/Wolfgang/repos/Bedmaster-ICU-tools/user_files/quality_checks_errorlog.txt','r')

In [6]:
macrofiles = [x for x in f.read().split(' ') if (('BLK' in x) or ('ELL' in x) )]

In [7]:
import re
macrofiles = [re.split( '_\d+_v4.mat', x)[0] for x in macrofiles]

In [8]:
macrofiles = np.unique(macrofiles)
macrofiles = [x.split('1\n')[-1] for x in macrofiles]
macrofiles = np.unique(macrofiles)
macrofiles

array(['\nBLK12_1266-1529051991', 'BLK07_756-1547899217',
       'BLK07_758-1539133548', 'BLK07_768-1547323995',
       'BLK07_780-1547074542', 'BLK12_1252-1547942773',
       'BLK12_1272-1537781946', 'BLK12_1280-1547913492',
       'BLK12_1284-1540337896', 'BLK12_1288-1539370921',
       'ELL04_418-1543634799'], dtype='<U22')

In [9]:
#dirdata = 'C:/Users/wg984/Wolfgang/bedmaster/'
import pandas as pd

#input is either corrupt file list, for reconversion or first time conversion file list

task ='manual'



if task == 'reconversion':

    LogDir = '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/DataProcessingLog/'
#     filep=LogDir+'corruptFiles4Reconversion.csv'
    filep=LogDir+'corrupt_files4Reconversion_StepB2_range(1, 40)2019-04-24_19_40_3.csv'
    table=pd.read_csv(filep, header = None, names = ['fileID'])
    
elif task =='conversion':
    LogDir = '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/DataProcessingLog/'
#     LogDir = 'C:/Users/wg984/Wolfgang/ICU-Sleep/'
    filep=LogDir+'toConvert.csv'
    table=pd.read_csv(filep)    

elif task =='manual':
#     fileIDs = ['ELL04_424-1558127736','ELL4_424-1445169540','ELL04_424-1445169540', 'BLK10_1088-1557606617', 'BLK10_1058-1557612726']
    
#     fileIDs = [ 'BLK10_1088-1557606617', 'BLK10_1058-1557612726']
    
#     'BLK12_1266-1529051991','BLK12_1286-1554056823']
    
#     fileIDs = ['BLK10_1058-1560012202']
#     fileIDs = ['LUN06_640-1477198001']
#     fileIDs = ['BLK10_1066-1561135440', 'BLK10_1058-1561222211']
#     fileIDs = ['ELL04_432-1535156235', 'BLK12_1278-1535677927', 'BLK07_770-1534053914', 'ELL09_922-1533258162', 'BLK12_1280-1533125204', 'LUN07_788-1533639226', 'LUN06_632-1534461681' ]
        
#     fileIDs = ['ELL04_404-1566264527','ELL04_406-1565831769','BLK07_756-1565661060','BLK07_770-1565795532', 'BLK12_1254-1566194557', 'BLK12_1286-1566252227']
#     fileIDs = ['BLK12_1286-1566252227','ELL04_406-1565831769']
#     fileIDs = ['ELL04_406-1565831769']
    
#     table = pd.DataFrame(fileIDs, columns =['fileID'])
    
    table = pd.read_csv('C:/Users/wg984/Wolfgang/repos/ICU-Sleep/data/fileIDs_larger_STP_than_mat_after_LargeBundleSize_conversion.csv')
    
#     table=pd.DataFrame(fileIDs, columns=['fileID'])

In [5]:
table = pd.DataFrame(
['BLK07_754-1529299617', 'BLK07_754-1529299617', 'BLK07_788-1531346646', 'BLK07_788-1531408226', 'BLK07_758-1539133548', 'ELL04_438-1539459164', 'ELL04_438-1540403862', 'BLK12_1254-1547520918', 'BLK07_768-1547323995', 'BLK07_768-1547647085', 'BLK07_766-1548719417', 'BLK07_766-1549067030', 'BLK07_778-1549418939', 'BLK07_786-1549816181', 'BLK07_778-1549981372', 'BLK07_786-1550078285', 'ELL04_402-1549599295', 'ELL04_414-1549673602', 'ELL04_414-1549844349', 'BLK12_1258-1546474180', 'BLK12_1268-1550616601', 'BLK12_1268-1550623121', 'BLK12_1258-1550691336', 'BLK07_758-1552397514', 'BLK12_1284-1552179101', 'BLK12_1274-1554554114', 'BLK12_1266-1554335530', 'ELL04_408-1554754789', 'ELL04_432-1555456610', 'BLK12_1252-1571609375', 'ELL04_432-1571007865', 'LUN10_1072-1572446220', 'BLK07_770-1572939539', 'BLK07_770-1573615241', 'LUN10_1072-1573754384', 'BLK07_790-1572739158'])

In [5]:
ids = [2, 4, 5, 12, 16, 23, 25, 28, 31, 33, 41, 49, 64, 70, 71, 92, 100, 106, 113, 116, 137, 147, 150, 163, 170, 174, 185]

mad3folder = os.path.join('M:Projects/ICU_SLEEP_STUDY/data/data_analysis')
tablefile = 'Study/ICUSleep_DataTable_ICUonly.csv'
study_table = pd.read_csv(os.path.join(mad3folder, tablefile))
bmfiles_to_convert = []
for studyid in ids:
    bmfilesstudyid = study_table[study_table.StudyID == studyid].BMFileID.dropna()
    for x in bmfilesstudyid:
        bmfiles_to_convert += list(x.split(','))
bmfiles_to_convert = pd.unique(bmfiles_to_convert)
table = pd.DataFrame(bmfiles_to_convert)

In [2]:
ids = [2, 4, 5, 12, 16, 23, 25, 28, 31, 33, 41, 49, 64, 70, 71, 92, 100, 106, 113, 116, 137, 147, 150, 163, 170, 174, 185]
for idtmp in ids:
    print('python bmfileID_h5_to_studyID_h5.py ' + str(idtmp))

python bmfileID_h5_to_studyID_h5.py 2
python bmfileID_h5_to_studyID_h5.py 4
python bmfileID_h5_to_studyID_h5.py 5
python bmfileID_h5_to_studyID_h5.py 12
python bmfileID_h5_to_studyID_h5.py 16
python bmfileID_h5_to_studyID_h5.py 23
python bmfileID_h5_to_studyID_h5.py 25
python bmfileID_h5_to_studyID_h5.py 28
python bmfileID_h5_to_studyID_h5.py 31
python bmfileID_h5_to_studyID_h5.py 33
python bmfileID_h5_to_studyID_h5.py 41
python bmfileID_h5_to_studyID_h5.py 49
python bmfileID_h5_to_studyID_h5.py 64
python bmfileID_h5_to_studyID_h5.py 70
python bmfileID_h5_to_studyID_h5.py 71
python bmfileID_h5_to_studyID_h5.py 92
python bmfileID_h5_to_studyID_h5.py 100
python bmfileID_h5_to_studyID_h5.py 106
python bmfileID_h5_to_studyID_h5.py 113
python bmfileID_h5_to_studyID_h5.py 116
python bmfileID_h5_to_studyID_h5.py 137
python bmfileID_h5_to_studyID_h5.py 147
python bmfileID_h5_to_studyID_h5.py 150
python bmfileID_h5_to_studyID_h5.py 163
python bmfileID_h5_to_studyID_h5.py 170
python bmfileID_h5_to_studyID_h5.py 174
python bmfileID_h5_to_studyID_h5.py 185

In [6]:
table.columns = ['fileID']

In [7]:
table

                   fileID
0    ELL04_432-1528528595
1    BLK07_788-1529370699
2    LUN07_778-1529875345
3   BLK12_1252-1529362196
4    ELL04_424-1537837052
5    BLK07_788-1540401161
6    BLK07_788-1540676544
7    ELL04_412-1541524281
8    ELL04_438-1539459164
9    ELL04_434-1547056025
10   ELL04_434-1547245531
11  BLK12_1254-1547520918
12  BLK12_1252-1547942773
13   BLK07_756-1547899217
14   BLK07_756-1548200185
15   BLK07_756-1548200241
16   ELL04_422-1548505531
17   ELL04_408-1550011150
18   ELL04_422-1552381093
19  BLK12_1274-1554554114
20   ELL04_432-1555456610
21  BLK12_1288-1557857171
22   LUN07_764-1559683996
23  BLK12_1284-1559730040
24  BLK12_1268-1560369140
25  BLK12_1274-1561803974
26  BLK12_1274-1562702709
27  BIG13_1326-1558386657
28  BIG13_1354-1561066693
29  BIG13_1326-1562086161
30  BLK12_1254-1562544296
31  BLK12_1280-1562574671
32  BIG13_1354-1564758137
33  BIG13_1354-1565033463
34   ELL04_438-1562109370
35  BLK12_1252-1563110378
36  BLK12_1288-1565458626
37  BLK12_1288-1566135054
38  BLK12_1260-1565652541
39  BLK12_1256-1566687902
40   ELL04_438-1567635972
41   ELL04_438-1568145594
42  BLK12_1252-1571609375
43   ELL04_404-1571677212
44  LUN10_1026-1570202354
45  LUN10_1022-1570722751
46  LUN10_1026-1570806702
47   BLK07_770-1572213977
48  LUN10_1012-1573002368
49   BLK07_766-1573220956
50   BLK07_766-1573334582
51  LUN10_1012-1573508378
52   LUN06_614-1573751394
53   LUN06_614-1573935026
54  LUN10_1072-1572446220
55   BLK07_770-1572939539
56   BLK07_770-1573615241
57  LUN10_1072-1573754384

In [11]:
# remove all filIDs that are already in ICU_Sleep or ICU_Sleep_2
files_already_converted_path = '//eris1fs2/CDAC/bedmaster_data/batching/ICUSleep_2/'
files_already_converted = os.listdir(files_already_converted_path)
files_already_converted = [x for x in files_already_converted if '.Stp' in x]
files_already_convertedfiles = [x.split('.Stp')[0] for x in files_already_converted]

In [12]:
len(files_already_convertedfiles)

417

### connect to cdac database

In [8]:
module_p='//mad3/MGH-NEURO-CDAC/Projects/CDAC_DATABASE/notebooks/utils'
sys.path.append(module_p)
from common import connect_cdac,connect_edw, get_module_version
#TODO: get version num? connection string message?
print('cdac module version: ' + get_module_version())
cxn=connect_cdac()

cdac module version: 0.2
CDAC connection <pyodbc.Connection object at 0x000001CF49B7F5E0>

In [8]:
# fileIDsNotConverted

# fileIDsNotConverted=set(df_nonmat['fileID'])
fileIDsNotConverted = set(table.fileID)
# fileIDsNotConverted = fileIDsNotConverted - set(files_already_convertedfiles)
# fileIDsNotConverted = list(fileIDsNotConverted)
# fileIDsNotConverted = fileIDsNotConverted+ ['ELL04_406-1554232479','BLK12_1252-1549081788']
# fileIDsNotConverted = set(macrofiles)
# print(len(fileIDsNotConverted))

In [9]:
#### EDIT: reconversion ####

##########################################
# Reconversion
##########################################


# df_files_src=pd.DataFrame(list(fileIDsNotConverted),columns=['fileID'])

df_files_src = table

In [10]:
df_files_src

                   fileID
0    ELL04_432-1528528595
1    BLK07_788-1529370699
2    LUN07_778-1529875345
3   BLK12_1252-1529362196
4    ELL04_424-1537837052
5    BLK07_788-1540401161
6    BLK07_788-1540676544
7    ELL04_412-1541524281
8    ELL04_438-1539459164
9    ELL04_434-1547056025
10   ELL04_434-1547245531
11  BLK12_1254-1547520918
12  BLK12_1252-1547942773
13   BLK07_756-1547899217
14   BLK07_756-1548200185
15   BLK07_756-1548200241
16   ELL04_422-1548505531
17   ELL04_408-1550011150
18   ELL04_422-1552381093
19  BLK12_1274-1554554114
20   ELL04_432-1555456610
21  BLK12_1288-1557857171
22   LUN07_764-1559683996
23  BLK12_1284-1559730040
24  BLK12_1268-1560369140
25  BLK12_1274-1561803974
26  BLK12_1274-1562702709
27  BIG13_1326-1558386657
28  BIG13_1354-1561066693
29  BIG13_1326-1562086161
30  BLK12_1254-1562544296
31  BLK12_1280-1562574671
32  BIG13_1354-1564758137
33  BIG13_1354-1565033463
34   ELL04_438-1562109370
35  BLK12_1252-1563110378
36  BLK12_1288-1565458626
37  BLK12_1288-1566135054
38  BLK12_1260-1565652541
39  BLK12_1256-1566687902
40   ELL04_438-1567635972
41   ELL04_438-1568145594
42  BLK12_1252-1571609375
43   ELL04_404-1571677212
44  LUN10_1026-1570202354
45  LUN10_1022-1570722751
46  LUN10_1026-1570806702
47   BLK07_770-1572213977
48  LUN10_1012-1573002368
49   BLK07_766-1573220956
50   BLK07_766-1573334582
51  LUN10_1012-1573508378
52   LUN06_614-1573751394
53   LUN06_614-1573935026
54  LUN10_1072-1572446220
55   BLK07_770-1572939539
56   BLK07_770-1573615241
57  LUN10_1072-1573754384

In [11]:
### EDIT ###
### Create a service name

from storage import get_service_name, init_move_service, call_move_service
from bedmaster import init_bedmaster_service, call_bedmaster_service
# TODO: change user name
usrn='wg984'
user=usrn
# DEMO: change it to bandit
# usrn='bandit'

In [12]:
len(df_files_src) # - 2/4/2019 - 61074 # - 2/11/2019 - 60704

58

In [12]:
# looking at which group
df_files=df_files_src
# df_files=df_files[~df_files['fileID'].str.contains('EDURGNT|EDACUTE|WHITE')]

# ICU
# df_files=df_files[df_files['fileID'].str.contains('BLK12|ELL04|BLK08|BLK09|LUN06')]

# EM
# df_files=df_files[~df_files['fileID'].str.contains('BLK12|ELL04|BLK08|BLK09|LUN06')]
# df_files=df_files[~df_files['fileID'].str.contains('EDURGNT|EDACUTE')]

In [13]:
# ICU
df_files.head()

                  fileID
0   ELL04_432-1528528595
1   BLK07_788-1529370699
2   LUN07_778-1529875345
3  BLK12_1252-1529362196
4   ELL04_424-1537837052

In [14]:
df_files.to_csv('tosubmit.csv')

In [17]:
# wg984_20191004_210353 --> Eriks file.

In [15]:
### Calling service - Always recell the links if possible

usrn,servicen=get_service_name(usrn)
print('==> get service name')
print(servicen)

==> get service name
wg984_20200126_170310

In [16]:
import pandas as pd

init_bedmaster_service(servicen,df_files)

==> initialize conversion node
mounting /data/cdac/bedmaster_data/batching
--> done
==> move files to converison node
params ELL04_432-1528528595
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_788-1529370699
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN07_778-1529875345
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1252-1529362196
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_424-1537837052
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_788-1540401161
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_788-1540676544
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_412-1541524281
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_438-1539459164
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_434-1547056025
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_434-1547245531
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1254-1547520918
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1252-1547942773
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_756-1547899217
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_756-1548200185
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_756-1548200241
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_422-1548505531
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_408-1550011150
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_422-1552381093
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1274-1554554114
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_432-1555456610
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1288-1557857171
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN07_764-1559683996
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1284-1559730040
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1268-1560369140
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1274-1561803974
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1274-1562702709
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BIG13_1326-1558386657
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BIG13_1354-1561066693
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BIG13_1326-1562086161
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1254-1562544296
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1280-1562574671
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BIG13_1354-1564758137
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BIG13_1354-1565033463
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_438-1562109370
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1252-1563110378
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1288-1565458626
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1288-1566135054
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1260-1565652541
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1256-1566687902
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_438-1567635972
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_438-1568145594
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK12_1252-1571609375
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params ELL04_404-1571677212
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN10_1026-1570202354
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN10_1022-1570722751
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN10_1026-1570806702
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_770-1572213977
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN10_1012-1573002368
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_766-1573220956
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_766-1573334582
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN10_1012-1573508378
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN06_614-1573751394
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN06_614-1573935026
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN10_1072-1572446220
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_770-1572939539
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params BLK07_770-1573615241
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
params LUN10_1072-1573754384
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
--> done

In [17]:
call_bedmaster_service(servicen,df_files)

==> create conversion node
bedmaster module version 0.1
ls *.Stp > a_filesStp.csv ;
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
cat a_filesStp.csv | sed s/.Stp//g | sed s/\r//g | xargs -I {} bsub -q rerunnable -o 1.log -e 1.err python bm_convert.py {}
mounting /data/cdac/bedmaster_data/batching/wg984_20200126_170310
--> done

In [17]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.