#### aim: from different airgo file format versions, we transform data to common format called 'airgo reserach'

In [1]:
import numpy as np
import pandas as pd
import re
import datetime
import os

In [2]:
# sample research airgo, as done for sleep lab data:
sample_airgo_research = pd.read_csv('C:/Users/wg984/Wolfgang/repos/ICU-Sleep/data/sample_airgo_research.csv')
sample_airgo_research = sample_airgo_research.head()
sample_airgo_research

                  DateTime    Band  accX  accY  accZ  CRCStatus
0  2019-08-03 22:26:32.378  3115.0  1.15  1.75 -9.56        NaN
1  2019-08-03 22:26:32.478  3109.0  1.11  1.96 -9.51        NaN
2  2019-08-03 22:26:32.578  3109.0  1.11  1.71 -9.42        NaN
3  2019-08-03 22:26:32.678  3101.0  0.91  1.73 -9.43        NaN
4  2019-08-03 22:26:32.778  3095.0  1.01  1.77 -9.57        NaN

In [73]:
folder = '001_Sullivan'
re.split('_', folder)[0]

'001'

In [65]:
### get all v4 breath files:
savefolder = '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files'
savepaths = []
    
### get all v4 breath files:
enrolled = '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/'
enrolled_folders = os.listdir(enrolled)
v4_files = []
for folder in enrolled_folders[:170]:
    if '.db' in folder: continue
    if '.txt' in folder: continue
    files = os.listdir(os.path.join(enrolled, folder, 'airgo'))
    #     print(files)
    for file in files:
        if '_Breath.csv' in file:
            v4_files.append(os.path.join(enrolled, folder, 'airgo', file))
            savepaths.append(os.path.join(savefolder, file))

In [68]:
for v4_file, savepath in zip(v4_files, savepaths):
    print('\n')
    print(v4_file)
    print(savepath)

//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/001_Sullivan\airgo\001_2018_06_06pm_airgo breath AirGo 78a5043e9810 2018-06-06 152600_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\001_2018_06_06pm_airgo breath AirGo 78a5043e9810 2018-06-06 152600_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/002_Herling\airgo\002_2018_06_11pm_airgo breath AirGo 78a5043e8ea1 2018-06-11 194614_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\002_2018_06_11pm_airgo breath AirGo 78a5043e8ea1 2018-06-11 194614_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/003_Carey\airgo\003_ 2018_06_18pm_airgo breath AirGo 78a5043e9b82 2018-06-18 203845_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\003_ 2018_06_18pm_airgo breath AirGo 78a5043e9b82 2018-06-18 203845_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/003_Carey\airgo\003_ 2018_06_20am_airgo breath AirGo 78a5043e9246 2018-06-20 082641_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\003_ 2018_06_20am_airgo breath AirGo 78a5043e9246 2018-06-20 082641_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/003_Carey\airgo\003_ 2018_06_20pm_airgo breath AirGo 78a5043e9b82 2018-06-20 202651_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\003_ 2018_06_20pm_airgo breath AirGo 78a5043e9b82 2018-06-20 202651_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/003_Carey\airgo\003_2018_06_21pm_airgo breath AirGo 78a5043e94e6 2018-06-21 202300_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\003_2018_06_21pm_airgo breath AirGo 78a5043e94e6 2018-06-21 202300_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/004_Foster\airgo\004_2018_06_19pm_airgo breath AirGo 78a5043e9482 2018-06-19 203935_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\004_2018_06_19pm_airgo breath AirGo 78a5043e9482 2018-06-19 203935_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/004_Foster\airgo\004_2018_06_20am_airgo breath AirGo 78a5043e926f 2018-06-20 100756_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\004_2018_06_20am_airgo breath AirGo 78a5043e926f 2018-06-20 100756_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/004_Foster\airgo\004_2018_06_21am_airgo breath AirGo 78a5043e94e6 2018-06-21 082816_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\004_2018_06_21am_airgo breath AirGo 78a5043e94e6 2018-06-21 082816_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/004_Foster\airgo\004_2018_06_23am_airgo breath Airgo 78a5043e926f 2018-06-23 120904_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\004_2018_06_23am_airgo breath Airgo 78a5043e926f 2018-06-23 120904_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/004_Foster\airgo\004_2018_06_24am_airgo breath AirGo 78a5043e9482 2018-06-24 093128_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\004_2018_06_24am_airgo breath AirGo 78a5043e9482 2018-06-24 093128_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/006_Soteropoulos\airgo\006_2018_07_10am_airgo breath AirGo 78a5043e94e6 2018-07-10 091124_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\006_2018_07_10am_airgo breath AirGo 78a5043e94e6 2018-07-10 091124_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/006_Soteropoulos\airgo\006_2018_07_10pm AirGo 78a5043e94bd 2018-07-10 204622_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\006_2018_07_10pm AirGo 78a5043e94bd 2018-07-10 204622_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/006_Soteropoulos\airgo\006_2018_07_11am_airgo breath AirGo 78a5043e925f 2018-07-11 083522_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\006_2018_07_11am_airgo breath AirGo 78a5043e925f 2018-07-11 083522_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/006_Soteropoulos\airgo\006_2018_07_11pm airgo breath AirGo 78a5043e94b8 2018-07-11 210315_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\006_2018_07_11pm airgo breath AirGo 78a5043e94b8 2018-07-11 210315_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/006_Soteropoulos\airgo\006_2018_07_12am airgo breath 78a5043e925f 2018-07-12 085220_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\006_2018_07_12am airgo breath 78a5043e925f 2018-07-12 085220_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/007_Nobel\airgo\007_2018_08_07pm_airgo breath AirGo 78a5043e8eef 2018-08-07 185001_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\007_2018_08_07pm_airgo breath AirGo 78a5043e8eef 2018-08-07 185001_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/007_Nobel\airgo\007_2018_08_08am_airg breath AirGo 78a5043e9852 2018-08-08 111356_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\007_2018_08_08am_airg breath AirGo 78a5043e9852 2018-08-08 111356_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/008_Norris\airgo\008_2018_07_12pm_airgo breath  AirGo 78a5043e94f7 2018-07-12 193937_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\008_2018_07_12pm_airgo breath  AirGo 78a5043e94f7 2018-07-12 193937_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/008_Norris\airgo\008_2018_07_13am_airgo breath AirGo 78a5043e94b8 2018-07-13 085256_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\008_2018_07_13am_airgo breath AirGo 78a5043e94b8 2018-07-13 085256_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/008_Norris\airgo\008_2018_07_13pm_airgo breath AirGo 78a5043e9482 2018-07-13 202243_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\008_2018_07_13pm_airgo breath AirGo 78a5043e9482 2018-07-13 202243_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/008_Norris\airgo\008_2018_07_14AM_airgo breath AirGo 78a5043e8ea1 2018-07-14 090727_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\008_2018_07_14AM_airgo breath AirGo 78a5043e8ea1 2018-07-14 090727_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/008_Norris\airgo\008_2018_07_14PM_airgo breath AirGo 78a5043e926f 2018-07-14 201309_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\008_2018_07_14PM_airgo breath AirGo 78a5043e926f 2018-07-14 201309_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/008_Norris\airgo\008_2018_07_15AM_airgo breath AirGo 78a5043e9484 2018-07-15 083235_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\008_2018_07_15AM_airgo breath AirGo 78a5043e9484 2018-07-15 083235_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/009_Mullen\airgo\009_2018_09_05pm to 2018_09_07pm 05AirGo 78a5043e8eef 2018-09-05 193618_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\009_2018_09_05pm to 2018_09_07pm 05AirGo 78a5043e8eef 2018-09-05 193618_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/010_Martin\airgo\010_2018_09_20pm_airgo breath  AirGo 2018-09-05 185100_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\010_2018_09_20pm_airgo breath  AirGo 2018-09-05 185100_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/011_Cullen\airgo\011_2018_09_20pm_airgo breath  AirGo 2018-09-20 181600_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\011_2018_09_20pm_airgo breath  AirGo 2018-09-20 181600_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/012_Welch\airgo\012_2018_09_24pm_airgo breath AirGo 78a5043e8eef 2018-09-24 140224_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\012_2018_09_24pm_airgo breath AirGo 78a5043e8eef 2018-09-24 140224_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/013_Papa\airgo\013_2018_09_25pm_airgo breath AirGo 78a5043e94e7 2018-09-25 201200_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\013_2018_09_25pm_airgo breath AirGo 78a5043e94e7 2018-09-25 201200_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/014_Volger\airgo\014_2018_10_09pm_airgo breath AirGo 78a5043e9226 2018-10-09 175724_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\014_2018_10_09pm_airgo breath AirGo 78a5043e9226 2018-10-09 175724_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/015_Keigney\airgo\015_2018_10_11pm_airgo breath AirGo 78a5043e8ec0 2018-10-11 175510_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\015_2018_10_11pm_airgo breath AirGo 78a5043e8ec0 2018-10-11 175510_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/015_Keigney\airgo\015_2018_10_13pm_airGo breath AirGo 78a5043e9852 2018-10-13 190754_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\015_2018_10_13pm_airGo breath AirGo 78a5043e9852 2018-10-13 190754_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/016_Smith_Stanley\airgo\016_2018_10_15pm_airgo breath_AirGo 78a5043e9226 2018-10-15 185950_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\016_2018_10_15pm_airgo breath_AirGo 78a5043e9226 2018-10-15 185950_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/017_Kiley_Richard\airgo\017_2018_10_20pm_airgo breath_AirGo 78a5043e9226 2018-10-20 182232_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\017_2018_10_20pm_airgo breath_AirGo 78a5043e9226 2018-10-20 182232_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/017_Kiley_Richard\airgo\017_2018_10_23pm_airgo breath_AirGo 78a5043e9852 2018-10-23 190517_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\017_2018_10_23pm_airgo breath_AirGo 78a5043e9852 2018-10-23 190517_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/018_Koehler_Judith\airgo\018_2018_10_25pm_airgo breath_AirGo 78a5043e9226 2018-10-25 184348_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\018_2018_10_25pm_airgo breath_AirGo 78a5043e9226 2018-10-25 184348_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/020_Perkins_Grace\airgo\020_2018_10_29pm_airgo breath_AirGo 78a5043e8ec0 2018-10-29 181528_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\020_2018_10_29pm_airgo breath_AirGo 78a5043e8ec0 2018-10-29 181528_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/021_Shannon_Kevin\airgo\021_2018_10_31pm_airgo breath_ AirGo 78a5043e94e7 2018-10-31 17_15_51_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\021_2018_10_31pm_airgo breath_ AirGo 78a5043e94e7 2018-10-31 17_15_51_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/023_Klaft_Gerlyn\airgo\023_2019_01_14pmairgo breath_AirGo 78a5043e8ec0 2019-01-14 171359_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\023_2019_01_14pmairgo breath_AirGo 78a5043e8ec0 2019-01-14 171359_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/025_Ferguson_Susan\airgo\025_2019_01_15,17_airgo breath_AirGo 78a5043e94e7 2019-01-15 17_36_19_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\025_2019_01_15,17_airgo breath_AirGo 78a5043e94e7 2019-01-15 17_36_19_Breath.csv


//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/038_Leewood_Alan\airgo\038_2019_02_07pm_airgo breath_AirGo78a5043e8eef 2019-02-07 17_58_13_Breath.csv
//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\038_2019_02_07pm_airgo breath_AirGo78a5043e8eef 2019-02-07 17_58_13_Breath.csv

In [66]:
v4_files[:5]

['//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/001_Sullivan\\airgo\\001_2018_06_06pm_airgo breath AirGo 78a5043e9810 2018-06-06 152600_Breath.csv',
 '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/002_Herling\\airgo\\002_2018_06_11pm_airgo breath AirGo 78a5043e8ea1 2018-06-11 194614_Breath.csv',
 '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/003_Carey\\airgo\\003_ 2018_06_18pm_airgo breath AirGo 78a5043e9b82 2018-06-18 203845_Breath.csv',
 '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/003_Carey\\airgo\\003_ 2018_06_20am_airgo breath AirGo 78a5043e9246 2018-06-20 082641_Breath.csv',
 '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/enrolled_subjects/003_Carey\\airgo\\003_ 2018_06_20pm_airgo breath AirGo 78a5043e9b82 2018-06-20 202651_Breath.csv']

In [67]:
savepaths[:5]

['//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\\001_2018_06_06pm_airgo breath AirGo 78a5043e9810 2018-06-06 152600_Breath.csv',
 '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\\002_2018_06_11pm_airgo breath AirGo 78a5043e8ea1 2018-06-11 194614_Breath.csv',
 '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\\003_ 2018_06_18pm_airgo breath AirGo 78a5043e9b82 2018-06-18 203845_Breath.csv',
 '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\\003_ 2018_06_20am_airgo breath AirGo 78a5043e9246 2018-06-20 082641_Breath.csv',
 '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research_single_files\\003_ 2018_06_20pm_airgo breath AirGo 78a5043e9b82 2018-06-20 202651_Breath.csv']

### for v4 breath:

In [45]:
def airgo_v4_to_research(filepath, savepath):
    AirGo_data = pd.read_csv(filepath)
    
    AirGo_data.columns = AirGo_data.columns.str.strip()
    print(AirGo_data.columns)
    # delete first entry because it has weird values, e.g. breathHigh = 0. also sampleTime+breathDuration is sometimes lower than sample time of second entry.
    AirGo_data.drop(0,0, inplace=True)

    AirGo_breath = pd.DataFrame()

    sampleTime_beginning = AirGo_data['sampleTime']
    sampleTime_end = AirGo_data['sampleTime'] + AirGo_data['breathDuration']
    sampleTime_raw = pd.Series(np.zeros(2*len(sampleTime_beginning)))
    sampleTime_raw.iloc[0::2] = sampleTime_beginning.values
    sampleTime_raw.iloc[1::2] = sampleTime_end.values

    girth = pd.Series(np.zeros(len(sampleTime_raw)))
    girth.iloc[0::2] = AirGo_data['breathLow'].values
    girth.iloc[1::2] = AirGo_data['breathHigh'].values

    accX = pd.Series(np.zeros(len(sampleTime_raw)))
    accX.iloc[0::2] = AirGo_data['accX'].values
    accX.iloc[1::2] = AirGo_data['accX'].values

    accY = pd.Series(np.zeros(len(sampleTime_raw)))
    accY.iloc[0::2] = AirGo_data['accY'].values
    accY.iloc[1::2] = AirGo_data['accY'].values

    accZ = pd.Series(np.zeros(len(sampleTime_raw)))
    accZ.iloc[0::2] = AirGo_data['accZ'].values
    accZ.iloc[1::2] = AirGo_data['accZ'].values

    # sample time in seconds:
    AirGo_breath['sampleTime'] = sampleTime_raw / 1000 
    AirGo_breath['girth'] = girth
    AirGo_breath['accX'] = accX
    AirGo_breath['accY'] = accY
    AirGo_breath['accZ'] = accZ

    # create the DateTime array:

    AirGo_breath['sampleTime']

    starting_date = re.search("\d\d\d\d-\d\d-\d\d \d\d\d\d\d\d", filename)
    starting_date = starting_date.group(0)
    starting_date = datetime.datetime.strptime(starting_date, '%Y-%m-%d %H%M%S')

    DateTime = pd.Series( np.zeros(AirGo_breath.shape[0],) )
    DateTime.index = AirGo_breath.index

    for counter, sampleTime in enumerate(AirGo_breath['sampleTime']):

        DateTime.iloc[counter] = starting_date + datetime.timedelta(seconds=sampleTime)

    AirGo_breath['DateTime'] = DateTime

    AirGo_breath.columns = ['sampleTime','Band','accX','accY','accZ','DateTime']
    AirGo_breath = AirGo_breath[['DateTime','Band','accX','accY','accZ']]

    # resampling:
    AirGo_breath = AirGo_breath.set_index('DateTime');
    AirGo_breath.index = AirGo_breath.index.round('100ms')
    resampled = AirGo_breath.resample(datetime.timedelta(seconds=0.1)).interpolate(method='pchip', order =3, limit_direction='forward', axis=0)
    resampled.reset_index(level=0, inplace=True)
    resampled = resampled[['DateTime','Band','accX','accY','accZ']]
    
    # drop duplicate:
    dup = resampled.duplicated(subset=['DateTime','Band'])
    resampled = resampled.mask(dup).dropna(axis = 0, how='all')
	
	# detect all open belt areas
	OpenBeltIdx = np.where(resampled['Band'] > 60000)[0]

	LastIdxOpenBeltAtBeginOfRecording = np.where(np.diff(OpenBeltIdx)>1)[0][0]
	LastIdxOpenBeltAtBeginOfRecording = OpenBeltIdx[LastIdxOpenBeltAtBeginOfRecording]
	FirstIdxOpenBeltAtEndOfRecording = np.where(np.diff(OpenBeltIdx)>1)[0][-1]
	FirstIdxOpenBeltAtEndOfRecording  = OpenBeltIdx[FirstIdxOpenBeltAtEndOfRecording+1]
	resampled = resampled.iloc[LastIdxOpenBeltAtBeginOfRecording+1:FirstIdxOpenBeltAtEndOfRecording,:]


    resampled['CRCStatus'] = np.nan
    
    resampled.to_csv(savepath, index = False)
    
    plt.plot(AirGo_breath.index[:1000], AirGo_breath.Band[:1000])
    plt.plot(resampled.DateTime[:10000], resampled.Band[:10000])
    plt.show()

In [46]:
filepath = 'C:/Users/wg984/Wolfgang/repos/ICU-Sleep/data/sample_airgo_breathv4.csv'
savepath = 'C:/Users/wg984/Wolfgang/repos/ICU-Sleep/data/sample_research_breath4.csv'
airgo_v4_to_research(filepath, savepath)

Index(['logId', 'sampleTime', 'rawBigBreath', 'breathDuration', 'breathLow',
       'breathHigh', 'accX', 'accY', 'accZ'],
      dtype='object')

In [34]:
# filename = '001_2018_06_06pm_airgo breath AirGo 78a5043e9810 2018-06-06 152600_Breath.csv'
AirGo_data = pd.read_csv('C:/Users/wg984/Wolfgang/repos/ICU-Sleep/data/sample_airgo_breathv4.csv')

In [35]:
AirGo_data.head()

,logId,sampleTime,rawBigBreath,breathDuration,breathLow,breathHigh,accX,accY,accZ
0,1,0,24,400,16088,0,3,0,14
1,1,310,128,201,16008,16136,3,1,14
2,1,911,112,200,16104,16216,3,1,14
3,1,1411,272,400,16224,16496,2,0,15
4,1,3911,792,401,16264,17056,3,0,14

In [5]:
AirGo_data.columns = AirGo_data.columns.str.strip()

# delete first entry because it has weird values, e.g. breathHigh = 0. also sampleTime+breathDuration is sometimes lower than sample time of second entry.
AirGo_data.drop(0,0, inplace=True)

AirGo_breath = pd.DataFrame()

sampleTime_beginning = AirGo_data['sampleTime']
sampleTime_end = AirGo_data['sampleTime'] + AirGo_data['breathDuration']
sampleTime_raw = pd.Series(np.zeros(2*len(sampleTime_beginning)))
sampleTime_raw.iloc[0::2] = sampleTime_beginning.values
sampleTime_raw.iloc[1::2] = sampleTime_end.values


girth = pd.Series(np.zeros(len(sampleTime_raw)))
girth.iloc[0::2] = AirGo_data['breathLow'].values
girth.iloc[1::2] = AirGo_data['breathHigh'].values

accX = pd.Series(np.zeros(len(sampleTime_raw)))
accX.iloc[0::2] = AirGo_data['accX'].values
accX.iloc[1::2] = AirGo_data['accX'].values

accY = pd.Series(np.zeros(len(sampleTime_raw)))
accY.iloc[0::2] = AirGo_data['accY'].values
accY.iloc[1::2] = AirGo_data['accY'].values

accZ = pd.Series(np.zeros(len(sampleTime_raw)))
accZ.iloc[0::2] = AirGo_data['accZ'].values
accZ.iloc[1::2] = AirGo_data['accZ'].values


# sample time in seconds:
AirGo_breath['sampleTime'] = sampleTime_raw / 1000 
AirGo_breath['girth'] = girth
AirGo_breath['accX'] = accX
AirGo_breath['accY'] = accY
AirGo_breath['accZ'] = accZ

# create the DateTime array:

AirGo_breath['sampleTime']

starting_date = re.search("\d\d\d\d-\d\d-\d\d \d\d\d\d\d\d", filename)
starting_date = starting_date.group(0)
starting_date = datetime.datetime.strptime(starting_date, '%Y-%m-%d %H%M%S')


DateTime = pd.Series( np.zeros(AirGo_breath.shape[0],) )
DateTime.index = AirGo_breath.index

for counter, sampleTime in enumerate(AirGo_breath['sampleTime']):

    DateTime.iloc[counter] = starting_date + datetime.timedelta(seconds=sampleTime)

AirGo_breath['DateTime'] = DateTime

# create the binary vector that indicates a new recording session

# 	bool_newRecording = np.concatenate((np.array([1]),np.zeros([AirGo_breath.shape[0]-1,])), axis = 0)        
# 
# 	AirGo_breath['newRecording'] = bool_newRecording

In [6]:
AirGo_breath.columns = ['sampleTime','Band','accX','accY','accZ','DateTime']
AirGo_breath = AirGo_breath[['DateTime','Band','accX','accY','accZ']]
AirGo_breath.head()

                     DateTime     Band  accX  accY  accZ
0  2018-06-06 15:26:00.310000  16008.0   3.0   1.0  14.0
1  2018-06-06 15:26:00.511000  16136.0   3.0   1.0  14.0
2  2018-06-06 15:26:00.911000  16104.0   3.0   1.0  14.0
3  2018-06-06 15:26:01.111000  16216.0   3.0   1.0  14.0
4  2018-06-06 15:26:01.411000  16224.0   2.0   0.0  15.0

In [7]:
# resampling:
AirGo_breath = AirGo_breath.set_index('DateTime');

In [8]:
AirGo_breath.head()

                            Band  accX  accY  accZ
DateTime
2018-06-06 15:26:00.310  16008.0   3.0   1.0  14.0
2018-06-06 15:26:00.511  16136.0   3.0   1.0  14.0
2018-06-06 15:26:00.911  16104.0   3.0   1.0  14.0
2018-06-06 15:26:01.111  16216.0   3.0   1.0  14.0
2018-06-06 15:26:01.411  16224.0   2.0   0.0  15.0

In [9]:
AirGo_breath.index = AirGo_breath.index.round('100ms')

In [10]:
resampled = AirGo_breath.resample(datetime.timedelta(seconds=0.1)).interpolate(method='pchip', order =3, limit_direction='forward', axis=0)

In [11]:
resampled.head()

                            Band  accX  accY  accZ
DateTime
2018-06-06 15:26:00.300  16008.0   3.0   1.0  14.0
2018-06-06 15:26:00.400  16094.0   3.0   1.0  14.0
2018-06-06 15:26:00.500  16136.0   3.0   1.0  14.0
2018-06-06 15:26:00.600  16131.0   3.0   1.0  14.0
2018-06-06 15:26:00.700  16120.0   3.0   1.0  14.0

In [12]:
%matplotlib widget
import matplotlib.pyplot as plt

In [15]:
plt.figure(figsize=(20,10))
plt.plot(AirGo_breath.index[:1000], AirGo_breath.Band[:1000])
plt.plot(resampled.index[:10000], resampled.Band[:10000])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [47]:
plt.figure(figsize=(20,10))
plt.plot(AirGo_breath.index, AirGo_breath.Band)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [16]:
plt.show()

In [27]:
resampled.reset_index(level=0, inplace=True)

In [28]:
resampled

                      DateTime          Band  accX  accY   accZ
0      2018-06-06 15:26:00.300  16008.000000   3.0   1.0   14.0
1      2018-06-06 15:26:00.400  16094.000000   3.0   1.0   14.0
2      2018-06-06 15:26:00.500  16136.000000   3.0   1.0   14.0
3      2018-06-06 15:26:00.600  16131.000000   3.0   1.0   14.0
4      2018-06-06 15:26:00.700  16120.000000   3.0   1.0   14.0
...                        ...           ...   ...   ...    ...
469728 2018-06-07 04:28:53.100  10085.333333   3.0   3.0  246.0
469729 2018-06-07 04:28:53.200  10050.666667   3.0   3.0  246.0
469730 2018-06-07 04:28:53.300  10032.000000   3.0   3.0  246.0
469731 2018-06-07 04:28:53.400  10081.600000   3.0   3.0  246.0
469732 2018-06-07 04:28:53.500  10192.000000   3.0   3.0  246.0

[469733 rows x 5 columns]