In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# because of prior. conversing, new files get into pool folder. with _v2.mat extension. so check what files have been converted and which not.

In [3]:
# original, to-be-converted files

In [4]:
LogDir = '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/DataProcessingLog/'
# LogDir = 'C:/Users/wg984/Wolfgang/ICU-Sleep/'
filep=LogDir+'toConvert.csv'
table=pd.read_csv(filep)

In [5]:
print(table.shape)
table.head()

(524, 1)

                  fileID
0  BLK12_1276-1540773486
1   BLK07_776-1556783082
2   BLK07_752-1560992100
3  BLK12_1282-1560113874
4  BLK12_1268-1563390617

In [6]:
# LogDirTemp = 'C:/Users/wg984/Wolfgang/ICU-Sleep/'
filep=LogDir+'ConversionStatus_Step1.csv'
ConversionStatus = pd.read_csv(filep)
ConversionStatus['Converted_V4'] = -np.ones([len(ConversionStatus),1],dtype=int)
ConversionStatus.iloc[0,:]

studyID                                       0
fileID                     BLK07_752-1560992100
StartTime                   2019-06-19 20:53:00
EndTime                     2019-06-21 14:00:00
stpIn                                      B752
tStart                                1.561e+09
tEnd                                1.56114e+09
tDischarge                          1.56114e+09
tAdmit                              1.56096e+09
unixFileStartTime                   1.56099e+09
unixFileEndTime                     1.56117e+09
fileStartTime               2019-06-20 00:55:00
MRN                                     2264238
VisitIdentifier                      3256745825
grp                             B752_1560995580
ugid                 B752_1560995580_1560992100
Converted_V4                                 -1
Name: 0, dtype: object

In [7]:
# which files have been converted:

In [8]:
convertedDir = '//eris1fs2/CDAC/bedmaster_data/batching/ICUSleep_2'
convertedDir2 = '//eris1fs2/CDAC/bedmaster_data/batching/wg984_20191129_163322'
convertedFiles = os.listdir(convertedDir) + os.listdir(convertedDir2)

In [9]:
# difference -> which have not been converted
# send those to new reconversion job.

In [10]:
cols = ConversionStatus.columns.tolist()
cols = cols[-1:] + cols[:-1]
ConversionStatus= ConversionStatus[cols]

In [11]:
ConversionStatus.tail()

,Converted_V4,studyID,fileID,StartTime,EndTime,stpIn,tStart,tEnd,tDischarge,tAdmit,unixFileStartTime,unixFileEndTime,fileStartTime,MRN,VisitIdentifier,grp,ugid
634,-1,192,BLK12_1260-1575680691,2019-12-07 14:35:00,2019-12-10 23:19:00,B1260,1.575747e+09,1.576038e+09,1.577855e+09,1.574766e+09,1.575681e+09,1.575748e+09,2019-12-07 01:04:51,1750989,3278402307,B1260_1575747300,B1260_1575747300_1575680691
635,-1,192,BLK12_1260-1575747932,2019-12-07 14:35:00,2019-12-10 23:19:00,B1260,1.575747e+09,1.576038e+09,1.577855e+09,1.574766e+09,1.575748e+09,1.577855e+09,2019-12-07 19:45:32,1750989,3278402307,B1260_1575747300,B1260_1575747300_1575747932
636,-1,192,BLK12_1272-1574812978,2019-11-26 22:31:00,2019-12-07 14:35:00,B1272,1.574825e+09,1.575747e+09,1.577855e+09,1.574766e+09,1.574813e+09,1.575789e+09,2019-11-27 00:02:58,1750989,3278402307,B1272_1574825460,B1272_1574825460_1574812978
637,-1,193,BLK12_1252-1574537100,2019-11-23 14:54:00,2019-11-29 12:38:00,B1252,1.574539e+09,1.575049e+09,1.577855e+09,1.574180e+09,1.574537e+09,1.575277e+09,2019-11-23 19:25:00,4533154,3281186837,B1252_1574538840,B1252_1574538840_1574537100
638,-1,194,BLK12_1290-1574722511,2019-11-25 18:31:00,2019-11-27 18:03:00,B1290,1.574725e+09,1.574896e+09,1.577855e+09,1.574688e+09,1.574723e+09,1.574966e+09,2019-11-25 22:55:11,6175987,3276933907,B1290_1574724660,B1290_1574724660_1574722511

In [12]:
convertedFileIDs = []
NotconvertedFileIDs = []
for fileID in ConversionStatus.fileID:
    fileIDconverted = np.unique([fileID for x in convertedFiles if fileID in x])
    fileIDNotconverted = np.unique([fileID for x in convertedFiles if not fileID in x])
    if len(fileIDconverted)>0:
        convertedFileIDs.append(fileID)
    elif len(fileIDNotconverted)>0:
        NotconvertedFileIDs.append(fileID)

In [13]:
for rowID in range(len(ConversionStatus)):
    if ConversionStatus.iloc[rowID].fileID in convertedFileIDs:
        ConversionStatus['Converted_V4'].iloc[rowID] = 1
    elif ConversionStatus.iloc[rowID].fileID in NotconvertedFileIDs:
        ConversionStatus['Converted_V4'].iloc[rowID] = 0

C:\Users\wg984\.conda\envs\visualization\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [14]:
ConversionStatus.shape

(639, 17)

In [15]:
ConversionStatus

,Converted_V4,studyID,fileID,StartTime,EndTime,stpIn,tStart,tEnd,tDischarge,tAdmit,unixFileStartTime,unixFileEndTime,fileStartTime,MRN,VisitIdentifier,grp,ugid
0,1,0,BLK07_752-1560992100,2019-06-19 20:53:00,2019-06-21 14:00:00,B752,1.560996e+09,1.561144e+09,1.561144e+09,1.560964e+09,1.560992e+09,1.561173e+09,2019-06-20 00:55:00,2264238,3256745825,B752_1560995580,B752_1560995580_1560992100
1,1,1,BLK07_768-1528197453,2018-06-05 07:16:00,2018-06-08 14:45:00,B768,1.528201e+09,1.528487e+09,1.528657e+09,1.528165e+09,1.528197e+09,1.528522e+09,2018-06-05 11:17:33,1298742,3203968691,B768_1528200960,B768_1528200960_1528197453
2,1,2,ELL04_432-1528528595,2018-06-09 03:48:00,2018-06-11 11:30:00,E432,1.528534e+09,1.528735e+09,1.529348e+09,1.528528e+09,1.528529e+09,1.528934e+09,2018-06-09 07:16:35,6378271,3204668863,E432_1528534080,E432_1528534080_1528528595
3,1,2,ELL04_432-1528528595,2018-06-11 14:27:00,2018-06-12 22:07:00,E432,1.528745e+09,1.528859e+09,1.529348e+09,1.528528e+09,1.528529e+09,1.528934e+09,2018-06-09 07:16:35,6378271,3204668863,E432_1528745220,E432_1528745220_1528528595
4,1,3,BLK07_754-1529299617,2018-06-18 01:12:00,2018-06-21 21:56:00,B754,1.529302e+09,1.529636e+09,1.530216e+09,1.529270e+09,1.529300e+09,1.529685e+09,2018-06-18 05:26:57,1910753,3205625962,B754_1529302320,B754_1529302320_1529299617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,0,192,BLK12_1260-1575680691,2019-12-07 14:35:00,2019-12-10 23:19:00,B1260,1.575747e+09,1.576038e+09,1.577855e+09,1.574766e+09,1.575681e+09,1.575748e+09,2019-12-07 01:04:51,1750989,3278402307,B1260_1575747300,B1260_1575747300_1575680691
635,0,192,BLK12_1260-1575747932,2019-12-07 14:35:00,2019-12-10 23:19:00,B1260,1.575747e+09,1.576038e+09,1.577855e+09,1.574766e+09,1.575748e+09,1.577855e+09,2019-12-07 19:45:32,1750989,3278402307,B1260_1575747300,B1260_1575747300_1575747932
636,0,192,BLK12_1272-1574812978,2019-11-26 22:31:00,2019-12-07 14:35:00,B1272,1.574825e+09,1.575747e+09,1.577855e+09,1.574766e+09,1.574813e+09,1.575789e+09,2019-11-27 00:02:58,1750989,3278402307,B1272_1574825460,B1272_1574825460_1574812978
637,1,193,BLK12_1252-1574537100,2019-11-23 14:54:00,2019-11-29 12:38:00,B1252,1.574539e+09,1.575049e+09,1.577855e+09,1.574180e+09,1.574537e+09,1.575277e+09,2019-11-23 19:25:00,4533154,3281186837,B1252_1574538840,B1252_1574538840_1574537100
638,1,194,BLK12_1290-1574722511,2019-11-25 18:31:00,2019-11-27 18:03:00,B1290,1.574725e+09,1.574896e+09,1.577855e+09,1.574688e+09,1.574723e+09,1.574966e+09,2019-11-25 22:55:11,6175987,3276933907,B1290_1574724660,B1290_1574724660_1574722511

In [18]:
ConversionStatus[ConversionStatus.studyID == 31]

,Converted_V4,studyID,fileID,StartTime,EndTime,stpIn,tStart,tEnd,tDischarge,tAdmit,unixFileStartTime,unixFileEndTime,fileStartTime,MRN,VisitIdentifier,grp,ugid
88,0,31,ELL09_924-1546145882,2018-12-30 00:50:00,2019-01-02 18:29:00,E924,1.546149e+09,1.546472e+09,1.546986e+09,1.546131e+09,1.546146e+09,1.546478e+09,2018-12-30 04:58:02,1876849,3231166228,E924_1546149000,E924_1546149000_1546145882
89,1,31,BLK07_756-1547899217,2019-01-22 18:29:00,2019-01-26 18:03:00,B756,1.548200e+09,1.548544e+09,1.549489e+09,1.548178e+09,1.547899e+09,1.548200e+09,2019-01-19 12:00:17,1876849,3234178903,B756_1548199740,B756_1548199740_1547899217
90,1,31,BLK07_756-1548200185,2019-01-22 18:29:00,2019-01-26 18:03:00,B756,1.548200e+09,1.548544e+09,1.549489e+09,1.548178e+09,1.548200e+09,1.548200e+09,2019-01-22 23:36:25,1876849,3234178903,B756_1548199740,B756_1548199740_1548200185
91,1,31,BLK07_756-1548200241,2019-01-22 18:29:00,2019-01-26 18:03:00,B756,1.548200e+09,1.548544e+09,1.549489e+09,1.548178e+09,1.548200e+09,1.548569e+09,2019-01-22 23:37:21,1876849,3234178903,B756_1548199740,B756_1548199740_1548200241

In [21]:
StudyDir = '//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/Study/'
filep=StudyDir+'ConversionStatus.csv'
ConversionStatus.to_csv(filep,index=False)

In [23]:
NotconvertedFileIDs = pd.DataFrame(NotconvertedFileIDs, columns=['fileID'])

In [24]:
NotconvertedFileIDs.shape

(0, 1)

In [20]:
NotconvertedFileIDs.to_csv(LogDir+'toConvert.csv', index = False)

AttributeError: 'list' object has no attribute 'to_csv'

In [26]:
LogDir

'//mad3/MGH-NEURO-CDAC/Projects/ICU_SLEEP_STUDY/data/data_analysis/DataProcessingLog/'

In [27]:
ConversionStatus.head()

,Converted_V4,studyID,fileID,StartTime,EndTime,stpIn,tStart,tEnd,tDischarge,tAdmit,unixFileStartTime,unixFileEndTime,fileStartTime,MRN,VisitIdentifier,grp,ugid
0,1,0,BLK07_756-1547899217,2019-01-22 18:29:00,2019-01-26 18:03:00,B756,1.548200e+09,1.548544e+09,1.549489e+09,1.548178e+09,1.547899e+09,1.548200e+09,2019-01-19 12:00:17,1876849,3234178903,B756_1548199740,B756_1548199740_1547899217
1,1,0,BLK07_756-1548200185,2019-01-22 18:29:00,2019-01-26 18:03:00,B756,1.548200e+09,1.548544e+09,1.549489e+09,1.548178e+09,1.548200e+09,1.548200e+09,2019-01-22 23:36:25,1876849,3234178903,B756_1548199740,B756_1548199740_1548200185
2,1,0,BLK07_752-1560992100,2019-06-19 20:53:00,2019-06-21 14:00:00,B752,1.560996e+09,1.561144e+09,1.561144e+09,1.560964e+09,1.560992e+09,1.561173e+09,2019-06-20 00:55:00,2264238,3256745825,B752_1560995580,B752_1560995580_1560992100
3,1,0,BLK07_756-1548200241,2019-01-22 18:29:00,2019-01-26 18:03:00,B756,1.548200e+09,1.548544e+09,1.549489e+09,1.548178e+09,1.548200e+09,1.548569e+09,2019-01-22 23:37:21,1876849,3234178903,B756_1548199740,B756_1548199740_1548200241
4,1,1,BLK07_768-1528197453,2018-06-05 07:16:00,2018-06-08 14:45:00,B768,1.528201e+09,1.528487e+09,1.528657e+09,1.528165e+09,1.528197e+09,1.528522e+09,2018-06-05 11:17:33,1298742,3203968691,B768_1528200960,B768_1528200960_1528197453

In [28]:
ConversionStatus[ConversionStatus.studyID == 75]

,Converted_V4,studyID,fileID,StartTime,EndTime,stpIn,tStart,tEnd,tDischarge,tAdmit,unixFileStartTime,unixFileEndTime,fileStartTime,MRN,VisitIdentifier,grp,ugid
251,1,75,BLK07_776-1556782731,2019-04-29 18:45:00,2019-05-02 03:25:00,B776,1.556582e+09,1.556786e+09,1.556786e+09,1.555482e+09,1.556783e+09,1.556783e+09,2019-05-02 07:38:51,6292253,3246833222,B776_1556581500,B776_1556581500_1556782731
252,1,75,BLK07_756-1555462981,2019-04-17 01:14:00,2019-04-22 15:04:00,B756,1.555482e+09,1.555963e+09,1.556786e+09,1.555482e+09,1.555463e+09,1.556050e+09,2019-04-17 01:03:01,6292253,3246833222,B756_1555481640,B756_1555481640_1555462981
253,1,75,BLK07_776-1556783082,2019-04-29 18:45:00,2019-05-02 03:25:00,B776,1.556582e+09,1.556786e+09,1.556786e+09,1.555482e+09,1.556783e+09,1.556785e+09,2019-05-02 07:44:42,6292253,3246833222,B776_1556581500,B776_1556581500_1556783082
254,1,75,BLK07_776-1556784805,2019-04-29 18:45:00,2019-05-02 03:25:00,B776,1.556582e+09,1.556786e+09,1.556786e+09,1.555482e+09,1.556785e+09,1.556797e+09,2019-05-02 08:13:25,6292253,3246833222,B776_1556581500,B776_1556581500_1556784805
255,1,75,BLK07_776-1556580656,2019-04-29 18:45:00,2019-05-02 03:25:00,B776,1.556582e+09,1.556786e+09,1.556786e+09,1.555482e+09,1.556581e+09,1.556582e+09,2019-04-29 23:30:56,6292253,3246833222,B776_1556581500,B776_1556581500_1556580656
256,1,75,BLK07_776-1556581850,2019-04-29 18:45:00,2019-05-02 03:25:00,B776,1.556582e+09,1.556786e+09,1.556786e+09,1.555482e+09,1.556582e+09,1.556783e+09,2019-04-29 23:50:50,6292253,3246833222,B776_1556581500,B776_1556581500_1556581850

In [29]:
6405518

6405518