In [1]:
%matplotlib widget
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
import scipy.io as sio
import h5py
import datetime
from scipy.integrate import simps
from tqdm import tqdm

%load_ext autoreload
%autoreload 2

In [2]:
def get_grass_start_end_time(starttime_raw, endtime_raw):
    
    time_str_elements = starttime_raw.flatten()
    start_time = ''.join(chr(time_str_elements[j]) for j in range(time_str_elements.shape[0]))
    time_str_elements = endtime_raw.flatten()
    end_time = ''.join(chr(time_str_elements[j]) for j in range(time_str_elements.shape[0]))

    start_time = start_time.split(':')
    second_elements = start_time[-1].split('.')
    start_time = datetime.datetime(1990,1,1,hour=int(float(start_time[0])), minute=int(float(start_time[1])),
        second=int(float(second_elements[0])), microsecond=int(float('0.'+second_elements[1])*1000000))
    end_time = end_time.split(':')
    second_elements = end_time[-1].split('.')
    end_time = datetime.datetime(1990,1,1,hour=int(float(end_time[0])), minute=int(float(end_time[1])),
        second=int(float(second_elements[0])), microsecond=int(float('0.'+second_elements[1])*1000000))

    return start_time, end_time

def check_load_mgh_dataset(data_path, label_path, channels=None, report_and_actual_time_tol=300, reverse_sign=False):

    gender = None
    handedness = None
    
    try: # usually Grass, saved as pre 7.3 format:
        ff = sio.loadmat(signalfilepath)
        data_path = os.path.basename(signalfilepath)
        if 's' not in ff:
            raise Exception('No signal found in %s.'%data_path)
        signal = ff['s']
        if reverse_sign:
            signal = -signal
        channel_names = [ff['hdr'][0,i]['signal_labels'][0].upper().replace('EKG','ECG') for i in range(ff['hdr'].shape[1])]
        gender = None
        handedness = None
        if 'grass' in signalfilepath:
            Fs = 200.
        else:
            raise Exception('Safety check to make sure this is Grass data with Fs=200')
        # Label part for grass:
        if 'grass' in signalfilepath:
            # load labels
            with h5py.File(labelfilepath) as ffl:
                sleep_stage = ffl['stage'][()].flatten()
                apnea = ffl['apnea'][()].flatten()
                start_time, end_time = get_grass_start_end_time(ffl['features']['StartTime'][()].flatten(), ffl['features']['EndTime'][()].flatten())


    except: # saved as .mat 7.3. new grass or natus files:
        with h5py.File(signalfilepath,'r') as ff:

            hdr = ff['hdr']
            signal_labels = hdr['signal_labels'][:]
            channel_names = [ ''.join(list(map(chr, ff[signal_labels[i,0]][:]))) for i in range(signal_labels.shape[0]) ]
            channel_names = [channel.upper() for channel in channel_names]
            signal = ff['s'][()]
            signal = np.transpose(signal);

            if 'recording' in ff.keys(): # only available for natus:
                year = int(np.squeeze(ff['recording']['year']))
                month = int(np.squeeze(ff['recording']['month']))
                day = int(np.squeeze(ff['recording']['day']))
                hour = int(np.squeeze(ff['recording']['hour']))
                if (hour >= 7) and (hour <=10):         # 'typo' by sleep techs
                    hour = hour + 12
                minute = int(np.squeeze(ff['recording']['minute']))
                second = int(np.squeeze(ff['recording']['second']))
                millisecond = int(np.squeeze(ff['recording']['millisecond']))
                Fs = int(np.squeeze(ff['recording']['samplingrate']))

                start_time = datetime.datetime(1990,1,1,hour=hour, minute=minute,
                        second=second, microsecond=int(millisecond*1000))
                end_time = start_time+datetime.timedelta(seconds=max(signal.shape)/Fs)

            else: # grass:
                if 'grass' in signalfilepath:
                    Fs = 200.
                else:
                    raise Exception('Safety check to make sure this is Grass data with Fs=200')

            # Label part for grass:
            ff.close()

        # load labels
        with h5py.File(labelfilepath, 'r') as ffl:
            sleep_stage = ffl['stage'][()].flatten()
            apnea = ffl['apnea'][()].flatten()
            if 'grass' in signalfilepath:
                start_time, end_time = get_grass_start_end_time(ffl['features']['StartTime'][()].flatten(), ffl['features']['EndTime'][()].flatten())
            ffl.close()

    # end of loading part
    ##################################
    
    # check signal length = sleep stage length
    if sleep_stage.shape[0]!=signal.shape[1]:
        raise Exception('Inconsistent sleep stage length (%d) and signal length (%d) in %s'%(sleep_stage.shape[0],signal.shape[1],data_path))

    # only take signal channels to study
    if channels is None:
        signal_channel_ids = list(range(len(channel_names)))
        
    elif 'SumEffort' in channels:
        signal_channel_ids = []
        signal_names = []
        for ichannel in ['ABD','CHEST']:
            #channel_name_pattern = re.compile(channels[i][:2].upper()+'-*'+channels[i][-2:].upper())
            found = False
            for j in range(len(channel_names)):
                if channel_names[j]==ichannel.upper():
                    signal_channel_ids.append(j)
                    signal_names.append(channel_names[j])
                    found = True
                    break
            if not found:
                raise Exception('Channel %s is not found.'%ichannel)
        signal = signal[signal_channel_ids,:]#.T
        # do effort belt average here:
        signal = np.sum(signal,0,keepdims=1)/2
        
    else:
        signal_channel_ids = []
        signal_names = []
        for i in range(len(channels)):
            #channel_name_pattern = re.compile(channels[i][:2].upper()+'-*'+channels[i][-2:].upper())
            found = False
            for j in range(len(channel_names)):
                if channel_names[j]==channels[i].upper():
                    signal_channel_ids.append(j)
                    signal_names.append(channel_names[j])
                    found = True
                    break
            if not found:
                continue
#                 raise Exception('Channel %s is not found.'%channels[i])
        signal = signal[signal_channel_ids,:]#.T

    # check whether the signal contains NaN
    if np.any(np.isnan(signal)):
        raise Exception('Found Nan in signal in %s'%data_path)

    # check whether sleep_stage contains all 5 stages
    stages = np.unique(sleep_stage[np.logical_not(np.isnan(sleep_stage))]).astype(int).tolist()
    if len(stages)<=1:
        if len(stages)==0:
            raise Exception('no sleep stages available in %s'%data_path)
        if stages[0] != 5: # only reasonable 1 sleepstage if all is Wake (==5), else raise Error
            raise Exception('#sleep stage <= 1: %s in %s'%(stages,data_path))

    params = {'Fs':Fs*1.0, 'signal_channel_ids':signal_channel_ids, 'signal_names':signal_names}
    if gender is not None:
        params['gender'] = gender
    if handedness is not None:
        params['handedness'] = handedness
    return signal, sleep_stage, apnea, params

In [3]:
if 1:
    
    table_grass = pd.read_csv('/media/mad3/Datasets_ConvertedData/sleeplab/grass_studies_list.csv')
    table_natus = pd.read_csv('/media/mad3/Datasets_ConvertedData/sleeplab/natus_studies_list.csv')
    assert np.all(table_grass.columns == table_natus.columns)
    sleeplab_table = pd.concat([table_grass, table_natus], axis=0)
    sleeplab_table = sleeplab_table[pd.notna(sleeplab_table.MRN)]
    sleeplab_table.reset_index(inplace=True, drop=True)
    
    sleeplab_table['MRN_int'] = [int(str(x).replace('-','').replace('/','').replace('X','0')) for x in sleeplab_table['MRN']]
    dates = pd.to_datetime(sleeplab_table.DateOfVisit, infer_datetime_format=1)


    for jloc, row in sleeplab_table.iterrows():
        path = row.Path
        path = path.replace('M:', '/media/mad3')
        path = path.replace('\\', '/')

        signalfile = [x for x in os.listdir(path) if 'Signal' in x]
        if len(signalfile) > 0:
            signalfile = signalfile[0]
        else:
            continue 

        labelfile = [x for x in os.listdir(path) if 'Labels' in x]
        if len(labelfile) > 0:
            labelfile = labelfile[0]
        else:
            continue

        sleeplab_table.loc[jloc, 'Signalfile'] = os.path.join(path, signalfile)
        sleeplab_table.loc[jloc, 'Labelfile'] = os.path.join(path, labelfile)

    sleeplab_table.to_csv('sleeplab_table.csv', index=False)

else:
    sleeplab_table = pd.read_csv('sleeplab_table.csv')

In [4]:
hypoxic_table = pd.read_excel('Hypoxic_Study_Table.xlsx', engine='openpyxl')

control_table = pd.read_excel('/scr/wolfgang/Hypoxia_Study/control_group.xls')

In [5]:
control_table = control_table[control_table.MRN_Type.apply(lambda x: 'MGH' in x)]
control_table['MRN_original'] = control_table['MRN']
control_table.loc[control_table.MRN_Type == 'PMRN, MGH, BWH', 'MRN'] = control_table.loc[control_table.MRN_Type == 'PMRN, MGH, BWH'].MRN.apply(lambda x: x.split(',')[1].strip())
control_table.loc[control_table.MRN_Type == 'PMRN, MGH', 'MRN'] = control_table.loc[control_table.MRN_Type == 'PMRN, MGH'].MRN.apply(lambda x: x.split(',')[1].strip())
control_table['MRN'] = control_table['MRN'].astype(int)

In [6]:
# print('TMP!!!!!!')

# hypoxic_table = hypoxic_table.iloc[:20]
# control_table = control_table.iloc[:20]

In [7]:
def mrn_matching(table):
    # first, let's check if there is a perfect match with MRN for MGH patients.
    table['MRN_Match'] = 0
    
#     table_MGH = table[table.MRN_Type == 'MGH']
    table.loc[table.index,'MRN_Match'] = np.isin(table.MRN, sleeplab_table.MRN_int)
    
    if 'Name' in table.columns:
        table['LastName'] = [str(x).split(', ')[0] for x in table.Name.values]
        table['FirstName'] = [str(x).split(', ')[1] if ', ' in str(x) else np.nan for x in table.Name.values]

    return table

hypoxic_table = mrn_matching(hypoxic_table)
control_table = mrn_matching(control_table)

In [8]:
import Levenshtein
import pdb;

In [9]:
if 1:
    hypoxic_table['NameMatch'] = np.nan
    hypoxic_table['NewMRN'] = np.nan

    for index, row in hypoxic_table.iterrows():

        for index2, row2 in sleeplab_table.iterrows():
            try:
                if Levenshtein.distance(str(row.LastName), str(row2.LastName)) <= 2:
                    if Levenshtein.distance(str(row.FirstName), str(row2.FirstName)) <= 2:
                        hypoxic_table.loc[index, 'NameMatch'] = 1
                        hypoxic_table.loc[index, 'MatchedMRN'] = int(row2.MRN_int)
                        hypoxic_table.loc[index, 'MatchedLastName'] = row2.LastName
                        hypoxic_table.loc[index, 'MatchedFirstName'] = row2.FirstName
                        hypoxic_table.loc[index, 'MatchedDOB'] = row2.DateOfBirth

            except Exception as e:
                if not str(e) == 'distance expected two Strings or two Unicodes':
                    print(e)
                continue

In [10]:
hypoxic_table.MRN_Match.sum()

409

In [11]:
print(hypoxic_table.MRN_Match.sum())
print(control_table.MRN_Match.sum())

409
8199

In [12]:
from sleep_analysis_functions import compute_spo2_clean, compute_hypoxia_burden, desaturation_detection, hypoxaemic_burden_minutes

def compute_hypoxia_statistics(signalfilepath, labelfilepath):
    
    signal, sleep_stage, apnea, params = check_load_mgh_dataset(signalfilepath, labelfilepath, channels=['SAO2','SPO2','PTAF', 'CFlow'], report_and_actual_time_tol=300, reverse_sign=False)
    
    data = pd.DataFrame()
    data['Apnea'] = apnea
    for iSignal, name in enumerate(params['signal_names']):
        data[name] = signal[iSignal]
    data.rename({'SAO2':'SPO2'}, axis=1, inplace=True)
    data['spo2'] = data['SPO2']
    fs = int(params['Fs'])

    dt_start = pd.Timestamp('2000-01-01 00:00:00')
    dt_end = dt_start + datetime.timedelta(seconds=(data.shape[0]-1) / fs)
    pseudo_dt_index = pd.date_range(start=dt_start, end=dt_end, periods=data.shape[0])
    data.index = pseudo_dt_index

    data = compute_spo2_clean(data, fs=fs)
    data['spo2'] = data['spo2_clean']

    data['Apnea_Binary'] = np.isin(data['Apnea'],[1,2,3,4]).astype(int)
    data['Apnea_End'] = np.isin(data['Apnea_Binary'].diff(), [-1])
    
    sleep_stage = sleep_stage[np.logical_not(pd.isna(sleep_stage))]
    hours_sleep = sum(sleep_stage<5)/fs/3600
    
    data, hypoxia_burden = compute_hypoxia_burden(data, fs, hours_sleep=hours_sleep)
    
    
    T90burden, T90desaturation, T90nonspecific = hypoxaemic_burden_minutes(data['spo2'].values, fs)
    
    AHI = np.round(sum(data['Apnea_End'])/hours_sleep,1)

    return hypoxia_burden, AHI, hours_sleep, T90burden, T90desaturation, T90nonspecific

In [13]:
sleeplab_avail_full = pd.DataFrame()

# hypoxic_table[f'Visit_1_HypoxiaBurden'] = np.nan
for i_visit in range(10):
    hypoxic_table.loc[index,f'Visit_{i_visit+1}_HypoxiaBurden'] = np.nan
    hypoxic_table.loc[index,f'Visit_{i_visit+1}_AHI'] = np.nan
    hypoxic_table.loc[index,f'Visit_{i_visit+1}_Total_Sleep_Time'] = np.nan
    hypoxic_table.loc[index,f'Visit_{i_visit+1}_T90_minutes'] = np.nan
    hypoxic_table.loc[index,f'Visit_{i_visit+1}_T90_minutes_desat'] = np.nan
    hypoxic_table.loc[index,f'Visit_{i_visit+1}_T90_minutes_unspecific'] = np.nan

for index, row in tqdm(hypoxic_table.iterrows()):
#     pdb.set_trace()
    try:
        new_patient = 0

        if row['MRN_Match'] == 1:
            sleeplab_avail = sleeplab_table[np.isin(sleeplab_table.MRN_int, row.MRN)].copy()
        elif row['NameMatch'] == 1:
            sleeplab_avail = sleeplab_table[np.isin(sleeplab_table.MRN_int, row.MatchedMRN)].copy()
        else:
            continue

        num_of_visits = sleeplab_avail.shape[0]
        hypoxic_table.loc[index,'num_of_visits'] = num_of_visits

        i_visit = -1
        for index_sleeplab, row_sleeplab in sleeplab_avail.iterrows():

            i_visit += 1

    #         if not f'Visit_{i_visit+1}_HypoxiaBurden' in hypoxic_table.columns:
    #             do_nothing = 1
            if not pd.isna(hypoxic_table.loc[index,f'Visit_{i_visit+1}_HypoxiaBurden']):
                # this has already been computed in prior loop/computation, let's skip it.
                continue

            # if there is at least one visist which is new, do computation and add to table eventually:
            new_patient = 1

            hypoxic_table.loc[index,f'Visit_{i_visit+1}_Date'] = sleeplab_avail.iloc[i_visit].DateOfVisit		
            hypoxic_table.loc[index,f'Visit_{i_visit+1}_Type'] = sleeplab_avail.iloc[i_visit].TypeOfTest

            path = sleeplab_avail.iloc[i_visit].Path
            signalfile = sleeplab_avail.iloc[i_visit].Signalfile
            labelfile = sleeplab_avail.iloc[i_visit].Labelfile

            hypoxic_table.loc[index,f'Visit_{i_visit+1}_Path'] = path
            hypoxic_table.loc[index,f'Visit_{i_visit+1}_Signalfile'] = signalfile
            hypoxic_table.loc[index,f'Visit_{i_visit+1}_Labelfile'] = labelfile

            signalfilepath = signalfile # os.path.join(path, signalfile)
            labelfilepath = labelfile # os.path.join(path, labelfile)

            if not pd.isna(labelfile): #  == '[]':
    #             try:
                hypoxia_burden, ahi, total_sleep_time, T90burden, T90desaturation, T90nonspecific = compute_hypoxia_statistics(signalfilepath, labelfilepath)

    #             except Exception as e:
    #                 print(e)
    #                 print(signalfilepath)
    #                 print(labelfilepath)
    #                 continue

            else:
                [hypoxia_burden, ahi, total_sleep_time, T90burden, T90desaturation, T90nonspecific] = [np.nan]*6

            hypoxic_table.loc[index,f'Visit_{i_visit+1}_HypoxiaBurden'] = [hypoxia_burden]
            hypoxic_table.loc[index,f'Visit_{i_visit+1}_AHI'] = [ahi]
            hypoxic_table.loc[index,f'Visit_{i_visit+1}_Total_Sleep_Time'] = [total_sleep_time]
            hypoxic_table.loc[index,f'Visit_{i_visit+1}_T90_minutes'] = [T90burden]
            hypoxic_table.loc[index,f'Visit_{i_visit+1}_T90_minutes_desat'] = [T90desaturation]
            hypoxic_table.loc[index,f'Visit_{i_visit+1}_T90_minutes_unspecific'] = [T90nonspecific]

            # also fill up sleeplab_available table:
            sleeplab_avail.loc[index_sleeplab, 'Hypoxia_Burden'] = [hypoxia_burden]
            sleeplab_avail.loc[index_sleeplab, 'AHI'] = [ahi]
            sleeplab_avail.loc[index_sleeplab, 'Total_Sleep_Time'] = [np.round(total_sleep_time,1)]
            sleeplab_avail.loc[index_sleeplab, 'T90_minutes'] = [np.round(T90burden,1)]
            sleeplab_avail.loc[index_sleeplab, 'T90_minutes_desat'] = [np.round(T90desaturation,1)]
            sleeplab_avail.loc[index_sleeplab, 'T90_minutes_unspecific'] = [np.round(T90nonspecific,1)]

        if new_patient == 1:
            sleeplab_avail_full = pd.concat([sleeplab_avail_full, sleeplab_avail], axis=0)
            sleeplab_avail_full.to_csv('sleeplab_avail_full_tmp.csv', index=False)
            hypoxic_table.to_csv('hypoxic_table_results_tmp.csv', index=False)

    except Exception as e:
        print(e)
        continue

0it [00:00, ?it/s]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:490: RuntimeWarning: invalid value encountered in greater_equal
  desaturation_spo2[spo2_signal >= minimum_spo2_level] = 0
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1391: RuntimeWarning: All-NaN slice encountered
  overwrite_input, interpolation)
21it [05:04, 17.51s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:464: RuntimeWarning: invalid value encountered in less
  spo2_drop[spo2_drop<0] = 0
/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:478: RuntimeWarning: invalid value encountered in less
  areas_robust = areas[areas < np.std(areas)*3]
28it [08:55, 55.51s/it]

Timestamp('2000-01-01 03:13:36.846875188')

37it [13:56, 25.05s/it]

index 10123270 is out of bounds for axis 0 with size 10123270

47it [20:09, 58.35s/it]

Timestamp('2000-01-01 02:45:05.883203276')

62it [28:59, 27.21s/it]

Timestamp('2000-01-01 00:58:55.821484328')

68it [34:43, 38.23s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:479: RuntimeWarning: divide by zero encountered in double_scalars
  hypoxic_burden = np.sum(areas_robust)/hours_sleep
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/ipykernel_launcher.py:34: RuntimeWarning: divide by zero encountered in double_scalars
127it [1:04:55, 25.51s/it]

Timestamp('2000-01-01 02:34:34.809765553')

136it [1:12:34, 85.12s/it]

Timestamp('2000-01-01 04:33:20.158593547')

144it [1:15:25, 28.35s/it]

index 5296400 is out of bounds for axis 0 with size 5296400

160it [1:28:31, 50.53s/it]

Timestamp('2000-01-01 01:17:02.935937455')

164it [1:34:47, 76.75s/it]

Timestamp('2000-01-01 04:30:05.984765335')

169it [1:37:26, 55.73s/it]

Timestamp('2000-01-01 03:09:46.089062667')

178it [1:42:59, 44.29s/it]

Timestamp('2000-01-01 04:22:05.467578402')

192it [1:57:42, 101.80s/it]

Timestamp('2000-01-01 03:58:18.782031071')

205it [2:04:06, 79.50s/it]

Timestamp('2000-01-01 06:45:33.050390407')

220it [2:19:03, 107.01s/it]

Timestamp('2000-01-01 07:17:47.723827926')

237it [2:24:17, 25.91s/it]

Timestamp('2000-01-01 05:56:06.721094043')

248it [2:33:15, 46.13s/it]

Timestamp('2000-01-01 00:53:04.839062470')

261it [2:40:10, 28.51s/it]

Timestamp('2000-01-01 02:10:56.191015657')

269it [2:44:05, 26.02s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Diaz_Carmen_082917_2310.000/Signal_Diaz_Carmen_082917_2310.000.mat

285it [3:04:00, 84.02s/it]

Timestamp('2000-01-01 01:36:41.271093802')

303it [3:13:35, 67.10s/it]

Timestamp('2000-01-01 04:09:57.444921998')

330it [3:24:36, 36.43s/it]

Timestamp('2000-01-01 01:51:24.909374878')

349it [3:37:27, 47.39s/it]

Timestamp('2000-01-01 02:36:14.872265783')

357it [3:41:53, 44.13s/it]

Timestamp('2000-01-01 02:12:31.892187366')

375it [3:52:29, 42.02s/it]

Timestamp('2000-01-01 03:25:31.726171976')

386it [3:56:25, 32.01s/it]

Timestamp('2000-01-01 00:48:29.372656285')

402it [4:02:50, 19.06s/it]

Timestamp('2000-01-01 01:54:34.160937420')

407it [4:08:52, 77.20s/it]

cannot convert float NaN to integer

496it [4:49:43, 38.36s/it]

Timestamp('2000-01-01 01:51:24.909374878')

506it [4:51:53, 22.22s/it]

Timestamp('2000-01-01 00:56:10.557031263')

589it [5:18:54, 28.01s/it]

Timestamp('2000-01-01 02:12:35.112109512')

591it [5:19:50, 27.98s/it]

index 9577631 is out of bounds for axis 0 with size 9577631

613it [5:33:31, 78.52s/it]

Timestamp('2000-01-01 04:01:21.024999876')

620it [5:38:57, 53.92s/it]

index 6443200 is out of bounds for axis 0 with size 6443200

621it [5:43:35, 121.27s/it]

'Visit_11_HypoxiaBurden'

644it [5:49:55, 25.44s/it]

index 8878671 is out of bounds for axis 0 with size 8878671

664it [5:59:22, 76.19s/it]

Timestamp('2000-01-01 00:33:04.383203167')

683it [6:04:41, 21.80s/it]

Timestamp('2000-01-01 02:57:13.125390526')

692it [6:05:30, 12.58s/it]

index 9901051 is out of bounds for axis 0 with size 9901051

699it [6:08:10, 22.77s/it]

Timestamp('2000-01-01 03:02:26.981249901')

728it [6:11:10,  7.79s/it]

Timestamp('2000-01-01 00:15:28.419531259')

731it [6:12:47, 14.06s/it]

Timestamp('2000-01-01 02:19:46.739453087')

773it [6:26:38, 33.89s/it]

Timestamp('2000-01-01 02:20:03.159765504')

789it [6:32:51, 47.62s/it]

Timestamp('2000-01-01 02:42:42.613671959')

802it [6:48:00, 97.42s/it]

Timestamp('2000-01-01 01:13:52.189843705')

808it [6:50:00, 57.34s/it]

Timestamp('2000-01-01 01:43:03.830859285')

811it [6:52:31, 51.55s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:436: RuntimeWarning: Mean of empty slice
  mean_spo2 = np.nanmean(np.array(spo2_collection), axis=0)
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
821it [6:58:47, 39.91s/it]

Timestamp('2000-01-01 00:49:38.224218795')

890it [7:16:31, 47.45s/it]

Timestamp('2000-01-01 01:46:38.007031139')

919it [7:27:57, 59.21s/it]

Timestamp('2000-01-01 00:40:27.698046917')

936it [7:31:20, 28.93s/it]

In [14]:
hypoxic_table.dropna(how='all', axis=1, inplace=True)

In [15]:
hypoxic_table.loc[pd.notna(hypoxic_table['Visit_1_HypoxiaBurden'])].iloc[:, 40:55]

,LVsat,MRN_Match,LastName,FirstName,NameMatch,MatchedMRN,MatchedLastName,MatchedFirstName,MatchedDOB,Visit_1_HypoxiaBurden,Visit_1_AHI,Visit_1_Total_Sleep_Time,Visit_1_T90_minutes,Visit_1_T90_minutes_desat,Visit_1_T90_minutes_unspecific
2,NaN,True,Matthews,John,1.0,978221.0,Matthews,John D,1955-01-04,14.3,5.9,7.761111,4.449417,4.149667,0.299750
10,NaN,False,Correnti,Karen,1.0,5643580.0,Corsetti,Aaron,1957-09-14,41.6,32.8,6.767500,1.477417,1.477417,0.000000
14,NaN,True,Frishkopf,Lawrence S,1.0,836334.0,Frishkopf,Lawrence S,1930-06-26,30.7,12.2,6.866667,8.312917,8.312917,0.000000
18,NaN,True,Fitzgerald,Richard P,1.0,1996747.0,Fitzgerald,Richard P,1938-01-21,1.9,2.8,7.166667,0.565833,0.188667,0.377167
20,NaN,True,Lascuola,John,NaN,NaN,NaN,NaN,NaN,0.6,1.2,5.827222,3.400167,2.878000,0.522167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,NaN,True,WEBB,JEFFREY,NaN,NaN,NaN,NaN,NaN,0.0,0.1,7.524993,0.000000,0.000000,0.000000
911,NaN,False,Gardner,Ian D,1.0,574659.0,Gardiner,Ian H,1946-09-13,2.3,1.8,6.600000,0.000000,0.000000,0.000000
912,NaN,True,Wise,John,1.0,1493518.0,West,John,1961-07-20,2.6,4.3,6.908311,1.299674,1.299674,0.000000
920,NaN,False,Garcia,Milagros,1.0,3001358.0,Garcia,Milagros,1960-04-28,0.0,0.5,4.350000,0.000000,0.000000,0.000000
924,NaN,False,Horan,Thomas,1.0,5464338.0,Nolan,Thomas,1941-08-02,2.4,3.4,7.024990,0.000000,0.000000,0.000000

In [24]:
hypoxic_table.loc[hypoxic_table.LastName == 'Roderick'].iloc[:, 45 : 60]

,MatchedMRN,MatchedLastName,MatchedFirstName,MatchedDOB,Visit_1_HypoxiaBurden,Visit_1_AHI,Visit_1_Total_Sleep_Time,Visit_1_T90_minutes,Visit_1_T90_minutes_desat,Visit_1_T90_minutes_unspecific,Visit_2_HypoxiaBurden,Visit_2_AHI,Visit_2_Total_Sleep_Time,Visit_2_T90_minutes,Visit_2_T90_minutes_desat
284,4738703.0,Roderick,Donald W,1946-04-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
control_table.shape

(18633, 18)

In [17]:
sleeplab_avail_full = pd.DataFrame()

for i_visit in range(10):
    control_table.loc[index,f'Visit_{i_visit+1}_HypoxiaBurden'] = np.nan
    control_table.loc[index,f'Visit_{i_visit+1}_AHI'] = np.nan
    control_table.loc[index,f'Visit_{i_visit+1}_Total_Sleep_Time'] = np.nan
    control_table.loc[index,f'Visit_{i_visit+1}_T90_minutes'] = np.nan
    control_table.loc[index,f'Visit_{i_visit+1}_T90_minutes_desat'] = np.nan
    control_table.loc[index,f'Visit_{i_visit+1}_T90_minutes_unspecific'] = np.nan

for index, row in tqdm(control_table.iterrows()):

    try:
        new_patient = 0

        if row['MRN_Match'] == 1:
            sleeplab_avail = sleeplab_table[np.isin(sleeplab_table.MRN_int, row.MRN)].copy()
        else:
            continue

        num_of_visits = sleeplab_avail.shape[0]
        control_table.loc[index,'num_of_visits'] = num_of_visits

        i_visit = -1
        for index_sleeplab, row_sleeplab in sleeplab_avail.iterrows():

            i_visit += 1

    #         if not f'Visit_{i_visit+1}_HypoxiaBurden' in control_table.columns:
    #             do_nothing = 1
            if not pd.isna(control_table.loc[index,f'Visit_{i_visit+1}_HypoxiaBurden']):
                # this has already been computed in prior loop/computation, let's skip it.
                continue

            # if there is at least one visist which is new, do computation and add to table eventually:
            new_patient = 1
            control_table.loc[index,f'Visit_{i_visit+1}_Date'] = sleeplab_avail.iloc[i_visit].DateOfVisit		
            control_table.loc[index,f'Visit_{i_visit+1}_Type'] = sleeplab_avail.iloc[i_visit].TypeOfTest

            path = sleeplab_avail.iloc[i_visit].Path
            signalfile = sleeplab_avail.iloc[i_visit].Signalfile
            labelfile = sleeplab_avail.iloc[i_visit].Labelfile

            control_table.loc[index,f'Visit_{i_visit+1}_Path'] = path
            control_table.loc[index,f'Visit_{i_visit+1}_Signalfile'] = signalfile
            control_table.loc[index,f'Visit_{i_visit+1}_Labelfile'] = labelfile

            signalfilepath = signalfile # os.path.join(path, signalfile)
            labelfilepath = labelfile # os.path.join(path, labelfile)

            if not pd.isna(labelfile): #  == '[]':
    #             try:
                hypoxia_burden, ahi, total_sleep_time, T90burden, T90desaturation, T90nonspecific = compute_hypoxia_statistics(signalfilepath, labelfilepath)

    #             except Exception as e:
    #                 print(e)
    #                 print(signalfilepath)
    #                 print(labelfilepath)
    #                 continue

            else:
                [hypoxia_burden, ahi, total_sleep_time, T90burden, T90desaturation, T90nonspecific] = [np.nan]*6

            control_table.loc[index,f'Visit_{i_visit+1}_HypoxiaBurden'] = [hypoxia_burden]
            control_table.loc[index,f'Visit_{i_visit+1}_AHI'] = [ahi]
            control_table.loc[index,f'Visit_{i_visit+1}_Total_Sleep_Time'] = [total_sleep_time]
            control_table.loc[index,f'Visit_{i_visit+1}_T90_minutes'] = [T90burden]
            control_table.loc[index,f'Visit_{i_visit+1}_T90_minutes_desat'] = [T90desaturation]
            control_table.loc[index,f'Visit_{i_visit+1}_T90_minutes_unspecific'] = [T90nonspecific]

            # also fill up sleeplab_available table:
            sleeplab_avail.loc[index_sleeplab, 'Hypoxia_Burden'] = [hypoxia_burden]
            sleeplab_avail.loc[index_sleeplab, 'AHI'] = [ahi]
            sleeplab_avail.loc[index_sleeplab, 'Total_Sleep_Time'] = [np.round(total_sleep_time,1)]
            sleeplab_avail.loc[index_sleeplab, 'T90_minutes'] = [np.round(T90burden,1)]
            sleeplab_avail.loc[index_sleeplab, 'T90_minutes_desat'] = [np.round(T90desaturation,1)]
            sleeplab_avail.loc[index_sleeplab, 'T90_minutes_unspecific'] = [np.round(T90nonspecific,1)]

        if new_patient == 1:
            sleeplab_avail_full = pd.concat([sleeplab_avail_full, sleeplab_avail], axis=0)
            sleeplab_avail_full.to_csv('sleeplab_avail_full_tmp.csv', index=False)
            control_table.to_csv('control_table_results_tmp.csv', index=False)

    except Exception as e:
        print(e)
        continue

31it [07:15, 44.08s/it]

Timestamp('2000-01-01 02:29:38.939843795')

38it [09:40, 33.91s/it]

local variable 'samples_limit' referenced before assignment

52it [11:56, 32.75s/it]

#sleep stage <= 1: [1] in /media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Shea~ Janet_85fa0fa7-0989-4e44-a913-2386c7c7e6a7/Signal_Shea~ Janet_85fa0fa7-0989-4e44-a913-2386c7c7e6a7.mat

54it [12:35, 28.83s/it]

local variable 'samples_limit' referenced before assignment

78it [25:38, 37.04s/it]

Timestamp('2000-01-01 02:15:28.028515778')

110it [46:21, 76.05s/it]

Timestamp('2000-01-01 01:51:55.823046954')

111it [47:58, 82.37s/it]

Timestamp('2000-01-01 04:43:09.850781100')

120it [54:55, 53.16s/it]

Timestamp('2000-01-01 00:11:05.245703128')

136it [1:03:27, 37.84s/it]

index 9654270 is out of bounds for axis 0 with size 9654270

153it [1:09:39, 41.27s/it]

Timestamp('2000-01-01 01:04:21.976171956')

191it [1:21:40, 55.99s/it]

Timestamp('2000-01-01 06:35:30.534765412')

228it [1:34:23, 46.72s/it]

Timestamp('2000-01-01 01:17:12.303125075')

236it [1:38:45, 42.66s/it]

Timestamp('2000-01-01 02:16:57.630859460')

237it [1:40:35, 62.85s/it]

Timestamp('2000-01-01 04:38:03.257812773')

241it [1:43:09, 63.87s/it]

Timestamp('2000-01-01 00:18:30.241796865')

300it [2:09:51, 34.71s/it]

Timestamp('2000-01-01 03:14:27.387109537')

306it [2:11:55, 39.23s/it]

Timestamp('2000-01-01 04:42:19.933202844')

309it [2:13:26, 40.69s/it]

Timestamp('2000-01-01 04:40:33.824609038')

312it [2:18:15, 98.23s/it]

Timestamp('2000-01-01 02:34:31.110546799')

364it [2:40:02, 56.42s/it]

Timestamp('2000-01-01 06:25:55.353125292')

377it [2:44:06, 45.29s/it]

Timestamp('2000-01-01 04:08:37.701562707')

378it [2:46:10, 68.80s/it]

Timestamp('2000-01-01 03:35:23.165234481')

379it [2:47:47, 77.36s/it]

Timestamp('2000-01-01 00:17:19.275000019')

395it [2:53:01, 43.20s/it]

Timestamp('2000-01-01 00:42:58.169140646')

405it [2:56:40, 42.87s/it]

Timestamp('2000-01-01 02:57:14.042578234')

449it [3:20:38, 34.53s/it]

Timestamp('2000-01-01 03:45:06.639453321')

491it [3:31:46, 21.34s/it]

Timestamp('2000-01-01 06:33:04.369921682')

504it [3:33:48, 34.25s/it]

Timestamp('2000-01-01 06:11:16.522265226')

509it [3:36:23, 32.59s/it]

Timestamp('2000-01-01 00:56:33.206640691')

510it [3:37:57, 51.08s/it]

Timestamp('2000-01-01 02:01:26.569140592')

525it [3:42:02, 40.47s/it]

Timestamp('2000-01-01 03:27:09.560937289')

531it [3:44:44, 38.22s/it]

Timestamp('2000-01-01 04:22:36.040234300')

534it [3:46:22, 36.52s/it]

Timestamp('2000-01-01 01:10:37.353906306')

559it [3:58:08, 60.33s/it]

Timestamp('2000-01-01 01:47:42.719531330')

588it [4:13:24, 44.85s/it]

Timestamp('2000-01-01 03:06:24.927343886')

611it [4:20:58, 41.50s/it]

Timestamp('2000-01-01 04:54:06.626171648')

614it [4:26:20, 83.64s/it]

Timestamp('2000-01-01 02:51:00.473437355')

622it [4:34:10, 117.96s/it]

Timestamp('2000-01-01 00:30:12.001562477')

629it [4:36:27, 51.36s/it]

Timestamp('2000-01-01 02:22:53.708203163')

637it [4:37:44, 30.07s/it]

index 9208783 is out of bounds for axis 0 with size 9208783

653it [4:47:32, 33.91s/it]

Timestamp('2000-01-01 05:16:27.674609211')

668it [4:51:30, 13.45s/it]

Timestamp('2000-01-01 03:45:49.864843538')

669it [4:53:01, 36.80s/it]

Timestamp('2000-01-01 06:19:48.219921569')

686it [5:01:35, 48.15s/it]

Timestamp('2000-01-01 01:07:43.776953036')

739it [5:18:02, 51.91s/it]

Timestamp('2000-01-01 03:19:05.732031086')

764it [5:27:59, 32.49s/it]

Timestamp('2000-01-01 04:26:53.267578349')

767it [5:29:43, 33.17s/it]

Timestamp('2000-01-01 01:05:14.525000033')

783it [5:40:37, 56.23s/it]

Timestamp('2000-01-01 06:48:14.830859814')

800it [5:50:17, 49.79s/it]

Timestamp('2000-01-01 02:34:15.569140666')

801it [5:52:23, 72.50s/it]

Timestamp('2000-01-01 07:55:11.467187618')

830it [6:04:32, 78.26s/it]

Timestamp('2000-01-01 04:10:34.352734121')

877it [6:28:52, 36.28s/it]

Timestamp('2000-01-01 05:32:39.629297111')

900it [6:36:36, 19.61s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Notter_David E_080317_2206.000/Signal_Notter_David E_080317_2206.000.mat

958it [6:59:35, 48.34s/it]

Timestamp('2000-01-01 00:34:30.724218719')

961it [7:04:04, 74.48s/it]

Timestamp('2000-01-01 02:13:37.960546769')

999it [7:12:11, 51.31s/it]

Timestamp('2000-01-01 04:00:44.817968558')

1048it [7:30:18, 23.02s/it]

Timestamp('2000-01-01 02:02:28.406250063')

1053it [7:32:20, 23.45s/it]

Timestamp('2000-01-01 01:20:03.731640713')

1095it [7:44:27, 27.48s/it]

Timestamp('2000-01-01 02:02:30.299218847')

1101it [7:46:45, 37.36s/it]

Timestamp('2000-01-01 01:56:10.146875127')

1118it [7:52:30, 45.18s/it]

Timestamp('2000-01-01 05:45:53.128125094')

1130it [7:53:40, 24.84s/it]/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in double_scalars
1162it [8:02:12, 14.72s/it]

Timestamp('2000-01-01 06:24:22.178515955')

1167it [8:05:11, 23.50s/it]

Timestamp('2000-01-01 06:58:15.872656442')

1184it [8:10:25, 45.38s/it]

Timestamp('2000-01-01 01:11:09.721875059')

1227it [8:28:19, 69.76s/it]

Timestamp('2000-01-01 02:16:45.684375110')

1243it [8:38:24, 73.41s/it]

Timestamp('2000-01-01 02:34:15.569140666')

1262it [8:49:53, 18.07s/it]

local variable 'samples_limit' referenced before assignment

1272it [8:53:22, 45.12s/it]

Timestamp('2000-01-01 01:26:40.797656225')

1290it [8:57:49, 18.77s/it]

local variable 'samples_limit' referenced before assignment

1297it [9:03:03, 83.81s/it]

Timestamp('2000-01-01 04:39:41.007421795')

1316it [9:12:58, 47.83s/it]

Timestamp('2000-01-01 03:23:12.885546729')

1326it [9:16:49, 39.79s/it]

Timestamp('2000-01-01 00:59:12.270312469')

1350it [9:24:16, 67.54s/it]

Timestamp('2000-01-01 00:40:12.579296854')

1357it [9:26:46, 38.63s/it]

Timestamp('2000-01-01 02:13:47.298437569')

1361it [9:28:20, 34.10s/it]

Timestamp('2000-01-01 00:35:40.818359384')

1374it [9:33:15, 38.91s/it]

index 13843858 is out of bounds for axis 0 with size 13843858

1384it [9:36:12, 48.37s/it]

Timestamp('2000-01-01 03:22:17.695703302')

1416it [9:42:58, 18.89s/it]

#sleep stage <= 1: [4] in /media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Louis~ Marie_a03daac4-54f7-454a-a9df-0e6ee7de2460/Signal_Louis~ Marie_a03daac4-54f7-454a-a9df-0e6ee7de2460.mat

1442it [9:49:03, 18.09s/it]

index 9903797 is out of bounds for axis 0 with size 9903797

1496it [10:05:41, 39.72s/it]

Timestamp('2000-01-01 05:48:50.808984083')

1580it [10:22:16, 20.70s/it]

Timestamp('2000-01-01 02:56:02.618749949')

1581it [10:24:01, 45.97s/it]

Timestamp('2000-01-01 00:22:54.691796886')

1619it [10:25:37, 32.94s/it]

Timestamp('2000-01-01 01:37:53.440625048')

1685it [10:34:51, 52.83s/it]

Timestamp('2000-01-01 02:35:42.350390586')

1694it [10:38:57, 36.34s/it]

Timestamp('2000-01-01 02:07:27.000390536')

1697it [10:42:02, 60.63s/it]

Timestamp('2000-01-01 01:19:49.045703145')

1700it [10:43:32, 43.26s/it]

Timestamp('2000-01-01 03:44:15.736718975')

1724it [10:47:28, 12.03s/it]

Timestamp('2000-01-01 02:23:38.419140534')

1729it [10:49:22, 17.44s/it]

cannot convert float NaN to integer

1740it [10:56:16, 66.53s/it]

Timestamp('2000-01-01 08:34:43.925000461')

1755it [11:07:58, 61.86s/it]

Timestamp('2000-01-01 00:38:02.903906291')

1767it [11:14:24, 41.57s/it]

Timestamp('2000-01-01 02:56:14.651171924')

1783it [11:19:32, 40.67s/it]

Timestamp('2000-01-01 00:07:58.706250004')

1945it [12:16:10, 25.51s/it]

Timestamp('2000-01-01 00:53:04.839062470')

1984it [12:29:56, 42.81s/it]

Timestamp('2000-01-01 04:42:57.265234300')

2000it [12:32:35, 16.79s/it]

Timestamp('2000-01-01 02:11:09.884374919')

2008it [12:35:51, 53.50s/it]

Timestamp('2000-01-01 00:44:31.985937511')

2030it [12:45:49, 29.65s/it]

Timestamp('2000-01-01 03:41:22.174999714')

2067it [13:02:26, 26.30s/it]

Timestamp('2000-01-01 06:03:37.626172269')

2187it [13:41:50, 37.17s/it]

Timestamp('2000-01-01 03:01:33.926562596')

2218it [14:00:06, 85.08s/it]

Timestamp('2000-01-01 06:21:16.424609685')

2235it [14:11:43, 49.75s/it]

index 9391446 is out of bounds for axis 0 with size 9391446

2261it [14:25:52, 53.82s/it]

Timestamp('2000-01-01 06:19:05.436718857')

2276it [14:34:36, 56.39s/it]

Timestamp('2000-01-01 03:19:19.863671818')

2283it [14:38:44, 81.79s/it]

Timestamp('2000-01-01 04:40:44.324609614')

2307it [14:46:59, 37.36s/it]

Timestamp('2000-01-01 01:37:40.616015677')

2351it [14:56:42, 15.64s/it]

"Unable to open object (object 'stage' doesn't exist)"

2354it [14:58:30, 25.23s/it]

Timestamp('2000-01-01 03:17:23.747265446')

2395it [15:18:09, 40.75s/it]

Timestamp('2000-01-01 01:57:47.352734343')

2408it [15:22:50, 29.20s/it]

Timestamp('2000-01-01 02:22:57.758593856')

2467it [15:53:24, 43.52s/it]

Timestamp('2000-01-01 02:27:39.187499956')

2473it [15:54:36, 30.21s/it]

index 9301702 is out of bounds for axis 0 with size 9301702

2478it [15:56:04, 31.75s/it]

Timestamp('2000-01-01 01:44:15.943749934')

2507it [16:05:21, 58.53s/it]

Timestamp('2000-01-01 02:27:27.420703240')

2528it [16:08:05, 24.44s/it]

Timestamp('2000-01-01 03:22:17.695703302')

2536it [16:13:05, 50.77s/it]

Timestamp('2000-01-01 04:26:53.267578349')

2550it [16:19:33, 60.71s/it]

Timestamp('2000-01-01 00:51:38.022265595')

2552it [16:21:23, 59.03s/it]

Timestamp('2000-01-01 02:25:33.669921988')

2702it [17:02:44, 33.90s/it]

Timestamp('2000-01-01 02:22:59.999218673')

2748it [17:16:27, 25.82s/it]

Timestamp('2000-01-01 00:58:55.821484328')

2794it [17:32:48, 36.23s/it]

index 9615975 is out of bounds for axis 0 with size 9615975

2795it [17:34:29, 55.44s/it]

Timestamp('2000-01-01 00:56:00.863281266')

2894it [17:55:19, 42.19s/it]

Timestamp('2000-01-01 01:28:43.655078051')

2951it [18:11:08, 10.38s/it]

Timestamp('2000-01-01 06:16:50.461718640')

2956it [18:13:00, 13.95s/it]

Timestamp('2000-01-01 02:25:48.211718708')

3007it [18:35:19, 46.23s/it]

Timestamp('2000-01-01 02:00:59.805468818')

3019it [18:39:04, 24.72s/it]

index 9931467 is out of bounds for axis 0 with size 9931467

3034it [18:42:56, 40.85s/it]

Timestamp('2000-01-01 01:53:05.438281163')

3106it [19:01:09, 36.36s/it]

Timestamp('2000-01-01 02:27:02.011328201')

3107it [19:03:30, 67.75s/it]

Timestamp('2000-01-01 01:38:07.873828022')

3124it [19:09:30, 37.35s/it]

Timestamp('2000-01-01 03:07:53.146093594')

3142it [19:14:36, 27.63s/it]

Timestamp('2000-01-01 04:22:51.397265803')

3181it [19:26:54, 66.96s/it]

Timestamp('2000-01-01 06:51:00.804297272')

3194it [19:30:17, 24.97s/it]

Timestamp('2000-01-01 01:43:03.830859285')

3197it [19:32:18, 44.32s/it]

Timestamp('2000-01-01 04:10:34.352734121')

3210it [19:41:10, 143.09s/it]

Timestamp('2000-01-01 03:01:48.440624872')

3248it [19:59:26, 31.01s/it]

Unable to open file (truncated file: eof = 3931648, sblock->base_addr = 512, stored_eof = 16487021)

3338it [20:24:35, 13.76s/it]

Timestamp('2000-01-01 04:38:03.257812773')

3341it [20:26:53, 29.58s/it]

Timestamp('2000-01-01 05:49:52.398827927')

3414it [20:41:26, 32.31s/it]

Timestamp('2000-01-01 06:48:14.830859814')

3432it [20:49:27, 26.07s/it]

Timestamp('2000-01-01 01:36:36.675781320')

3445it [20:54:06, 26.99s/it]

Timestamp('2000-01-01 04:06:13.392578197')

3561it [21:09:11, 14.03s/it]

Timestamp('2000-01-01 00:40:41.045703165')

3641it [21:30:02, 22.22s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Dunn_Michael A _102317_2304.000/Signal_Dunn_Michael A _102317_2304.000.mat

3661it [21:35:08, 20.09s/it]

Timestamp('2000-01-01 02:26:52.132422002')

3680it [21:41:27, 38.96s/it]

Timestamp('2000-01-01 07:37:40.354687391')

3764it [22:05:51, 64.39s/it]

Timestamp('2000-01-01 03:08:32.459765812')

3781it [22:13:02, 39.75s/it]

Timestamp('2000-01-01 01:38:46.918359402')

3785it [22:14:17, 33.40s/it]

Timestamp('2000-01-01 02:17:06.421484215')

3803it [22:19:29, 22.64s/it]

Timestamp('2000-01-01 03:20:05.809765475')

3810it [22:22:21, 39.02s/it]

Timestamp('2000-01-01 00:52:24.111718718')

3817it [22:24:42, 50.59s/it]

Timestamp('2000-01-01 01:52:21.331250109')

3829it [22:28:09, 29.31s/it]

index 9014628 is out of bounds for axis 0 with size 9014628

3846it [22:34:31, 23.10s/it]

Unable to open file (file signature not found)

3879it [22:49:39, 21.23s/it]

index 5761600 is out of bounds for axis 0 with size 5761600

3933it [23:00:41,  7.34s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Frost_John_093009_2306.000/Signal_Frost_John_093009_2306.000.mat

3960it [23:16:08, 103.02s/it]

Timestamp('2000-01-01 06:29:46.983593441')

4000it [23:28:29, 17.31s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Bjorkman~ Zach_bd12e62d-5c9a-4167-9948-d83f457b15d3/Signal_Bjorkman~ Zach_bd12e62d-5c9a-4167-9948-d83f457b15d3.mat

4008it [23:33:31, 28.73s/it]

Timestamp('2000-01-01 03:50:10.244921990')

4054it [23:54:08, 46.82s/it]

Timestamp('2000-01-01 04:58:54.622656575')

4056it [23:56:07, 50.48s/it]

Timestamp('2000-01-01 00:38:27.352343729')

4092it [24:06:52, 42.12s/it]

Timestamp('2000-01-01 04:49:05.750390878')

4118it [24:19:43, 21.60s/it]

Timestamp('2000-01-01 00:42:50.636328085')

4149it [24:33:02, 48.25s/it]

Timestamp('2000-01-01 06:27:09.004296778')

4150it [24:34:33, 60.85s/it]

Timestamp('2000-01-01 06:08:31.418750281')

4181it [24:40:16, 17.30s/it]

Timestamp('2000-01-01 01:25:00.055078193')

4192it [24:42:34, 33.04s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Mancio_Marcos T_052017_2247.000/Signal_Mancio_Marcos T_052017_2247.000.mat

4307it [25:19:16, 57.76s/it]

Timestamp('2000-01-01 04:10:46.924609670')

4312it [25:25:38, 120.44s/it]

Timestamp('2000-01-01 00:07:19.075781258')

4340it [25:34:11, 40.83s/it]

Timestamp('2000-01-01 00:48:05.881640639')

4345it [25:36:05, 47.73s/it]

Timestamp('2000-01-01 01:15:32.441015548')

4350it [25:38:28, 38.05s/it]

Timestamp('2000-01-01 05:46:49.860156160')

4375it [25:50:25, 36.02s/it]

Timestamp('2000-01-01 05:00:21.361328414')

4390it [25:56:41, 42.69s/it]

Timestamp('2000-01-01 03:41:20.200000223')

4423it [26:11:35, 67.97s/it]

Timestamp('2000-01-01 02:10:19.221875038')

4449it [26:19:26, 21.01s/it]

Timestamp('2000-01-01 00:26:57.244140604')

4498it [26:31:49, 23.01s/it]

index 10074992 is out of bounds for axis 0 with size 10074992

4528it [26:37:04, 10.35s/it]

index 9391446 is out of bounds for axis 0 with size 9391446

4536it [26:40:00, 18.08s/it]

Timestamp('2000-01-01 06:20:49.273047161')

4610it [27:01:27, 41.89s/it]

Timestamp('2000-01-01 03:25:31.726171976')

4637it [27:10:12, 23.26s/it]

Timestamp('2000-01-01 01:57:52.835156350')

4644it [27:15:05, 43.60s/it]

Timestamp('2000-01-01 00:26:57.244140604')

4683it [27:33:22, 30.21s/it]

Timestamp('2000-01-01 03:15:35.973047060')

4703it [27:38:41, 29.21s/it]

Timestamp('2000-01-01 03:11:39.957421968')

4712it [27:44:21, 41.41s/it]

Timestamp('2000-01-01 00:39:39.585546885')

4773it [28:14:54, 101.89s/it]

Timestamp('2000-01-01 01:31:57.704687430')

4809it [28:29:32, 72.35s/it]

Timestamp('2000-01-01 03:01:35.625390814')

4815it [28:33:06, 53.25s/it]

Timestamp('2000-01-01 00:47:22.931249989')

4832it [28:46:28, 61.91s/it]

Timestamp('2000-01-01 01:25:40.754296828')

4844it [28:51:38, 41.45s/it]

Timestamp('2000-01-01 06:42:10.106640920')

4853it [28:57:07, 61.15s/it]

Timestamp('2000-01-01 02:00:20.108593824')

4861it [29:00:52, 32.70s/it]

index 9792990 is out of bounds for axis 0 with size 9792990

4881it [29:06:51, 47.62s/it]

Timestamp('2000-01-01 02:56:02.618749949')

4937it [29:30:37, 62.43s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Santiago_Luis_041917_2131.000/Signal_Santiago_Luis_041917_2131.000.mat

4945it [29:32:41, 41.94s/it]

Timestamp('2000-01-01 03:18:40.085156059')

4978it [29:44:51, 19.00s/it]

Timestamp('2000-01-01 00:45:22.713281224')

4982it [29:49:19, 48.45s/it]

Timestamp('2000-01-01 05:35:25.652734638')

5045it [30:12:21, 21.25s/it]

index 12738632 is out of bounds for axis 0 with size 12738632

5068it [30:17:14, 34.52s/it]

Timestamp('2000-01-01 00:52:56.819140662')

5136it [30:34:06, 10.43s/it]

Timestamp('2000-01-01 04:40:44.324609614')

5145it [30:36:14, 22.63s/it]

Timestamp('2000-01-01 04:24:08.682421627')

5155it [30:38:56, 25.12s/it]

Timestamp('2000-01-01 00:15:06.704687507')

5207it [31:00:50, 112.28s/it]

Timestamp('2000-01-01 01:30:20.357421789')

5214it [31:02:33, 82.99s/it]

Timestamp('2000-01-01 03:04:33.160937444')

5324it [31:28:55, 37.00s/it]

Timestamp('2000-01-01 02:58:17.075781303')

5351it [31:36:50, 33.41s/it]/home/wolfgang/anaconda3/envs/AirGoSleep/lib/python3.6/site-packages/ipykernel_launcher.py:34: RuntimeWarning: divide by zero encountered in double_scalars
5353it [31:40:25, 71.27s/it]

Timestamp('2000-01-01 05:17:37.690234108')

5431it [32:02:23, 14.44s/it]

Timestamp('2000-01-01 01:58:16.905859460')

5563it [32:40:12, 69.38s/it]

Timestamp('2000-01-01 00:49:38.224218795')

5656it [33:02:23, 45.89s/it]

Timestamp('2000-01-01 02:07:50.237890531')

5690it [33:16:02, 52.20s/it]

Timestamp('2000-01-01 04:17:46.834765819')

5730it [33:27:09, 65.34s/it]

Timestamp('2000-01-01 03:28:26.273828274')

5772it [33:37:24, 51.93s/it]

Timestamp('2000-01-01 00:57:30.580859405')

5775it [33:39:06, 46.54s/it]

Timestamp('2000-01-01 02:40:54.410937332')

5866it [33:55:48, 13.55s/it]

Timestamp('2000-01-01 01:27:32.154687549')

5876it [33:56:50, 10.31s/it]

index 5205000 is out of bounds for axis 0 with size 5205000

5885it [34:00:08, 24.17s/it]

Timestamp('2000-01-01 02:06:54.680859500')

5911it [34:05:55, 44.63s/it]

Timestamp('2000-01-01 05:45:49.840234657')

5938it [34:12:03, 32.44s/it]

Timestamp('2000-01-01 03:55:47.973828040')

5948it [34:16:33, 35.26s/it]

Timestamp('2000-01-01 03:13:16.147656011')

5958it [34:18:34, 30.23s/it]

Timestamp('2000-01-01 06:25:55.353125292')

5978it [34:24:23, 33.62s/it]

Timestamp('2000-01-01 01:19:49.045703145')

6018it [34:33:10, 37.93s/it]

Timestamp('2000-01-01 00:28:14.271875022')

6039it [34:43:11, 38.74s/it]

Timestamp('2000-01-01 01:46:38.007031139')

6040it [34:44:57, 58.95s/it]

Timestamp('2000-01-01 00:45:10.366406262')

6042it [34:46:41, 56.81s/it]

Timestamp('2000-01-01 06:13:20.628125174')

6062it [34:55:54, 79.63s/it]

Timestamp('2000-01-01 07:00:50.710546679')

6078it [35:04:46, 40.96s/it]

Timestamp('2000-01-01 05:52:25.333984095')

6093it [35:11:55, 47.13s/it]

Timestamp('2000-01-01 03:42:03.403906373')

6186it [35:33:47, 20.31s/it]

Timestamp('2000-01-01 04:32:14.739843533')

6195it [35:45:14, 69.16s/it]

Timestamp('2000-01-01 00:21:00.563671898')

6201it [35:46:50, 52.16s/it]

Timestamp('2000-01-01 05:58:08.383593563')

6202it [35:48:22, 64.19s/it]

Timestamp('2000-01-01 00:27:49.962500023')

6240it [35:57:26, 19.04s/it]

index 6390800 is out of bounds for axis 0 with size 6390800

6247it [36:03:01, 49.03s/it]

Timestamp('2000-01-01 02:53:56.012890408')

6262it [36:06:09, 44.18s/it]

Timestamp('2000-01-01 02:33:37.371484329')

6267it [36:07:05, 25.94s/it]

index 12315095 is out of bounds for axis 0 with size 12315095

6294it [36:12:00, 49.09s/it]

Timestamp('2000-01-01 02:02:10.206250099')

6300it [36:14:43, 51.48s/it]

Timestamp('2000-01-01 06:41:52.641796664')

6373it [36:36:43, 32.27s/it]

Timestamp('2000-01-01 02:24:21.378906123')

6442it [36:53:28, 29.07s/it]

Timestamp('2000-01-01 02:57:13.125390526')

6452it [36:58:16, 31.60s/it]

Timestamp('2000-01-01 00:13:38.981640637')

6457it [37:01:31, 36.67s/it]

Timestamp('2000-01-01 02:47:17.886328210')

6535it [37:27:38, 55.00s/it]

Timestamp('2000-01-01 01:27:25.713281177')

6540it [37:30:17, 49.34s/it]

Timestamp('2000-01-01 01:19:18.524609412')

6574it [37:38:13, 16.75s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Styles~ Evan_4a898e81-979a-4817-b748-87ab0b7e4a88/Signal_Styles~ Evan_4a898e81-979a-4817-b748-87ab0b7e4a88.mat

6590it [37:44:28, 39.45s/it]

Timestamp('2000-01-01 02:38:14.510546743')

6652it [38:04:54, 50.80s/it]

Timestamp('2000-01-01 02:05:55.541406341')

6660it [38:08:03, 37.86s/it]

Timestamp('2000-01-01 07:14:45.020703235')

6709it [38:26:46, 26.53s/it]

Timestamp('2000-01-01 00:47:22.931249989')

6786it [38:46:17, 21.98s/it]

Timestamp('2000-01-01 03:45:33.440234555')

6807it [38:51:12, 53.41s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/natus_data/Natola~ Anthon_ff592bd4-82e5-4ff7-9664-eec13b24099f/Signal_Natola~ Anthon_ff592bd4-82e5-4ff7-9664-eec13b24099f.mat

6845it [39:04:36, 30.19s/it]

Timestamp('2000-01-01 03:31:38.241797119')

6862it [39:10:25, 29.42s/it]

Timestamp('2000-01-01 05:16:27.674609211')

6925it [39:20:35, 21.69s/it]

index 12321364 is out of bounds for axis 0 with size 12321364

6937it [39:25:55, 44.37s/it]

Timestamp('2000-01-01 03:00:28.830859275')

6941it [39:28:34, 38.92s/it]

Timestamp('2000-01-01 00:40:39.821484405')

6946it [39:30:36, 46.96s/it]

Timestamp('2000-01-01 02:20:03.159765504')

7007it [39:56:17, 36.67s/it]

Timestamp('2000-01-01 01:48:12.979296982')

7025it [40:02:58, 38.72s/it]

local variable 'samples_limit' referenced before assignment

7044it [40:14:25, 33.90s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Resca_Anne Marie_092211_2312.000/Signal_Resca_Anne Marie_092211_2312.000.mat

7045it [40:15:56, 51.03s/it]

Timestamp('2000-01-01 03:27:42.260547038')

7057it [40:20:31, 52.46s/it]

Timestamp('2000-01-01 03:16:56.855078072')

7059it [40:23:35, 80.65s/it]

Timestamp('2000-01-01 01:38:46.918359402')

7119it [40:53:18, 47.24s/it]

Timestamp('2000-01-01 01:23:33.785937563')

7122it [40:55:28, 52.22s/it]

Timestamp('2000-01-01 00:17:19.275000019')

7137it [41:01:03, 70.18s/it]

local variable 'samples_limit' referenced before assignment

7188it [41:21:55, 42.08s/it]

Timestamp('2000-01-01 00:12:35.377343735')

7195it [41:27:47, 60.36s/it]

Timestamp('2000-01-01 05:09:40.723828279')

7197it [41:30:13, 68.34s/it]

Timestamp('2000-01-01 00:09:05.519921865')

7201it [41:31:35, 57.78s/it]

Timestamp('2000-01-01 03:42:03.403906373')

7227it [41:40:02, 30.91s/it]

Timestamp('2000-01-01 02:04:06.774218712')

7230it [41:41:27, 30.21s/it]

Timestamp('2000-01-01 03:08:32.459765812')

7242it [41:47:34, 42.62s/it]

Timestamp('2000-01-01 04:47:58.044140354')

7253it [41:52:58, 33.59s/it]

Timestamp('2000-01-01 00:57:38.672656308')

7259it [41:57:14, 48.19s/it]

Timestamp('2000-01-01 04:43:39.150781463')

7269it [42:05:55, 56.59s/it]

Timestamp('2000-01-01 01:56:03.737890593')

7290it [42:08:48, 13.04s/it]

Timestamp('2000-01-01 03:33:58.575390825')

7338it [42:31:43, 24.97s/it]

Timestamp('2000-01-01 03:03:56.571484465')

7364it [42:41:06, 25.55s/it]

index 10292688 is out of bounds for axis 0 with size 10292688

7402it [42:51:35, 18.20s/it]

Timestamp('2000-01-01 02:49:08.752343925')

7445it [43:00:51, 18.47s/it]

Timestamp('2000-01-01 00:54:56.645703188')

7469it [43:02:20,  6.94s/it]

index 5207000 is out of bounds for axis 0 with size 5207000

7478it [43:04:12, 16.27s/it]

Timestamp('2000-01-01 05:11:54.151171698')

7544it [43:22:37, 31.35s/it]

Timestamp('2000-01-01 06:42:47.719530913')

7627it [43:47:29, 33.65s/it]

Timestamp('2000-01-01 07:34:27.980859258')

7650it [43:51:02, 29.35s/it]

Timestamp('2000-01-01 02:11:09.884374919')

7666it [43:54:19, 22.14s/it]

Timestamp('2000-01-01 04:16:16.103125259')

7690it [44:04:30, 42.39s/it]

Timestamp('2000-01-01 04:08:21.654687790')

7706it [44:11:32, 19.14s/it]

Timestamp('2000-01-01 07:58:11.223047104')

7710it [44:12:56, 21.97s/it]

Timestamp('2000-01-01 03:48:53.348828369')

7729it [44:17:40, 25.75s/it]

Timestamp('2000-01-01 05:09:06.564843673')

7758it [44:27:08, 35.58s/it]

Timestamp('2000-01-01 01:13:59.834375058')

7775it [44:31:55, 40.23s/it]

Timestamp('2000-01-01 06:35:30.534765412')

7780it [44:34:06, 27.00s/it]

Timestamp('2000-01-01 04:18:37.375781455')

7785it [44:36:16, 24.19s/it]

Timestamp('2000-01-01 01:32:23.792187594')

7805it [44:43:33, 34.48s/it]

Timestamp('2000-01-01 04:59:47.132031496')

7839it [44:54:15, 37.91s/it]

Timestamp('2000-01-01 02:25:30.728906370')

7867it [44:58:04, 12.06s/it]

index 10633794 is out of bounds for axis 0 with size 10633794

7952it [45:11:29, 23.29s/it]

local variable 'samples_limit' referenced before assignment

7957it [45:13:50, 46.15s/it]

Timestamp('2000-01-01 04:39:55.487890853')

8018it [45:32:36, 40.82s/it]

Timestamp('2000-01-01 04:15:11.913281179')

8066it [45:39:41, 12.00s/it]

Timestamp('2000-01-01 01:45:44.592968838')

8078it [45:41:54, 14.72s/it]

Timestamp('2000-01-01 01:27:51.029687593')

8236it [46:05:42, 27.36s/it]

Timestamp('2000-01-01 03:17:12.759375124')

8240it [46:07:23, 43.45s/it]

Timestamp('2000-01-01 01:31:30.286328216')

8250it [46:11:43, 27.76s/it]

Timestamp('2000-01-01 02:25:42.171093669')

8257it [46:15:37, 40.80s/it]

Timestamp('2000-01-01 03:15:37.385546770')

8267it [46:18:06, 42.50s/it]

Timestamp('2000-01-01 06:27:06.576953318')

8273it [46:19:23, 28.49s/it]

Timestamp('2000-01-01 06:16:22.659375103')

8299it [46:26:41, 25.40s/it]

Timestamp('2000-01-01 01:25:40.754296828')

8301it [46:27:56, 28.97s/it]

Timestamp('2000-01-01 01:48:41.471093812')

8308it [46:29:27, 24.17s/it]

Timestamp('2000-01-01 05:09:06.564843673')

8352it [46:37:04, 10.58s/it]

Unable to open file (file signature not found)

8380it [46:56:42, 107.03s/it]

Timestamp('2000-01-01 05:15:53.428124750')

8382it [46:58:24, 90.21s/it]

Timestamp('2000-01-01 00:39:39.585546885')

8429it [47:11:26, 31.04s/it]

Timestamp('2000-01-01 02:36:27.975390712')

8439it [47:13:33, 16.56s/it]

Timestamp('2000-01-01 05:16:39.993750158')

8462it [47:17:02, 32.42s/it]

Timestamp('2000-01-01 01:47:48.512500054')

8508it [47:31:45, 42.79s/it]

Timestamp('2000-01-01 00:19:51.062109398')

8575it [47:50:55, 19.06s/it]

Timestamp('2000-01-01 02:23:09.111718894')

8591it [47:58:35, 54.65s/it]

Timestamp('2000-01-01 00:20:22.496484363')

8636it [48:04:49, 19.93s/it]

Timestamp('2000-01-01 02:28:38.752734414')

8708it [48:29:16, 63.94s/it]

Timestamp('2000-01-01 03:27:42.260547038')

8723it [48:37:40, 64.02s/it]

Timestamp('2000-01-01 01:17:22.768750061')

8738it [48:43:07, 28.81s/it]

Timestamp('2000-01-01 01:18:13.740625080')

8744it [48:45:29, 48.83s/it]

Timestamp('2000-01-01 02:11:12.359765739')

8766it [48:57:39, 65.69s/it]

Timestamp('2000-01-01 04:34:47.990625144')

8768it [48:59:10, 59.72s/it]

Timestamp('2000-01-01 02:14:07.080468710')

8783it [49:02:14, 26.18s/it]

Timestamp('2000-01-01 00:27:49.962500023')

8807it [49:14:41, 63.95s/it]

Timestamp('2000-01-01 02:36:27.975390712')

8871it [49:30:00, 34.00s/it]

Timestamp('2000-01-01 01:32:43.262499892')

8890it [49:37:50, 36.55s/it]

Timestamp('2000-01-01 02:57:31.923828317')

8913it [49:47:08, 40.25s/it]

Timestamp('2000-01-01 03:04:33.160937444')

8949it [50:01:34, 46.43s/it]

Timestamp('2000-01-01 02:27:39.187499956')

8956it [50:03:47, 23.64s/it]

index 9903104 is out of bounds for axis 0 with size 9903104

8971it [50:11:06, 41.18s/it]

Timestamp('2000-01-01 02:34:31.110546799')

8983it [50:16:06, 43.96s/it]

Timestamp('2000-01-01 04:26:10.510156556')

8999it [50:19:20, 33.52s/it]

Timestamp('2000-01-01 02:58:17.075781303')

9009it [50:24:43, 45.06s/it]

Timestamp('2000-01-01 04:24:08.682421627')

9054it [50:37:23, 22.97s/it]

Timestamp('2000-01-01 00:45:45.370312463')

9073it [50:43:54, 33.72s/it]

Timestamp('2000-01-01 00:57:07.304687471')

9087it [50:58:15, 98.74s/it]

Timestamp('2000-01-01 00:20:22.496484363')

9120it [51:15:23, 45.23s/it]

Timestamp('2000-01-01 02:33:33.993750073')

9125it [51:20:23, 58.05s/it]

Timestamp('2000-01-01 02:13:37.960546769')

9167it [51:31:38, 23.29s/it]

Timestamp('2000-01-01 02:16:45.684375110')

9221it [51:49:22, 73.78s/it]

index 10000206 is out of bounds for axis 0 with size 10000206

9268it [52:05:24, 33.05s/it]

Timestamp('2000-01-01 02:05:22.949609268')

9278it [52:08:51, 29.02s/it]

Timestamp('2000-01-01 02:59:09.652734230')

9290it [52:12:13, 41.51s/it]

Timestamp('2000-01-01 01:59:27.965234461')

9300it [52:15:34, 27.96s/it]

Timestamp('2000-01-01 02:28:50.335937629')

9316it [52:24:26, 31.71s/it]

index 9990214 is out of bounds for axis 0 with size 9990214

9389it [52:46:38, 55.09s/it]

Timestamp('2000-01-01 04:42:42.167187421')

9392it [52:47:50, 48.58s/it]

Timestamp('2000-01-01 00:24:59.825390602')

9400it [52:50:18, 19.19s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Marlow_Alan_052116_2134.000/Signal_Marlow_Alan_052116_2134.000.mat

9423it [52:59:32, 38.73s/it]

Timestamp('2000-01-01 03:33:22.780859160')

9437it [53:05:06, 29.02s/it]

Timestamp('2000-01-01 03:09:46.089062667')

9438it [53:06:29, 45.26s/it]

Timestamp('2000-01-01 05:18:58.468750365')

9470it [53:22:59, 80.11s/it]

Timestamp('2000-01-01 05:45:49.840234657')

9472it [53:23:44, 48.74s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Bern_Sandra_110417_2133.000/Signal_Bern_Sandra_110417_2133.000.mat

9502it [53:35:05, 56.68s/it]

Timestamp('2000-01-01 06:45:33.050390407')

9510it [53:40:17, 47.77s/it]

Timestamp('2000-01-01 01:04:09.571875045')

9516it [53:43:52, 55.30s/it]

Timestamp('2000-01-01 02:01:52.893750033')

9549it [54:02:38, 28.88s/it]

Timestamp('2000-01-01 02:08:42.921093638')

9555it [54:03:10, 16.37s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Thompson_Justin_042717_2238.000/Signal_Thompson_Justin_042717_2238.000.mat

9561it [54:06:13, 39.29s/it]

Timestamp('2000-01-01 07:11:21.264452904')

9620it [54:32:39, 48.95s/it]

Timestamp('2000-01-01 01:02:21.606640586')

9641it [54:42:06, 63.47s/it]

Timestamp('2000-01-01 01:40:33.010546847')

9655it [54:48:18, 50.57s/it]

Timestamp('2000-01-01 01:37:45.601171957')

9669it [54:54:45, 58.40s/it]

Timestamp('2000-01-01 00:48:29.372656285')

9670it [54:56:25, 70.69s/it]

Timestamp('2000-01-01 06:47:35.750781144')

9675it [54:59:31, 53.73s/it]

Timestamp('2000-01-01 02:51:17.098046741')

9711it [55:12:26, 19.08s/it]

Timestamp('2000-01-01 05:46:01.988671776')

9713it [55:14:23, 41.74s/it]

Timestamp('2000-01-01 06:28:17.134375333')

9747it [55:23:59, 36.43s/it]

Timestamp('2000-01-01 01:37:45.601171957')

9797it [55:36:08, 46.68s/it]

Timestamp('2000-01-01 01:12:41.462109317')

9811it [55:37:16, 23.12s/it]

no sleep stages available in /media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Mazzola_Salvatore_062209_2218.000/Signal_Mazzola_Salvatore_062209_2218.000.mat

9835it [55:43:55, 47.82s/it]

Timestamp('2000-01-01 03:01:14.946875051')

9871it [55:51:26, 18.40s/it]

index 4790600 is out of bounds for axis 0 with size 4790600

9879it [55:53:51, 49.29s/it]

Timestamp('2000-01-01 02:34:53.404687363')

9897it [56:04:05, 97.23s/it]

Timestamp('2000-01-01 00:33:04.383203167')

9939it [56:26:54, 68.30s/it]

local variable 'samples_limit' referenced before assignment

KeyboardInterrupt:

In [ ]:
control_table.to_csv('hypoxia_control_table.csv')
sleeplab_avail_full.to_csv('sleeplab_table_with_hypoxia.csv')

In [ ]:
control_table.loc[pd.notna(control_table['Visit_1_HypoxiaBurden'])].iloc[:, :25]

In [ ]:
sleeplab_avail_full.columns

In [ ]:
sleeplab_avail_share = sleeplab_avail_full.drop(['Signalfile', 'System','Labelfile','FolderName','FolderPath','PatientID', 'Path'], axis=1)

In [ ]:
sleeplab_avail_share = sleeplab_avail_share[['FirstName','LastName','DateOfBirth', 'Sex', 'MRN', 'MRN_int', 'DateOfVisit','TypeOfTest', 'Total_Sleep_Time', 'AHI', 'Hypoxia_Burden']]

In [ ]:
sleeplab_avail_share.to_csv('psg_studies_ahi_hypoxia_burden.csv', index=False)

In [ ]:
hypoxic_table.to_csv('hypoxic_table_with_psg_data.csv', index=False)

In [27]:
sleeplab_avail_full.shape

(712, 18)

In [43]:
hypoxic_table.columns[:10]

Index(['File', 'Line', 'ID', 'Name', 'Multiple values', 'EMPI', 'EPIC_PMRN',
       'MRN_Type', 'MRN', 'Report_Number'],
      dtype='object')

In [93]:
selection = (hypoxic_table['MRN_Match']==0) & (hypoxic_table['NameMatch']==1)
sel_table = hypoxic_table.loc[selection, ['Name', 'MRN_Type', 'MRN', 'NameMatch','MatchedMRN', 'MatchedLastName', 'MatchedFirstName']].copy()
sel_table.reset_index(inplace=True)
sel_table.drop(['index'],axis=1, inplace=True)
sel_table

,Name,MRN_Type,MRN,NameMatch,MatchedMRN,MatchedLastName,MatchedFirstName
0,"Waite, Suzanne",BWH,14048110,1.0,1824261.0,Waite,Suzanne
1,"Giroux, Margarete",BWH,24416349,1.0,4373783.0,Giroux,Margarete
2,"Swain, Richard",BWH,31848708,1.0,5905412.0,Swain,Richard
3,"Carey, William",MGH,1599843,1.0,2274159.0,Carey,William H
4,"Walsh, David P",BWH,11924768,1.0,3167268.0,Walsh,David L
5,"Deberardinis, Mario",MGH,2468714,1.0,1628027.0,Deberardinis,Marion
6,"Washington, Susan",BWH,2134559,1.0,2196761.0,Washington,Susan
7,"Noiles, Nina",BWH,5697594,1.0,5308280.0,Noiles,Nina
8,"Stapleton, Tammy A",BWH,31549488,1.0,5655499.0,Stapleton,Tammy
9,"Doiron, Mary",BWH,14044580,1.0,5158589.0,Doiron,Mary V
10,"Hastie, John J",BWH,25043910,1.0,1112423.0,Hastie,John J
11,"Sousa, Steven",BWH,11589173,1.0,4596654.0,Sousa,Steven
12,"Snyder, Carol A",BWH,8174138,1.0,3611601.0,Snyder,Carol A
13,"Lerra, Lois",BWH,2756591,1.0,2812606.0,Lerra,Lois M
14,"Maloney, Robert",MGH,1871070,1.0,3042124.0,Maloney,Robert
15,"Harris, George",MGH,2321725,1.0,5025400.0,Harris,George B
16,"Sullivan, James L",MGH,2003262,1.0,3133873.0,Sullivan,James L
17,"Day, Larry",MGH,3467306,1.0,1809192.0,Day,Mary
18,"Doyle, Edward",BWH,10650307,1.0,5640211.0,Doyle,Edward
19,"Garcia, Milagros",BWH,8648453,1.0,3001358.0,Garcia,Milagros
20,"Boisvert, Shelby E",BWH,29605409,1.0,6362666.0,Boisvert,Shelby E
21,"Dowling, Carol",BWH,4566709,1.0,2313730.0,Dowling,Carol
22,"Garcia, Milagros",BWH,8648453,1.0,3001358.0,Garcia,Milagros
23,"Osborne, Michelle",BWH,28047231,1.0,5286965.0,Osborne,Michelle

In [94]:
sel_table.to_csv('matched_based_on_name.csv')

In [54]:
hypoxic_table.drop(['NewMRN'], axis=1, inplace=True)

In [66]:
hypoxic_table[['Name','Visit_1_Date','Visit_1_HypoxiaBurden', 'Visit_1_AHI', 'Visit_1_Total_Sleep_Time']].dropna(subset=['Visit_1_Date'])

,Name,Visit_1_Date,Visit_1_HypoxiaBurden,Visit_1_AHI,Visit_1_Total_Sleep_Time
2,"Matthews, John",08/14/2009,13.7,6.1,7.761111
14,"Frishkopf, Lawrence S",08/11/2017,30.7,12.2,6.866667
18,"Fitzgerald, Richard P",10/18/2017,2.5,2.8,7.166667
20,"Lascuola, John",04/19/2014,0.6,1.2,5.827222
24,"Bernardi, Richard J",05/06/2016,112.5,37.2,5.356389
...,...,...,...,...,...
912,"Wise, John",12/04/2011,26.6,19.3,5.713333
913,"Boucher, Jessica",10/20/2010,0.0,0.0,3.652778
918,"Dowling, Carol",12/19/2014,6.4,7.3,6.441667
920,"Garcia, Milagros",01/05/2010,0.0,0.5,4.350000
929,"Osborne, Michelle",09/26/2016,NaN,NaN,NaN

In [61]:
hypoxic_table.columns

Index(['File', 'Line', 'ID', 'Name', 'Multiple values', 'EMPI', 'EPIC_PMRN',
       'MRN_Type', 'MRN', 'Report_Number',
       ...
       'Visit_10_AHI', 'Visit_10_Total_Sleep_Time', 'Visit_11_Date',
       'Visit_11_Type', 'Visit_11_Path', 'Visit_11_Signalfile',
       'Visit_11_Labelfile', 'Visit_11_HypoxiaBurden', 'Visit_11_AHI',
       'Visit_11_Total_Sleep_Time'],
      dtype='object', length=143)

In [28]:
sleeplab_avail_full.to_csv('sleeplab_avail_full.csv', index=False)
# sleeplab_avail_full

In [29]:
hypoxic_table.to_csv('hypoxic_table_results.csv', index=False)

In [ ]:
sleeplab_avail[['LastName', 'FirstName', 'DateOfBirth', 'TypeOfTest']]

In [32]:
sleeplab_avail = sleeplab_table[np.isin(sleeplab_table.MRN_int, hypoxic_table_MGH.MRN)]

In [33]:
hypoxic_avail[['Name','MRN','Report_Date_Time']]

                      Name      MRN     Report_Date_Time
2           Matthews, John   978221  2010-03-29 01:32:00
14   Frishkopf, Lawrence S   836334  2018-08-17 18:13:00
18   Fitzgerald, Richard P  1996747  2018-06-13 17:25:00
20          Lascuola, John  1558684  2009-04-07 11:35:00
24     Bernardi, Richard J  2485662  2016-04-11 14:00:00
..                     ...      ...                  ...
904          Graf, Cynthia  5799198  2017-01-18 13:39:00
907          WEBB, JEFFREY  3690069  2014-02-27 08:47:00
909        Hazimeh, Khalid  3283155  2020-01-30 09:24:00
912             Wise, John  1262196  2019-03-05 20:02:00
913      Boucher, Jessica   4251881  2005-10-26 10:12:00

[408 rows x 3 columns]

In [34]:
sleeplab_avail[sleeplab_avail.MRN_int==978221]

,FolderName,PatientID,MRN,LastName,FirstName,Sex,DateOfBirth,DateOfVisit,TypeOfTest,Signalfile,Labelfile,System,Path,FolderPath,MRN_int
14178,Matthews_John_081409_2202.000,Z6587649,097-82-21,Matthews,John D,Male,1/4/1955,08/14/2009,PSG all night CPAP,Signal_Matthews_John_081409_2202.000.mat,Labels_Matthews_John_081409_2202.000.mat,Grass,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,NaN,978221
16207,Matthews_John_081812_2255.000,Z6587649,097-82-21,Matthews,John D,Male,1/4/1955,08/18/2012,PSG all night CPAP,Signal_TwinData6_686.mat,Labels_TwinData6_686.mat,Grass,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,NaN,978221
17693,Matthews_John_072409_2308.000,Z6587649,097-82-21,Matthews,John D,Male,1/4/1955,07/24/2009,PSG Split night,Signal_Matthews_John_072409_2308.000.mat,Labels_Matthews_John_072409_2308.000.mat,Grass,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,NaN,978221

In [38]:
sleeplab_avail

,FolderName,PatientID,MRN,LastName,FirstName,Sex,DateOfBirth,DateOfVisit,TypeOfTest,Signalfile,Labelfile,System,Path,FolderPath,MRN_int
15,Deberardinis_Marion_072817_2242.000,Z6377495,162-80-27,Deberardinis,Marion,Female,12/27/1950,07/28/2017,PSG Diagnostic,Signal_Deberardinis_Marion_072817_2242.000.mat,Labels_Deberardinis_Marion_072817_2242.000.mat,Grass,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,NaN,1628027
74,Ansaldi_Laurie_121412_2300.000,Z11636199,225-96-68,Ansaldi,Laurie,Female,5/30/1961,12/14/2012,PSG all night CPAP,Signal_TwinData6_Exported_30.mat,Labels_TwinData6_30.mat,Grass,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,NaN,2259668
149,Amazu_Adeline_050714_2348.000,Z12907166,345-73-99,Amazu,Adeline,Female,9/4/1949,05/07/2014,PSG all night CPAP,Signal_TwinData10_Exported_14.mat,Labels_TwinData10_14.mat,Grass,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,NaN,3457399
179,El-Sherbini_Ahmad_060209_2306.000,Z6365231,250-52-26,Elsherbini,Ahmed A,Male,9/1/1940,06/02/2009,PSG Diagnostic,Signal_El-Sherbini_Ahmad_060209_2306.000.mat,Labels_El-Sherbini_Ahmad_060209_2306.000.mat,Grass,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,NaN,2505226
215,Mullen_Robert_110211_2156.000,Z8714448,265-72-98,Mullen,Robert K,Male,5/25/1931,11/02/2011,PSG all night CPAP,Signal_Mullen_Robert_110211_2156.000.mat,Labels_Mullen_Robert_110211_2156.000.mat,Grass,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,NaN,2657298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24164,Vogel~ Michael_da9c24b2-7cde-4d3d-b60d-d68cde0...,Z8106184,100-09-32,Vogel,Michael H,Male,1951-02-01,2019-04-16,Split Night,[],[],Natus,/media/mad3/Datasets_ConvertedData/sleeplab/na...,NaN,1000932
24223,Marrero~ Hecto_3d1420ec-7c87-41dc-8026-d5968c8...,Z12068005,348-06-30,Marrero,Hector M,Male,1968-08-17,2018-08-20,Diagnostic,Signal_Marrero~ Hecto_3d1420ec-7c87-41dc-8026-...,Labels_Marrero~ Hecto_3d1420ec-7c87-41dc-8026-...,Natus,/media/mad3/Datasets_ConvertedData/sleeplab/na...,NaN,3480630
24334,Palermo~ Julie_af85aaa1-7868-43b5-909a-954794f...,Z9014512,265-73-18,Palermo,Julie A,Female,1957-08-02,2018-08-26,Diagnostic,Signal_Palermo~ Julie_af85aaa1-7868-43b5-909a-...,Labels_Palermo~ Julie_af85aaa1-7868-43b5-909a-...,Natus,/media/mad3/Datasets_ConvertedData/sleeplab/na...,NaN,2657318
24338,Leon~ Victor_0b69fab1-6753-4b08-89dc-7e042cd3446c,Z9144001,280-83-92,Leon,Victor J.,Male,1949-08-27,2018-12-11,Split Night,Signal_Leon~ Victor_0b69fab1-6753-4b08-89dc-7e...,Labels_Leon~ Victor_0b69fab1-6753-4b08-89dc-7e...,Natus,/media/mad3/Datasets_ConvertedData/sleeplab/na...,NaN,2808392
24425,Gibson~ Linda_1310c1c2-710b-4003-ba0b-ce82b2c5...,Z13990532,562-68-57,Gibson,Linda,Female,1954-02-27,2018-09-03,Titration CPAP,Signal_Gibson~ Linda_1310c1c2-710b-4003-ba0b-c...,Labels_Gibson~ Linda_1310c1c2-710b-4003-ba0b-c...,Natus,/media/mad3/Datasets_ConvertedData/sleeplab/na...,NaN,5626857

In [308]:
study = sleeplab_avail.iloc[2]
study

FolderName                         Amazu_Adeline_050714_2348.000
PatientID                                              Z12907166
MRN                                                    345-73-99
LastName                                                   Amazu
FirstName                                                Adeline
Sex                                                       Female
DateOfBirth                                             9/4/1949
DateOfVisit                                           05/07/2014
TypeOfTest                                    PSG all night CPAP
Signalfile                     Signal_TwinData10_Exported_14.mat
Labelfile                               Labels_TwinData10_14.mat
System                                                     Grass
Path           /media/mad3/Datasets_ConvertedData/sleeplab/gr...
FolderPath                                                   NaN
MRN_int                                                  3457399
Name: 149, dtype: object

In [309]:
signalfilepath = os.path.join(study.Path, study.Signalfile)
labelfilepath = os.path.join(study.Path, study.Labelfile)

In [310]:
signalfilepath

'/media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Amazu_Adeline_050714_2348.000/Signal_TwinData10_Exported_14.mat'

In [326]:
x = np.arange(-50,50+1/fs,1/fs)
plt.figure()
plt.plot(x,mean_spo2)
plt.scatter(x[search_window0],mean_spo2[search_window0],c='r',zorder=5)
plt.scatter(x[search_window1],mean_spo2[search_window1],c='r', zorder=5)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [348]:
plt.figure()
plt.plot(np.arange(len(spo2_drop))/fs,spo2_drop)
plt.title(area_tmp)
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [357]:
# def hypoxia_plot():

plt.rcParams.update({'font.size': 8})
seconds_roi = 10
flow_seconds_drop = 15
fontdict = {'fontsize':8}

fig = plt.figure()

ax1 = fig.add_subplot(411)
# plt.plot(data.Stage,'r')
ax1.plot(data.Apnea)
ax1.set_yticks(np.arange(7))
ax1.set_yticklabels(['No Event', 'OA','CA','MA','HY','','RERA'])
ax1.set_ylabel('Apnea Label', fontdict=fontdict)

if 'PTAF' in data.columns:
    ax2 = fig.add_subplot(412, sharex=ax1)
    ax2.plot(data.PTAF)
    ax2.scatter(data.index[data['Apnea_End']], data.PTAF[data['Apnea_End']], color='r',s=10, zorder=5)
    
    # ax2.scatter(cpap_on_dt, data.PTAF.loc[cpap_on_dt], c='r', zorder=10)
    ax2.set_ylabel('PTAF', fontdict=fontdict)

if 'CFLOW' in data.columns:
    ax3 = fig.add_subplot(413, sharex=ax1)
    ax3.plot(data.CFLOW)
    ax3.scatter(data.index[data['Apnea_End']], data.CFLOW[data['Apnea_End']], color='r',s=10, zorder=5)
    ax3.set_ylabel('CFlow', fontdict=fontdict)

ax4 = fig.add_subplot(414, sharex=ax1)
ax4.plot(data.SPO2)
ax4.scatter(data.index[data['Apnea_End']], data.SPO2[data['Apnea_End']], color='r',s=10, zorder=5)
ax4.scatter(idx_prior, data.SPO2[idx_prior], color='g',s=10, zorder=5)
ax4.scatter(idx_post, data.SPO2[idx_post], color='cyan',s=12, zorder=5)
ax4.scatter(data.index[data['Apnea_End']], spo2_refs, color='purple', s=10, zorder=5)
            
            
ax4.set_ylabel('SpO2', fontdict=fontdict)
ax4.set_ylim([data.SPO2.quantile(0.01), data.SPO2.max()+0.5])
ax4.set_xlabel('time (s)')

# ax.set_xlim([pd.Timestamp('2019-01-25 00:17:00.00'), pd.Timestamp('2019-01-25 00:21:00.00')])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0.5, 0, 'time (s)')

In [297]:
data.SPO2[np.round(idx_post,1)]

4753.3     94.555581
5186.6     93.565270
11894.8    89.604028
11966.4    87.624933
19985.1    87.624933
20055.5    88.613718
Name: SPO2, dtype: float64

In [300]:
for i in range(25):
    plt.close()

In [299]:
idx_post

Float64Index([4753.3, 5186.6, 11894.8, 11966.4, 19985.1, 20055.5], dtype='float64')

In [13]:
signalfilepath = '/media/mad3/Datasets_ConvertedData/sleeplab/grass_data/Anatasia_Lori_091611_2209.000/Signal_TwinData5_Exported_34.mat'