In [1]:
# sofar i've run the sleep_lab table and hypoxia operations in three parts but had a bug in in, only selecting :8000 for hypoxia calculation. 
# therefore:
# read in 3 sleeplab_tables, concat.
# read in 3 hypoxia tables, concat. (less rows because of bug)
# add hypoxia values to sleeplab tables.
# for all files where hypoxia value is missing, run hypoxia computation.

In [2]:
%matplotlib widget
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
import sys
import datetime
from tqdm import tqdm

%load_ext autoreload
%autoreload 2

sys.path.append('/home/wolfgang/repos/sleep_general')
from mgh_sleeplab import load_mgh_signal, annotations_preprocess, vectorize_respiratory_events, vectorize_sleep_stages

In [3]:
st0 = pd.read_csv('sleeplab_table_0.csv')
st1 = pd.read_csv('sleeplab_table_1.csv')
st2 = pd.read_csv('sleeplab_table_2.csv')

assert st0.shape[1] == st1.shape[1]
assert st0.shape[1] == st2.shape[1]

st = pd.concat([st0, st1, st2], axis=0)
st.drop(['Unnamed: 0'], axis=1, inplace=True)
st.reset_index(drop=True, inplace=True)

In [4]:
print(st.shape)
st.head(3)

(25231, 12)

,FolderName,PatientID,MRN,LastName,FirstName,Sex,DateOfBirth,DateOfVisit,TypeOfTest,Path,path_signal,path_annotations
0,Anatasia_Lori_091611_2209.000,Z11530888,424-66-43,Anastasia,Lori E,Female,1972-08-11,2011-09-16,PSG Diagnostic,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...
1,Gronewold_Catherine W_041615_2224.000,Z8592929,237-74-50,Gronewold,Catherine,Female,1948-12-13,2015-04-16,PSG Split night,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...
2,Morris_Martha_112512_2118.000,Z9992290,512-71-58,Morris,Martha,Female,1947-04-30,2012-11-25,PSG all night CPAP,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...

In [5]:
ht0 = pd.read_csv('sleeplab_table_hypoxia_0.csv')
ht1 = pd.read_csv('sleeplab_table_hypoxia_1.csv')
ht2 = pd.read_csv('sleeplab_table_hypoxia_2.csv')

assert ht0.shape[1] == ht1.shape[1]
assert ht0.shape[1] == ht2.shape[1]

ht = pd.concat([ht0, ht1, ht2], axis=0)
ht.drop(['Unnamed: 0'], axis=1, inplace=True)
ht.reset_index(drop=True, inplace=True)

In [6]:
print(ht.shape)
ht.head(3)

(23831, 18)

,FolderName,PatientID,MRN,LastName,FirstName,Sex,DateOfBirth,DateOfVisit,TypeOfTest,Path,path_signal,path_annotations,Total_Sleep_Time,AHI,HypoxiaBurden,T90_minutes,T90_minutes_desat,T90_minutes_unspecific
0,Anatasia_Lori_091611_2209.000,Z11530888,424-66-43,Anastasia,Lori E,Female,1972-08-11,2011-09-16,PSG Diagnostic,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,6.641667,0.3,0.7,0.000000,0.000000,0.000000
1,Gronewold_Catherine W_041615_2224.000,Z8592929,237-74-50,Gronewold,Catherine,Female,1948-12-13,2015-04-16,PSG Split night,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,5.816667,26.1,33.7,16.903167,13.744833,3.158333
2,Morris_Martha_112512_2118.000,Z9992290,512-71-58,Morris,Martha,Female,1947-04-30,2012-11-25,PSG all night CPAP,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,0.883333,0.0,0.0,5.814500,4.109917,1.704583

In [7]:
hypoxia_columns = list(ht.columns[-6:])
print(hypoxia_columns)

['Total_Sleep_Time', 'AHI', 'HypoxiaBurden', 'T90_minutes', 'T90_minutes_desat', 'T90_minutes_unspecific']

In [8]:
st.set_index('FolderName', inplace=True)
ht.set_index('FolderName', inplace=True)
sleeplab_table = st.join(ht[hypoxia_columns])

# example check
# st.loc["Penta_Christina_091109_2149.000"]
# ht.loc["Penta_Christina_091109_2149.000"]
# table.loc["Penta_Christina_091109_2149.000"]

In [9]:
sleeplab_table.head(5)

,PatientID,MRN,LastName,FirstName,Sex,DateOfBirth,DateOfVisit,TypeOfTest,Path,path_signal,path_annotations,Total_Sleep_Time,AHI,HypoxiaBurden,T90_minutes,T90_minutes_desat,T90_minutes_unspecific
FolderName,,,,,,,,,,,,,,,,,
Anatasia_Lori_091611_2209.000,Z11530888,424-66-43,Anastasia,Lori E,Female,1972-08-11,2011-09-16,PSG Diagnostic,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,6.641667,0.3,0.7,0.000000,0.000000,0.000000
Gronewold_Catherine W_041615_2224.000,Z8592929,237-74-50,Gronewold,Catherine,Female,1948-12-13,2015-04-16,PSG Split night,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,5.816667,26.1,33.7,16.903167,13.744833,3.158333
Morris_Martha_112512_2118.000,Z9992290,512-71-58,Morris,Martha,Female,1947-04-30,2012-11-25,PSG all night CPAP,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,0.883333,0.0,0.0,5.814500,4.109917,1.704583
Schlein_Toby_012717_2300.000,Z6488130,354-22-12,Schlein,Toby,Female,1945-11-16,2017-01-27,PSG Diagnostic,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,5.350000,8.4,6.4,6.542250,6.542250,0.000000
Callahan_Marian_042010_2158.000,Z10588347,160-39-24,Callahan,Marian,Female,1959-08-30,2010-04-20,PSG Diagnostic,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,6.366667,2.8,2.1,0.815583,0.199500,0.616083

In [10]:
from sleep_analysis_functions import compute_spo2_clean, compute_hypoxia_burden, desaturation_detection, hypoxaemic_burden_minutes

def compute_hypoxia_statistics(data, apnea, sleep_stage, fs):
    
    data['apnea'] = apnea

    dt_start = pd.Timestamp('2000-01-01 00:00:00')
    dt_end = dt_start + datetime.timedelta(seconds=(data.shape[0]-1) / fs)
    pseudo_dt_index = pd.date_range(start=dt_start, end=dt_end, periods=data.shape[0])
    data.index = pseudo_dt_index

    data = compute_spo2_clean(data, fs=fs)
    data['spo2'] = data['spo2_clean']

    data['apnea_binary'] = np.isin(data['apnea'],[1,2,3,4]).astype(int)
    data['apnea_end'] = np.isin(data['apnea_binary'].diff(), [-1])
    
    sleep_stage = sleep_stage[np.logical_not(pd.isna(sleep_stage))]
    hours_sleep = sum(sleep_stage<5)/fs/3600
    
    data, hypoxia_burden = compute_hypoxia_burden(data, fs, hours_sleep=hours_sleep, apnea_name = 'apnea')
    
    T90burden, T90desaturation, T90nonspecific = hypoxaemic_burden_minutes(data['spo2'].values, fs)
    
    AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)

    return hypoxia_burden, AHI, hours_sleep, T90burden, T90desaturation, T90nonspecific

In [11]:
sleeplab_table.shape

(25231, 17)

In [12]:
part = 4

for jloc, row in tqdm(sleeplab_table.iterrows()):
    
    try:
        if pd.isna(row.path_signal) | pd.isna(row.path_annotations):
            continue
        
        if pd.notna(row.AHI):
            continue # already done.
        
        if 'natus' in row.Path.lower():
            continue # natus still running and not affected by bug.
        
        # read in raw data:
        signal, params = load_mgh_signal(row.path_signal)
        annotations = pd.read_csv(row.path_annotations)

        fs = int(params['Fs'])
        signal_len = signal.shape[0]

        # get respiratory event and sleep stage array:
        annotations = annotations_preprocess(annotations, fs)
        resp = vectorize_respiratory_events(annotations, signal_len)
        sleep_stage = vectorize_sleep_stages(annotations, signal_len)

        hypoxia_burden, ahi, total_sleep_time, T90burden, T90desaturation, T90nonspecific = compute_hypoxia_statistics(signal, resp, sleep_stage, fs)

        sleeplab_table.loc[jloc, 'AHI'] = ahi
        sleeplab_table.loc[jloc, 'HypoxiaBurden'] = hypoxia_burden
        sleeplab_table.loc[jloc, 'Total_Sleep_Time'] = total_sleep_time
        sleeplab_table.loc[jloc, 'T90_minutes'] = T90burden
        sleeplab_table.loc[jloc, 'T90_minutes_desat'] = T90desaturation
        sleeplab_table.loc[jloc, 'T90_minutes_unspecific'] = T90nonspecific

        sleeplab_table.to_csv(f'sleeplab_table_hypoxia_{part}.csv')
        
    except Exception as e:
        print(f'{jloc}, {row.Path}')
        print(e)

sleeplab_table.to_csv(f'sleeplab_table_hypoxia_{part}.csv')

0it [00:00, ?it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
82it [00:40,  1.84it/s]

Hexley_Allie_121015_0834.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hexley_Allie_121015_0834.000
local variable 'samples_limit' referenced before assignment

135it [00:40,  4.09it/s]

Rummel_Jeremy_010811_0553.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Rummel_Jeremy_010811_0553.000
Cannot convert non-finite values (NA or inf) to integer
Dugan_David_040314_2202.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Dugan_David_040314_2202.000
Cannot convert non-finite values (NA or inf) to integer

142it [00:51,  2.72it/s]

Merceds_Alfredo_020609_2145.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Merceds_Alfredo_020609_2145.000
argument of type 'float' is not iterable

232it [01:17,  3.10it/s]

Mitchell_Elliot_120315_0846.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mitchell_Elliot_120315_0846.000
index 5752000 is out of bounds for axis 0 with size 5752000

252it [01:34,  2.45it/s]

Harper_Alexandra_040111_0903.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Harper_Alexandra_040111_0903.000
local variable 'samples_limit' referenced before assignment

278it [01:35,  3.13it/s]

Nadel_Robert_071715_0410.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Nadel_Robert_071715_0410.000
Cannot convert non-finite values (NA or inf) to integer

296it [01:43,  2.90it/s]

Allen_Matthew_121009_0904.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Allen_Matthew_121009_0904.000
local variable 'samples_limit' referenced before assignment

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
320it [02:18,  1.36it/s]

Paton_Robert_022411_0831.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Paton_Robert_022411_0831.000
index 4816000 is out of bounds for axis 0 with size 4816000

334it [02:26,  1.44it/s]

Plapinger_Ellen_042913_2321.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Plapinger_Ellen_042913_2321.000
Cannot convert non-finite values (NA or inf) to integer

388it [02:29,  3.00it/s]

Al-Saud_Lolowah_042111_2321.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Al-Saud_Lolowah_042111_2321.000
Cannot convert non-finite values (NA or inf) to integer

566it [02:31, 10.30it/s]

Saravia_Alfredo_Partial_051610_2316.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Saravia_Alfredo_Partial_051610_2316.000
Cannot convert non-finite values (NA or inf) to integer

603it [02:54,  5.24it/s]

Psichoulas_Andrew_121010_2209.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Psichoulas_Andrew_121010_2209.000
local variable 'samples_limit' referenced before assignment

622it [03:14,  3.42it/s]

Modica_Rose_101712_2205.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Modica_Rose_101712_2205.000
float division by zero

636it [03:14,  3.78it/s]

Bougary_Loay_022310_2322.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bougary_Loay_022310_2322.000
float division by zero

667it [03:15,  4.97it/s]

Towne_Harold C_041817_2222.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Towne_Harold C_041817_2222.000
float division by zero

667it [03:34,  4.97it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
718it [03:36,  3.56it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
763it [04:02,  2.66it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
858it [04:20,  5.05it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
900it [04:51,  2.19it/s]

Chen_Dante_111910_0906.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Chen_Dante_111910_0906.000
index 4621000 is out of bounds for axis 0 with size 4621000

1011it [05:16,  3.04it/s]

Fisher_Linda_062812_0907.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Fisher_Linda_062812_0907.000
index 5926000 is out of bounds for axis 0 with size 5926000

1017it [05:26,  2.61it/s]

Bethune_Henry_032216_0237.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bethune_Henry_032216_0237.000
float division by zero

1044it [05:28,  3.09it/s]

Nadel_Robert_071715_0852.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Nadel_Robert_071715_0852.000
Cannot convert non-finite values (NA or inf) to integer

1060it [05:56,  1.87it/s]

Fortunato_Joanne_013113_0855.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Fortunato_Joanne_013113_0855.000
index 6427200 is out of bounds for axis 0 with size 6427200

1086it [06:22,  1.53it/s]

Kuzmin_Sergey_101812_0841.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Kuzmin_Sergey_101812_0841.000
index 6044000 is out of bounds for axis 0 with size 6044000

1090it [06:22,  1.61it/s]

Drourr_Shawn_100317_2113.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Drourr_Shawn_100317_2113.000
float division by zero

1211it [06:25,  4.87it/s]

Viella_Darlene_022312_0843.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Viella_Darlene_022312_0843.000
Cannot convert non-finite values (NA or inf) to integer

1214it [06:30,  4.22it/s]

Olms_Haylee_050616_0829.000_MERGED, M:\Datasets_ConvertedData\sleeplab\grass_data\Olms_Haylee_050616_0829.000_MERGED
float division by zero

1293it [06:58,  3.38it/s]

Bazinet_Joseph_043012_0847.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bazinet_Joseph_043012_0847.000
index 5974000 is out of bounds for axis 0 with size 5974000

1297it [07:06,  2.85it/s]

Coady_William_122008_2156.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Coady_William_122008_2156.000
argument of type 'float' is not iterable

1306it [07:07,  3.08it/s]

Hardej_Lissa M_071216_2211.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hardej_Lissa M_071216_2211.000
float division by zero

1389it [07:16,  4.83it/s]

CHAMPION_DANIELLE_011513_0808.000, M:\Datasets_ConvertedData\sleeplab\grass_data\CHAMPION_DANIELLE_011513_0808.000
Cannot convert non-finite values (NA or inf) to integer

1391it [07:17,  4.74it/s]

Laliberte_Justin_041609_2214.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Laliberte_Justin_041609_2214.000
float division by zero

1431it [07:47,  2.50it/s]

Callahan_Shaun_100313_0846.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Callahan_Shaun_100313_0846.000
index 5799200 is out of bounds for axis 0 with size 5799200

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
1454it [08:17,  1.50it/s]

Berg_William_030212_0930.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Berg_William_030212_0930.000
index 5615000 is out of bounds for axis 0 with size 5615000

1507it [08:41,  1.79it/s]

Kerrigan_Kelly_021116_0843.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Kerrigan_Kelly_021116_0843.000
index 5888000 is out of bounds for axis 0 with size 5888000

1622it [09:05,  2.89it/s]

Wallace_Janice_082009_2335.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Wallace_Janice_082009_2335.000
index 4892600 is out of bounds for axis 0 with size 4892600

1632it [09:31,  1.99it/s]

Grab_Tori_111113_0844.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Grab_Tori_111113_0844.000
index 6340800 is out of bounds for axis 0 with size 6340800

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
1660it [10:12,  1.35it/s]

Connolly_Edward_110611_2031.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Connolly_Edward_110611_2031.000
float division by zero

1696it [10:39,  1.35it/s]

Clement_Sara_012216_0903.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Clement_Sara_012216_0903.000
index 5565600 is out of bounds for axis 0 with size 5565600

1751it [11:02,  1.65it/s]

Ayers_Ronald_070915_0856.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ayers_Ronald_070915_0856.000
index 5781600 is out of bounds for axis 0 with size 5781600

1839it [11:08,  2.98it/s]

BrokenOuellette_Adrian_052512_2215.000, M:\Datasets_ConvertedData\sleeplab\grass_data\BrokenOuellette_Adrian_052512_2215.000
Cannot convert non-finite values (NA or inf) to integer

1922it [11:17,  4.07it/s]

Gooch_Christine_040714_2146.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Gooch_Christine_040714_2146.000
Cannot convert non-finite values (NA or inf) to integer

2027it [11:40,  4.32it/s]

Leung_Suikau_022012_2115.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Leung_Suikau_022012_2115.000
float division by zero

2033it [12:02,  2.89it/s]

Graziano_Daniel_120514_0855.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Graziano_Daniel_120514_0855.000
index 5208800 is out of bounds for axis 0 with size 5208800

2083it [12:11,  3.31it/s]

Santos_Dorothy_021512_0143.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Santos_Dorothy_021512_0143.000
float division by zero

2093it [12:15,  3.22it/s]

Jastrzebski_Marian_102115_2251.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Jastrzebski_Marian_102115_2251.000
Cannot convert non-finite values (NA or inf) to integer

2101it [12:18,  3.15it/s]

Charles_Julianne_090910_0839.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Charles_Julianne_090910_0839.000
Cannot convert non-finite values (NA or inf) to integer

2107it [12:19,  3.38it/s]

Ehlert_Anne T_022416_2205.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ehlert_Anne T_022416_2205.000
Cannot convert non-finite values (NA or inf) to integer

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
2178it [12:43,  2.92it/s]

Hickson_Rebecca_012612_0816.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hickson_Rebecca_012612_0816.000
index 5894000 is out of bounds for axis 0 with size 5894000

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
2280it [13:48,  1.94it/s]

Cordova_Carlos_022517_2307.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cordova_Carlos_022517_2307.000
index 4581000 is out of bounds for axis 0 with size 4581000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
2408it [14:04,  3.73it/s]

O'neil_Nicholas_052011_0820.000, M:\Datasets_ConvertedData\sleeplab\grass_data\O'neil_Nicholas_052011_0820.000
Cannot convert non-finite values (NA or inf) to integer

2408it [14:20,  3.73it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
2457it [14:48,  2.35it/s]

Coco_Marcella_041912_0943.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Coco_Marcella_041912_0943.000
index 4618000 is out of bounds for axis 0 with size 4618000

2475it [14:54,  2.46it/s]

Friedman_Anna_070313_0914.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Friedman_Anna_070313_0914.000
Cannot convert non-finite values (NA or inf) to integer

2534it [15:16,  2.51it/s]

Scully_Peter_102814_2101.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Scully_Peter_102814_2101.000
float division by zero

2545it [15:42,  1.72it/s]

Murphy_Jillian_070214_0859.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Murphy_Jillian_070214_0859.000
index 5993600 is out of bounds for axis 0 with size 5993600

2668it [16:09,  2.76it/s]

Christie_Andre_111916_2216.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Christie_Andre_111916_2216.000
index 5696600 is out of bounds for axis 0 with size 5696600

2683it [16:22,  2.43it/s]

Fried_Susan_092109_2256.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Fried_Susan_092109_2256.000
float division by zero

2689it [16:29,  2.20it/s]

Marilyn_Spence_100312_2203.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Marilyn_Spence_100312_2203.000
Cannot convert non-finite values (NA or inf) to integer

2731it [16:37,  2.77it/s]

Baer_Stan_010811_2303.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Baer_Stan_010811_2303.000
Cannot convert non-finite values (NA or inf) to integer

2762it [16:54,  2.43it/s]

Alkasab_Josephine_010716_0904.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Alkasab_Josephine_010716_0904.000
local variable 'samples_limit' referenced before assignment

2889it [16:58,  5.49it/s]

Bouras_Matthew_090308_2247.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bouras_Matthew_090308_2247.000
argument of type 'float' is not iterable

2889it [17:16,  5.49it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
2960it [17:34,  3.46it/s]

Edwards_Jasper_060910_2315.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Edwards_Jasper_060910_2315.000
Cannot convert non-finite values (NA or inf) to integer

2984it [19:01,  1.14it/s]

Wolff_Mario P_080616_2241.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Wolff_Mario P_080616_2241.000
index 5566400 is out of bounds for axis 0 with size 5566400

3022it [19:26,  1.22it/s]

Bullock_Betsy_110614_0847.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bullock_Betsy_110614_0847.000
index 5752000 is out of bounds for axis 0 with size 5752000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
3111it [19:53,  1.85it/s]

Knowlton_Paul_120615_0052.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Knowlton_Paul_120615_0052.000
Cannot convert non-finite values (NA or inf) to integer

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
3268it [20:09,  4.54it/s]

Nee_Scott_110716_2257.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Nee_Scott_110716_2257.000
Cannot convert non-finite values (NA or inf) to integer

3280it [20:14,  4.31it/s]

Broken_Kelley_Michael_080811_2206.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Broken_Kelley_Michael_080811_2206.000
Cannot convert non-finite values (NA or inf) to integer

3283it [20:18,  3.80it/s]

Goldstein_James_Partial_051710_0022.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Goldstein_James_Partial_051710_0022.000
Cannot convert non-finite values (NA or inf) to integer

3318it [20:48,  2.26it/s]

Crawford_Carol_092012_0849.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Crawford_Carol_092012_0849.000
index 6212000 is out of bounds for axis 0 with size 6212000

3330it [20:52,  2.35it/s]

Rourke_Timothy_063011_0843.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Rourke_Timothy_063011_0843.000
Cannot convert non-finite values (NA or inf) to integer

3476it [20:53,  7.24it/s]

Shaw_Kathleen_030911_2145.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Shaw_Kathleen_030911_2145.000
Cannot convert non-finite values (NA or inf) to integer

3481it [21:06,  4.66it/s]

Murphy_Conor_053113_0834.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Murphy_Conor_053113_0834.000
index 4995600 is out of bounds for axis 0 with size 4995600

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
3544it [21:32,  3.43it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
3593it [22:17,  1.89it/s]

Takaya_Shigetoshi_052113_0900.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Takaya_Shigetoshi_052113_0900.000
index 5782400 is out of bounds for axis 0 with size 5782400

/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:479: RuntimeWarning: invalid value encountered in double_scalars
  hypoxic_burden = np.sum(areas_robust)/hours_sleep
3770it [22:34,  4.24it/s]

Bezeredy_Felix_021413_2145.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bezeredy_Felix_021413_2145.000
float division by zero

3825it [22:38,  5.00it/s]

Aharonian_Christine_051412_2338.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Aharonian_Christine_051412_2338.000
Cannot convert non-finite values (NA or inf) to integer

4037it [22:39, 11.15it/s]

Damian_Chris_012616_2250.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Damian_Chris_012616_2250.000
Cannot convert non-finite values (NA or inf) to integer

4095it [22:44, 11.19it/s]

Maffei_Robert_121311_2352.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Maffei_Robert_121311_2352.000
Cannot convert non-finite values (NA or inf) to integer

4107it [22:50,  9.24it/s]

Hurley_Robert_051314_2241.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hurley_Robert_051314_2241.000
Cannot convert non-finite values (NA or inf) to integer

4152it [22:54,  9.54it/s]

Bethune_Henry_032116_2130.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bethune_Henry_032116_2130.000
Cannot convert non-finite values (NA or inf) to integer

4168it [23:19,  4.06it/s]

Veale_Michael_060613_0837.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Veale_Michael_060613_0837.000
index 6086400 is out of bounds for axis 0 with size 6086400

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
4390it [23:34,  8.87it/s]

Murray_Theresa_040814_2159.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Murray_Theresa_040814_2159.000
Cannot convert non-finite values (NA or inf) to integer

4446it [23:53,  6.28it/s]

Hussain_Fatima_042214_0910.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hussain_Fatima_042214_0910.000
local variable 'samples_limit' referenced before assignment

4499it [24:17,  4.44it/s]

Abdolmohammadi_Yasaman_010816_0852.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Abdolmohammadi_Yasaman_010816_0852.000
index 5286400 is out of bounds for axis 0 with size 5286400

4560it [24:38,  3.94it/s]

Mello_Kyle_062912_2027.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mello_Kyle_062912_2027.000
local variable 'samples_limit' referenced before assignment

4621it [24:41,  5.01it/s]

Aldrich_Alexandra_022411_0813.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Aldrich_Alexandra_022411_0813.000
Cannot convert non-finite values (NA or inf) to integer

4652it [24:42,  5.80it/s]

Dunlavey_Joann_022712_2310.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Dunlavey_Joann_022712_2310.000
Cannot convert non-finite values (NA or inf) to integer

4705it [25:06,  3.95it/s]

Hague_Kendra_060911_0847.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hague_Kendra_060911_0847.000
local variable 'samples_limit' referenced before assignment

4714it [25:24,  2.70it/s]

GRECO_ANTHONY_092912_2148.000, M:\Datasets_ConvertedData\sleeplab\grass_data\GRECO_ANTHONY_092912_2148.000
float division by zero

4776it [25:44,  2.85it/s]

Martignetti_Carmela_030416_0846.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Martignetti_Carmela_030416_0846.000
index 4523200 is out of bounds for axis 0 with size 4523200

4800it [25:53,  2.84it/s]

Turano_Anthony_012915_2315.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Turano_Anthony_012915_2315.000
Cannot convert non-finite values (NA or inf) to integer

4800it [26:12,  2.84it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
4911it [26:33,  3.12it/s]

Lamour_Jean_121012_2227.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lamour_Jean_121012_2227.000
float division by zero

4931it [26:52,  2.44it/s]

McIntosh_Cheryl_M_071514_0916.000, M:\Datasets_ConvertedData\sleeplab\grass_data\McIntosh_Cheryl_M_071514_0916.000
index 4451200 is out of bounds for axis 0 with size 4451200

4962it [27:02,  2.57it/s]

Hosker_Warren_031610_2224.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hosker_Warren_031610_2224.000
index 1960000 is out of bounds for axis 0 with size 1960000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
4965it [27:23,  1.68it/s]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
4971it [28:09,  1.18s/it]

Ruta_Lisa M._110716_2207.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ruta_Lisa M._110716_2207.000
index 5785000 is out of bounds for axis 0 with size 5785000

4972it [28:09,  1.17s/it]

Scenna_Donna_082209_2204.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Scenna_Donna_082209_2204.000
float division by zero

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
4996it [28:35,  1.23it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5040it [28:47,  1.51it/s]

Barry_Aliou_010712_0301.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Barry_Aliou_010712_0301.000
Cannot convert non-finite values (NA or inf) to integer

5045it [28:54,  1.39it/s]

Vlahakes_Gus_072508_2213.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Vlahakes_Gus_072508_2213.000
argument of type 'float' is not iterable

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5150it [29:01,  4.54it/s]

Broken_Santos_Dorothy_021412_2123.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Broken_Santos_Dorothy_021412_2123.000
Cannot convert non-finite values (NA or inf) to integer

5150it [29:19,  4.54it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5156it [29:28,  1.93it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5260it [29:51,  4.51it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5324it [30:07,  2.95it/s]

Dolan.0000, M:\Datasets_ConvertedData\sleeplab\grass_data\Dolan.0000
local variable 'samples_limit' referenced before assignment

5383it [30:14,  4.00it/s]

Foster_Michael_040714_2133.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Foster_Michael_040714_2133.000
Cannot convert non-finite values (NA or inf) to integer

5449it [30:30,  4.05it/s]

Torres_Bernice_012113_2218.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Torres_Bernice_012113_2218.000
float division by zero

5450it [30:32,  3.81it/s]

Crevecour-MSLT_Evelyne_080708_0835.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Crevecour-MSLT_Evelyne_080708_0835.000
argument of type 'float' is not iterable

5463it [30:56,  2.14it/s]

Wainblat_Robert_041813_0830.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Wainblat_Robert_041813_0830.000
index 5626400 is out of bounds for axis 0 with size 5626400

5508it [31:21,  1.97it/s]

Bullis_Jackie_042209_0808.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bullis_Jackie_042209_0808.000
index 6011000 is out of bounds for axis 0 with size 6011000

5510it [31:30,  1.66it/s]

Lathan_Rachael_040814_2307.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lathan_Rachael_040814_2307.000
Cannot convert non-finite values (NA or inf) to integer

5650it [31:31,  5.63it/s]

Haddad_Maher_061512_2149.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Haddad_Maher_061512_2149.000
Cannot convert non-finite values (NA or inf) to integer

5661it [31:36,  4.90it/s]

Delorie_Edward_010909_2214.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Delorie_Edward_010909_2214.000
argument of type 'float' is not iterable

5665it [32:00,  2.40it/s]

Heimes_Jacqueline_030713_0854.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Heimes_Jacqueline_030713_0854.000
index 5685600 is out of bounds for axis 0 with size 5685600

5667it [32:25,  1.38it/s]

Hoffmann_Carol-Anne_081315_0852.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hoffmann_Carol-Anne_081315_0852.000
index 6505600 is out of bounds for axis 0 with size 6505600

5718it [32:32,  2.25it/s]

McCrensky_Robert_122410_0003.000, M:\Datasets_ConvertedData\sleeplab\grass_data\McCrensky_Robert_122410_0003.000
Cannot convert non-finite values (NA or inf) to integer

5833it [32:40,  4.62it/s]

Cavallaro_Sandra_101608_2245.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cavallaro_Sandra_101608_2245.000
argument of type 'float' is not iterable

5899it [32:46,  5.88it/s]

Broken_Connor_David_022511_2152.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Broken_Connor_David_022511_2152.000
Cannot convert non-finite values (NA or inf) to integer

5943it [32:46,  7.57it/s]

Copy of Atefi Aghayan_Vahid_032911_2315.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Copy of Atefi Aghayan_Vahid_032911_2315.000
float division by zero

5943it [33:07,  7.57it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6086it [33:36,  4.34it/s]

Lefebvre_Christina_P._101515_0855.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lefebvre_Christina_P._101515_0855.000
local variable 'samples_limit' referenced before assignment

6130it [33:56,  3.57it/s]

Jain_Niharika_102215_0910.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Jain_Niharika_102215_0910.000
index 4611200 is out of bounds for axis 0 with size 4611200

6193it [34:20,  3.19it/s]

Manning_Michael_080715_0844.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Manning_Michael_080715_0844.000
index 5651200 is out of bounds for axis 0 with size 5651200

6234it [34:23,  3.85it/s]

Curran_Kathleen_042812_2303.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Curran_Kathleen_042812_2303.000
Cannot convert non-finite values (NA or inf) to integer

6279it [34:24,  5.16it/s]

Appleby_Shaun_120913_0908.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Appleby_Shaun_120913_0908.000
No columns to parse from file

6299it [34:29,  4.94it/s]

Rossman_Joanne_120108_2219.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Rossman_Joanne_120108_2219.000
argument of type 'float' is not iterable

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6333it [34:30,  6.55it/s]

Mancio_Marcos T_052017_2247.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mancio_Marcos T_052017_2247.000
float division by zero

6344it [34:32,  6.53it/s]

Cieri_Mildred_090210_2134.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cieri_Mildred_090210_2134.000
Cannot convert non-finite values (NA or inf) to integer

6395it [34:37,  8.16it/s]

Schonback_David_120311_2217.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Schonback_David_120311_2217.000
Cannot convert non-finite values (NA or inf) to integer

6397it [35:00,  2.34it/s]

Abraham_Jobin_041713_0842.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Abraham_Jobin_041713_0842.000
index 5536000 is out of bounds for axis 0 with size 5536000

6473it [35:03,  4.99it/s]

Warren_Steven_090711_2135.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Warren_Steven_090711_2135.000
float division by zero

6551it [35:08,  7.30it/s]

Broken_Mulkerrins_Ellen_070711_2136.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Broken_Mulkerrins_Ellen_070711_2136.000
Cannot convert non-finite values (NA or inf) to integer

6599it [35:33,  4.01it/s]

Cederbaum_Katherine_062614_0820.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cederbaum_Katherine_062614_0820.000
index 6559200 is out of bounds for axis 0 with size 6559200

6672it [36:02,  3.28it/s]

Ribeiro_Rudi_042612_0845.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ribeiro_Rudi_042612_0845.000
index 6541000 is out of bounds for axis 0 with size 6541000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6682it [36:43,  1.62it/s]

Barclay_Charles_011215_0857.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Barclay_Charles_011215_0857.000
index 4534400 is out of bounds for axis 0 with size 4534400

6706it [37:08,  1.37it/s]

Targonski_Elizabeth_040711_2159.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Targonski_Elizabeth_040711_2159.000
index 4967000 is out of bounds for axis 0 with size 4967000

6708it [37:14,  1.26it/s]

Griffis_Mary_070911_2047.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Griffis_Mary_070911_2047.000
Cannot convert non-finite values (NA or inf) to integer

6712it [37:19,  1.22it/s]

Maguire_Lynda_021814_0111.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Maguire_Lynda_021814_0111.000
Cannot convert non-finite values (NA or inf) to integer

6712it [37:34,  1.22it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6833it [37:42,  2.95it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6899it [38:25,  2.06it/s]

Mangini_Sheri_121815_0849.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mangini_Sheri_121815_0849.000
index 4732000 is out of bounds for axis 0 with size 4732000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6913it [38:55,  1.40it/s]

Graziano_Daniel_010814_0913.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Graziano_Daniel_010814_0913.000
Cannot convert non-finite values (NA or inf) to integer

7001it [39:19,  2.28it/s]

Lozyniak_Sara_111014_1014.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lozyniak_Sara_111014_1014.000
index 5853600 is out of bounds for axis 0 with size 5853600

7069it [39:26,  3.36it/s]

Connolly_Michael_071010_2149.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Connolly_Michael_071010_2149.000
Cannot convert non-finite values (NA or inf) to integer

7170it [39:27,  6.00it/s]

Regan_CliftonJ_112808_2245.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Regan_CliftonJ_112808_2245.000
float division by zero

7170it [39:42,  6.00it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7253it [40:08,  3.24it/s]

Jones_Mary_022614_0947.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Jones_Mary_022614_0947.000
index 4360800 is out of bounds for axis 0 with size 4360800

7273it [40:35,  2.14it/s]

Griffin_Daniel_080811_2131.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Griffin_Daniel_080811_2131.000
index 6144000 is out of bounds for axis 0 with size 6144000

7280it [40:36,  2.28it/s]

Notter_David E_080317_2206.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Notter_David E_080317_2206.000
float division by zero

7315it [40:38,  3.19it/s]

Thomas_Mary_062311_0857.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Thomas_Mary_062311_0857.000
Cannot convert non-finite values (NA or inf) to integer

7326it [40:40,  3.36it/s]

Oldak_Susan M_051418_2157.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Oldak_Susan M_051418_2157.000
Unable to open file (file signature not found)

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7373it [40:48,  3.81it/s]

KONSTANTILAKIS_PANAGIOTIS_060411_2147.001, M:\Datasets_ConvertedData\sleeplab\grass_data\KONSTANTILAKIS_PANAGIOTIS_060411_2147.001
Cannot convert non-finite values (NA or inf) to integer

7384it [40:54,  3.30it/s]

GRUNZWEIG_TZAHI_020413_2356.001, M:\Datasets_ConvertedData\sleeplab\grass_data\GRUNZWEIG_TZAHI_020413_2356.001
Cannot convert non-finite values (NA or inf) to integer
Hagerty_Kevin_012016_2141.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hagerty_Kevin_012016_2141.000
Unable to open file (file signature not found)

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
7408it [41:23,  1.61it/s]

Miller_Wayne  H_070617_2312.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Miller_Wayne  H_070617_2312.000
index 4790600 is out of bounds for axis 0 with size 4790600

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7465it [41:51,  2.03it/s]

Diruzza_Christopher_021918_2051.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Diruzza_Christopher_021918_2051.000
index 1089000 is out of bounds for axis 0 with size 1089000

7469it [42:15,  1.19it/s]

Katzman_Harriet_100611_0901.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Katzman_Harriet_100611_0901.000
index 5599000 is out of bounds for axis 0 with size 5599000

7490it [42:19,  1.58it/s]

Howard_Shelli_050913_0856.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Howard_Shelli_050913_0856.000
Cannot convert non-finite values (NA or inf) to integer

7550it [42:35,  2.32it/s]

Leonard_Jimmie_061115_0905.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Leonard_Jimmie_061115_0905.000
local variable 'samples_limit' referenced before assignment

7556it [42:36,  2.47it/s]

Albadri_Awatif_120909_2316.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Albadri_Awatif_120909_2316.000
float division by zero

7580it [42:36,  3.46it/s]

Cala_Adelina_120910_2228.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cala_Adelina_120910_2228.000
Cannot convert non-finite values (NA or inf) to integer

7618it [42:42,  4.37it/s]

Engelbrecht_Jan_101508_2301.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Engelbrecht_Jan_101508_2301.000
argument of type 'float' is not iterable

7647it [43:06,  2.40it/s]

Murphy_Andrew_010515_0856.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Murphy_Andrew_010515_0856.000
index 4619200 is out of bounds for axis 0 with size 4619200

7678it [43:16,  2.59it/s]

Jerry Yu_Theresa_021914_0826.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Jerry Yu_Theresa_021914_0826.000
local variable 'samples_limit' referenced before assignment

7687it [43:30,  1.91it/s]

Doyle_Sean_090812_2348.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Doyle_Sean_090812_2348.000
float division by zero

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7722it [44:00,  1.61it/s]

Perez_Juan_022813_0848.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Perez_Juan_022813_0848.000
Cannot convert non-finite values (NA or inf) to integer

7723it [44:22,  1.07s/it]

Bogavalli_Murali_010413_0913.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bogavalli_Murali_010413_0913.000
index 5841000 is out of bounds for axis 0 with size 5841000

7751it [44:22,  1.69it/s]

Diaz_Carmen_082917_2310.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Diaz_Carmen_082917_2310.000
float division by zero

7758it [44:50,  1.06s/it]

Flekser_Clifford_031413_0900.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Flekser_Clifford_031413_0900.000
index 6040800 is out of bounds for axis 0 with size 6040800

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7772it [45:21,  1.41s/it]

Goodwin_Patrick_101708_2214.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Goodwin_Patrick_101708_2214.000
argument of type 'float' is not iterable

7845it [45:27,  2.41it/s]

Ceranoglu_Tolga_040814_2159.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ceranoglu_Tolga_040814_2159.000
Cannot convert non-finite values (NA or inf) to integer

7859it [45:40,  1.99it/s]

Armstrong_Debra_090111_1252.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Armstrong_Debra_090111_1252.000
index 3277000 is out of bounds for axis 0 with size 3277000

7881it [45:44,  2.44it/s]

Mulkerrins_Ellen_070811_0253.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mulkerrins_Ellen_070811_0253.000
Cannot convert non-finite values (NA or inf) to integer

7980it [46:07,  3.34it/s]

Pradko_Meghan_052814_2046.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Pradko_Meghan_052814_2046.000
index 5312800 is out of bounds for axis 0 with size 5312800

7990it [46:16,  2.90it/s]

O'Boy_Francis_040710_2123.000, M:\Datasets_ConvertedData\sleeplab\grass_data\O'Boy_Francis_040710_2123.000
Cannot convert non-finite values (NA or inf) to integer

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8003it [47:49,  1.75s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8004it [48:18,  2.54s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8009it [50:14,  7.69s/it]

Leghorn_Richard_022510_2225.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Leghorn_Richard_022510_2225.000
float division by zero

8016it [53:38, 22.67s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8036it [1:01:26, 22.26s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8044it [1:03:54, 18.20s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8050it [1:06:22, 24.11s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:479: RuntimeWarning: divide by zero encountered in double_scalars
  hypoxic_burden = np.sum(areas_robust)/hours_sleep
8051it [1:06:36, 22.01s/it]

Spector_June_011912_0949.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Spector_June_011912_0949.000
float division by zero

8055it [1:07:52, 18.25s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8058it [1:09:19, 23.88s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8060it [1:10:13, 25.09s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8066it [1:11:59, 19.12s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8071it [1:13:17, 14.63s/it]

AQUINO_KENNEVIE_020311_0853.001, M:\Datasets_ConvertedData\sleeplab\grass_data\AQUINO_KENNEVIE_020311_0853.001
Cannot convert non-finite values (NA or inf) to integer

8075it [1:14:53, 18.37s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8085it [1:18:20, 17.90s/it]

Minichiello_William_041012_2341.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Minichiello_William_041012_2341.000
float division by zero

8087it [1:18:44, 15.52s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:436: RuntimeWarning: Mean of empty slice
  mean_spo2 = np.nanmean(np.array(spo2_collection), axis=0)
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:479: RuntimeWarning: invalid value encountered in double_scalars
  hypoxic_burden = np.sum(areas_robust)/hours_sleep
8088it [1:18:56, 14.92s/it]

Cronin_Nicole_040111_2319.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cronin_Nicole_040111_2319.000
float division by zero

8098it [1:21:47, 19.77s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8106it [1:26:11, 20.63s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8116it [1:31:23, 30.37s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8118it [1:32:28, 31.60s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8119it [1:33:39, 42.76s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8124it [1:34:40, 19.13s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8134it [1:40:02, 27.35s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8135it [1:40:27, 26.83s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8148it [1:46:29, 30.72s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8168it [1:55:45, 27.83s/it]

Pasquale_Nicole_050212_0858.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Pasquale_Nicole_050212_0858.000
index 6337000 is out of bounds for axis 0 with size 6337000

8177it [1:59:24, 23.65s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8179it [2:00:27, 26.53s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8181it [2:01:19, 26.24s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
8187it [2:04:01, 27.11s/it]

Segnini_Jessica_012816_0851.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Segnini_Jessica_012816_0851.000
index 5851200 is out of bounds for axis 0 with size 5851200

8196it [2:08:59, 32.81s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8200it [2:10:37, 25.65s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8202it [2:12:40, 45.79s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
8207it [2:14:58, 30.59s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8212it [2:16:49, 21.20s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8213it [2:17:31, 26.27s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8228it [2:25:30, 32.77s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8238it [2:30:53, 36.90s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8269it [2:47:35, 40.70s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8275it [2:51:02, 35.53s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8302it [3:02:37, 26.40s/it]

HILLIS_JAMES_042511_2312.000, M:\Datasets_ConvertedData\sleeplab\grass_data\HILLIS_JAMES_042511_2312.000
Cannot convert non-finite values (NA or inf) to integer

8307it [3:04:49, 27.23s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8335it [3:14:00, 20.27s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:436: RuntimeWarning: Mean of empty slice
  mean_spo2 = np.nanmean(np.array(spo2_collection), axis=0)
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
8338it [3:15:19, 22.57s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8341it [3:16:36, 23.14s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8358it [3:24:29, 21.67s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8401it [3:41:28, 24.14s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8407it [3:43:40, 22.16s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8427it [3:51:54, 29.29s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8439it [3:56:49, 16.86s/it]

Goldberg_Barbara_071411_0914.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Goldberg_Barbara_071411_0914.000
local variable 'samples_limit' referenced before assignment

8452it [4:01:04, 24.74s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8455it [4:02:49, 32.94s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8463it [4:04:57, 15.08s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
8467it [4:07:13, 28.52s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8473it [4:09:05, 19.54s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8476it [4:10:30, 24.23s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8481it [4:13:42, 30.12s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8488it [4:15:47, 14.68s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8492it [4:17:39, 22.49s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8523it [4:29:43, 18.32s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8527it [4:31:23, 19.97s/it]

Kokennen_Lindsay_091212_0927.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Kokennen_Lindsay_091212_0927.000
index 5562400 is out of bounds for axis 0 with size 5562400

8533it [4:33:02, 17.21s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8540it [4:36:10, 22.38s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8545it [4:37:31, 18.17s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8556it [4:41:52, 18.53s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8562it [4:43:36, 18.48s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8568it [4:45:57, 22.06s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8579it [4:49:36, 24.38s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8584it [4:51:45, 25.52s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8585it [4:52:25, 29.64s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8591it [4:55:05, 23.61s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8593it [4:56:24, 28.89s/it]

Digregorio_Ann_041111_2336.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Digregorio_Ann_041111_2336.000
index 3832000 is out of bounds for axis 0 with size 3832000

8626it [5:09:27, 17.74s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8627it [5:09:57, 20.42s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8656it [5:21:52, 27.67s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8659it [5:22:51, 22.04s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8666it [5:24:45, 15.59s/it]

Graizzaro_Bruno_102412_2139.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Graizzaro_Bruno_102412_2139.000
Cannot convert non-finite values (NA or inf) to integer

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8672it [5:27:21, 23.79s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8677it [5:29:29, 25.41s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8678it [5:29:50, 23.95s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8680it [5:31:12, 32.04s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8681it [5:31:40, 30.78s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8685it [5:34:02, 32.19s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8686it [5:35:04, 41.24s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8687it [5:35:44, 40.89s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8694it [5:39:22, 32.04s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
8700it [5:42:59, 34.07s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:479: RuntimeWarning: invalid value encountered in double_scalars
  hypoxic_burden = np.sum(areas_robust)/hours_sleep
8713it [5:43:14,  6.13s/it]

Oil_Karen_121710_2245.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Oil_Karen_121710_2245.000
float division by zero

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
8863it [5:43:42,  1.72it/s]

Mahoney_Truman_012014_2336.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mahoney_Truman_012014_2336.000
Cannot convert non-finite values (NA or inf) to integer

8872it [5:43:43,  1.89it/s]

Kat Ens, M:\Datasets_ConvertedData\sleeplab\grass_data\Kat Ens
float division by zero

8918it [5:43:44,  3.23it/s]

Bern_Sandra_110417_2133.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bern_Sandra_110417_2133.000
float division by zero

8982it [5:44:01,  3.42it/s]

Kwan_Raymond_110113_0859.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Kwan_Raymond_110113_0859.000
index 4142400 is out of bounds for axis 0 with size 4142400

9008it [5:44:22,  2.48it/s]

Crawford_Neta_060512_0830.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Crawford_Neta_060512_0830.000
index 5392000 is out of bounds for axis 0 with size 5392000

9136it [5:44:38,  4.25it/s]

Angel_Irina_110812_0836.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Angel_Irina_110812_0836.000
index 6226400 is out of bounds for axis 0 with size 6226400

9183it [5:45:02,  3.33it/s]

Bethune_Henry_032116_Merged_2130.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bethune_Henry_032116_Merged_2130.000
float division by zero

9198it [5:45:06,  3.34it/s]

Dudley_Horace_051012_0857.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Dudley_Horace_051012_0857.000
Cannot convert non-finite values (NA or inf) to integer

9199it [5:45:26,  2.08it/s]

Brown_Kenyatta_061813_0917.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Brown_Kenyatta_061813_0917.000
index 4490400 is out of bounds for axis 0 with size 4490400

9218it [5:45:42,  1.80it/s]

Slack_Robert_111414_0811.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Slack_Robert_111414_0811.000
local variable 'samples_limit' referenced before assignment

9225it [5:45:47,  1.75it/s]

Griffin_Melissa_121110_0225.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Griffin_Melissa_121110_0225.000
Cannot convert non-finite values (NA or inf) to integer

9256it [5:46:17,  1.39it/s]

Kalb_William_101515_0846.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Kalb_William_101515_0846.000
index 6257600 is out of bounds for axis 0 with size 6257600

9341it [5:46:44,  2.09it/s]

Locke_Jessica_031011_0846.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Locke_Jessica_031011_0846.000
index 6132000 is out of bounds for axis 0 with size 6132000

9356it [5:47:04,  1.70it/s]

Papernik_Arthur_082015_0906.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Papernik_Arthur_082015_0906.000
index 4502400 is out of bounds for axis 0 with size 4502400

9357it [5:47:07,  1.60it/s]

Lamperti_Jennifer_011212_0850.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lamperti_Jennifer_011212_0850.000
Cannot convert non-finite values (NA or inf) to integer

9420it [5:47:11,  3.02it/s]

ValentinTorres_Mildred_081908_2208.000, M:\Datasets_ConvertedData\sleeplab\grass_data\ValentinTorres_Mildred_081908_2208.000
argument of type 'float' is not iterable

9505it [5:47:17,  5.13it/s]

Larkin_Dana_111011_2301.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Larkin_Dana_111011_2301.000
Cannot convert non-finite values (NA or inf) to integer

9523it [5:47:32,  3.55it/s]

Agarwal_Rajeev_030816_2303.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Agarwal_Rajeev_030816_2303.000
float division by zero

9529it [5:48:01,  1.82it/s]

Ovalle_Marvin_051415_0856.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ovalle_Marvin_051415_0856.000
index 5531200 is out of bounds for axis 0 with size 5531200

9606it [5:48:38,  1.94it/s]

Reinach_Andrew_010517_2217.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Reinach_Andrew_010517_2217.000
index 5207000 is out of bounds for axis 0 with size 5207000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
9804it [5:49:05,  4.34it/s]

Barry_Aliou_010612_2147.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Barry_Aliou_010612_2147.000
float division by zero

9823it [5:49:09,  4.35it/s]

Griffin_Melissa_121010_2256.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Griffin_Melissa_121010_2256.000
Cannot convert non-finite values (NA or inf) to integer

9826it [5:49:16,  3.62it/s]

Marouane_Lisa_112508_2217.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Marouane_Lisa_112508_2217.000
argument of type 'float' is not iterable

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
9994it [5:49:53,  4.66it/s]

Sasso_David_042417_2148.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Sasso_David_042417_2148.000
index 30000 is out of bounds for axis 0 with size 30000

10000it [5:50:05,  3.43it/s]

McMullon_Nancy_112111_2311.000, M:\Datasets_ConvertedData\sleeplab\grass_data\McMullon_Nancy_112111_2311.000
float division by zero

10040it [5:50:29,  2.70it/s]

Marino_Barbara_041712_0854.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Marino_Barbara_041712_0854.000
index 5506000 is out of bounds for axis 0 with size 5506000

10128it [5:50:36,  4.19it/s]

Knodler_Erika_010414_2202.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Knodler_Erika_010414_2202.000
No columns to parse from file

10132it [5:50:43,  3.59it/s]

Riley_RobertE_122008_2140.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Riley_RobertE_122008_2140.000
argument of type 'float' is not iterable

10136it [5:50:50,  2.95it/s]

Lerman_Joseph_031613_2307.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lerman_Joseph_031613_2307.000
Cannot convert non-finite values (NA or inf) to integer

10279it [5:50:55,  9.34it/s]

Kolva_Jill_092810_0812.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Kolva_Jill_092810_0812.000
Cannot convert non-finite values (NA or inf) to integer
Germain_Jacqueline_050610_0900.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Germain_Jacqueline_050610_0900.000
Unable to open file (file signature not found)

10355it [5:50:55, 14.28it/s]

Santiago_Luis_041917_2131.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Santiago_Luis_041917_2131.000
float division by zero

10365it [5:51:16,  5.06it/s]

McHugh_Muriel_051911_0912.000, M:\Datasets_ConvertedData\sleeplab\grass_data\McHugh_Muriel_051911_0912.000
index 4524000 is out of bounds for axis 0 with size 4524000
Cooper_John_fixed_102815_2105.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cooper_John_fixed_102815_2105.000
Cannot convert non-finite values (NA or inf) to integer

10402it [5:51:38,  3.07it/s]

Lerman_Rebecca_M_032315_0902.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lerman_Rebecca_M_032315_0902.000
index 5075200 is out of bounds for axis 0 with size 5075200

10481it [5:51:39,  5.89it/s]

Cameron_Russell_021009_0843.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cameron_Russell_021009_0843.000
float division by zero

10552it [5:51:51,  6.00it/s]

Corrigan_Kathleen_060313_2153.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Corrigan_Kathleen_060313_2153.000
float division by zero

10654it [5:52:32,  3.64it/s]

Papadopoulos_Nikolaos_111212_2309.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Papadopoulos_Nikolaos_111212_2309.000
index 5637600 is out of bounds for axis 0 with size 5637600

10669it [5:52:53,  2.70it/s]

Burke_Joseph_092910_0842.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Burke_Joseph_092910_0842.000
index 5287000 is out of bounds for axis 0 with size 5287000

10703it [5:52:57,  3.16it/s]

Mason_Wesley_081310_0827.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mason_Wesley_081310_0827.000
Cannot convert non-finite values (NA or inf) to integer

10792it [5:53:21,  3.42it/s]

Brandt_Andrew_062215_0853.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Brandt_Andrew_062215_0853.000
index 5474400 is out of bounds for axis 0 with size 5474400

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
10933it [5:54:01,  3.34it/s]

Walker_Casey_100614_2312.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Walker_Casey_100614_2312.000
float division by zero

10948it [5:54:23,  2.45it/s]

Pollard_Charles_121112_0838.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Pollard_Charles_121112_0838.000
index 5066000 is out of bounds for axis 0 with size 5066000

10982it [5:54:24,  3.09it/s]

Burris_Hannah_021116_0850.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Burris_Hannah_021116_0850.000
Cannot convert non-finite values (NA or inf) to integer

10989it [5:54:53,  1.77it/s]

Lin_Christina_121115_0846.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lin_Christina_121115_0846.000
index 5730400 is out of bounds for axis 0 with size 5730400

11022it [5:54:59,  2.22it/s]

Germain_Jacqueline_050610_0114.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Germain_Jacqueline_050610_0114.000
Cannot convert non-finite values (NA or inf) to integer

11038it [5:55:06,  2.22it/s]

Grant_Jean_022211_2304.000broken, M:\Datasets_ConvertedData\sleeplab\grass_data\Grant_Jean_022211_2304.000broken
Cannot convert non-finite values (NA or inf) to integer

11098it [5:55:11,  3.67it/s]

Natola_William_071510_0821.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Natola_William_071510_0821.000
Cannot convert non-finite values (NA or inf) to integer

11141it [5:55:13,  5.12it/s]

Steverman_Jr._John_071014_1300.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Steverman_Jr._John_071014_1300.000
Cannot convert non-finite values (NA or inf) to integer

11205it [5:55:15,  7.92it/s]

Grant_Jean_022211_2200.000broken, M:\Datasets_ConvertedData\sleeplab\grass_data\Grant_Jean_022211_2200.000broken
Cannot convert non-finite values (NA or inf) to integer

11272it [5:55:40,  4.43it/s]

Gold_Alanna_B_111915_0858.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Gold_Alanna_B_111915_0858.000
index 5672800 is out of bounds for axis 0 with size 5672800

11277it [5:55:57,  2.91it/s]

Hammerle_Ann_052010_2213.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hammerle_Ann_052010_2213.000
float division by zero

11388it [5:56:16,  3.97it/s]

Merrill_Ryan_042314_0846.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Merrill_Ryan_042314_0846.000
index 5200000 is out of bounds for axis 0 with size 5200000

11394it [5:56:35,  2.72it/s]

Lalancette_William_101714_0844.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lalancette_William_101714_0844.000
index 4640000 is out of bounds for axis 0 with size 4640000

11417it [5:56:39,  3.03it/s]

Johnson_Edward_121511_0904.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Johnson_Edward_121511_0904.000
Cannot convert non-finite values (NA or inf) to integer

11439it [5:56:39,  3.72it/s]

Marlow_Alan_052116_2134.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Marlow_Alan_052116_2134.000
float division by zero

11448it [5:56:43,  3.45it/s]

Watson_Edward_061412_0841.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Watson_Edward_061412_0841.000
Cannot convert non-finite values (NA or inf) to integer

11501it [5:56:49,  5.02it/s]

Cody_James_012609_2228.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cody_James_012609_2228.000
argument of type 'float' is not iterable

11641it [5:56:53, 10.74it/s]

Galante_Robert_111011_0836.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Galante_Robert_111011_0836.000
Cannot convert non-finite values (NA or inf) to integer

11641it [5:57:12, 10.74it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
11922it [5:57:25, 11.51it/s]

Donahue_Richard_052510_0835.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Donahue_Richard_052510_0835.000
Cannot convert non-finite values (NA or inf) to integer

11968it [5:57:25, 13.29it/s]

Struzik_Paul_101513_2308.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Struzik_Paul_101513_2308.000
Unable to open file (file signature not found)

11968it [5:57:40, 13.29it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12115it [5:57:50,  9.29it/s]

Achadinha_Katarina_021412_2212.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Achadinha_Katarina_021412_2212.000
Cannot convert non-finite values (NA or inf) to integer

12129it [5:57:53,  8.58it/s]

Ruiz_Kendrick_053009_0132.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ruiz_Kendrick_053009_0132.000
Cannot convert non-finite values (NA or inf) to integer

12129it [5:58:07,  8.58it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12245it [5:58:19,  6.22it/s]

Moulaison_Alan_021712_2235.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Moulaison_Alan_021712_2235.000
Cannot convert non-finite values (NA or inf) to integer

12253it [5:58:42,  3.18it/s]

Beal_Jeanette_060712_0905.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Beal_Jeanette_060712_0905.000
index 5773000 is out of bounds for axis 0 with size 5773000

12266it [5:58:42,  3.56it/s]

Cooper_John_102815_2105.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cooper_John_102815_2105.000
Cannot convert non-finite values (NA or inf) to integer

12268it [5:59:21,  1.30it/s]

Jasny_Lila_052314_0113.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Jasny_Lila_052314_0113.000
index 8777600 is out of bounds for axis 0 with size 8777600

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12400it [6:00:10,  2.03it/s]

Rosen_Emily_033015_0855.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Rosen_Emily_033015_0855.000
index 5316000 is out of bounds for axis 0 with size 5316000

12407it [6:00:17,  1.90it/s]

Katherine_Clarke_071414_2303.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Katherine_Clarke_071414_2303.000
Cannot convert non-finite values (NA or inf) to integer

12504it [6:00:21,  3.99it/s]

Germain_Jacqueline_Partial_050610_0900.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Germain_Jacqueline_Partial_050610_0900.000
Cannot convert non-finite values (NA or inf) to integer

12533it [6:00:21,  4.88it/s]

Hoffman_Patrick_111413_2145.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hoffman_Patrick_111413_2145.000
float division by zero

12537it [6:00:49,  2.18it/s]

Invencio_Dennis_111711_0816.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Invencio_Dennis_111711_0816.000
index 5839000 is out of bounds for axis 0 with size 5839000

12569it [6:00:50,  3.07it/s]

Thompson_Justin_042717_2238.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Thompson_Justin_042717_2238.000
float division by zero

12618it [6:00:50,  4.99it/s]

Miller_Kenneth J_062317_FIXED_2227.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Miller_Kenneth J_062317_FIXED_2227.000
float division by zero

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12663it [6:01:20,  2.27it/s]

DelRossi_AnnMarie_061512_0906.000, M:\Datasets_ConvertedData\sleeplab\grass_data\DelRossi_AnnMarie_061512_0906.000
index 6438000 is out of bounds for axis 0 with size 6438000

12709it [6:01:45,  2.05it/s]

Beecham_Deborah_122310_0801.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Beecham_Deborah_122310_0801.000
index 6071000 is out of bounds for axis 0 with size 6071000

12790it [6:02:09,  2.58it/s]

Manzo_Peter_121515_0851.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Manzo_Peter_121515_0851.000
index 5565600 is out of bounds for axis 0 with size 5565600

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12812it [6:02:44,  1.77it/s]

Murphy_KathrynA_081508_2210.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Murphy_KathrynA_081508_2210.000
argument of type 'float' is not iterable

12839it [6:02:49,  2.14it/s]

Judd_Marjorie_120113_2307.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Judd_Marjorie_120113_2307.000
Cannot convert non-finite values (NA or inf) to integer

12971it [6:03:14,  3.57it/s]

Maunsell_Hannah_060211_0831.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Maunsell_Hannah_060211_0831.000
index 6237000 is out of bounds for axis 0 with size 6237000

12999it [6:03:20,  3.66it/s]

Martin_JanetM_121008_2142.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Martin_JanetM_121008_2142.000
argument of type 'float' is not iterable

13069it [6:03:37,  3.84it/s]

Lee_Peter_052313_0914.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lee_Peter_052313_0914.000
local variable 'samples_limit' referenced before assignment

13130it [6:03:38,  5.43it/s]

Crimmins_Robert_013116_2100.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Crimmins_Robert_013116_2100.000
Cannot convert non-finite values (NA or inf) to integer

13172it [6:04:00,  3.82it/s]

Morse_Jennifer_041714_0850.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Morse_Jennifer_041714_0850.000
index 5120000 is out of bounds for axis 0 with size 5120000

13269it [6:04:03,  6.27it/s]

RUANO-MSLT_LUDVIN_071008_0826.000, M:\Datasets_ConvertedData\sleeplab\grass_data\RUANO-MSLT_LUDVIN_071008_0826.000
argument of type 'float' is not iterable

13280it [6:04:20,  3.95it/s]

Rosen_Alexander_021512_0923.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Rosen_Alexander_021512_0923.000
local variable 'samples_limit' referenced before assignment

13317it [6:04:41,  3.04it/s]

Sutcliffe_Own_082511_2103.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Sutcliffe_Own_082511_2103.000
local variable 'samples_limit' referenced before assignment

13340it [6:04:44,  3.35it/s]

Freitas_Theresa_091008_0002.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Freitas_Theresa_091008_0002.000
argument of type 'float' is not iterable

13397it [6:05:04,  3.17it/s]

Argyle_Alannah_071615_0847.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Argyle_Alannah_071615_0847.000
index 4435200 is out of bounds for axis 0 with size 4435200

13424it [6:05:28,  2.31it/s]

DeOliveria_William_080212_0836.000, M:\Datasets_ConvertedData\sleeplab\grass_data\DeOliveria_William_080212_0836.000
index 6113600 is out of bounds for axis 0 with size 6113600

13443it [6:05:47,  1.88it/s]

Baker_Megan_011516_0855.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Baker_Megan_011516_0855.000
index 4195200 is out of bounds for axis 0 with size 4195200

13549it [6:06:13,  2.74it/s]

Squires_Jeremiah_102711_0835.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Squires_Jeremiah_102711_0835.000
index 5936000 is out of bounds for axis 0 with size 5936000

13561it [6:06:39,  1.91it/s]

Everett_Kathryn_102215_0930.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Everett_Kathryn_102215_0930.000
index 5859200 is out of bounds for axis 0 with size 5859200

13562it [6:06:45,  1.74it/s]

Doherty_Nancy_011909_2248.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Doherty_Nancy_011909_2248.000
argument of type 'float' is not iterable

13568it [6:06:49,  1.71it/s]

Leyden_Peter_082808_2209.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Leyden_Peter_082808_2209.000
argument of type 'float' is not iterable

13637it [6:07:03,  2.74it/s]

Ludkiewicz_Artur_041211_2253.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ludkiewicz_Artur_041211_2253.000
float division by zero

13674it [6:07:06,  3.58it/s]

Carlin_Sandra_082913_0904.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Carlin_Sandra_082913_0904.000
Cannot convert non-finite values (NA or inf) to integer

13699it [6:07:06,  4.51it/s]

Smith_William_081615_2256.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Smith_William_081615_2256.000
Cannot convert non-finite values (NA or inf) to integer

13737it [6:07:09,  5.94it/s]

Bono_Paul_051911_2113.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bono_Paul_051911_2113.000
Cannot convert non-finite values (NA or inf) to integer

13742it [6:07:24,  2.94it/s]

Goldberg_Barbara_071311_2235.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Goldberg_Barbara_071311_2235.000
float division by zero

13757it [6:07:42,  1.95it/s]

Farris_Alexandra_121715_0856.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Farris_Alexandra_121715_0856.000
index 4314400 is out of bounds for axis 0 with size 4314400

13824it [6:07:43,  4.37it/s]

Rosado_Lissette S_121616_2217.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Rosado_Lissette S_121616_2217.000
Unable to open file (file signature not found)

13849it [6:07:47,  4.73it/s]

Broken_Connor_David_022611_0244.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Broken_Connor_David_022611_0244.000
Cannot convert non-finite values (NA or inf) to integer

13859it [6:08:13,  2.01it/s]

Dauphinais_Janet_041113_0852.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Dauphinais_Janet_041113_0852.000
index 5886400 is out of bounds for axis 0 with size 5886400

13892it [6:08:31,  1.93it/s]

Scarborough_Shelly_042015_0856.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Scarborough_Shelly_042015_0856.000
index 4215200 is out of bounds for axis 0 with size 4215200

14002it [6:08:51,  3.27it/s]

Aquino_Luz_040315_0852.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Aquino_Luz_040315_0852.000
index 4572000 is out of bounds for axis 0 with size 4572000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
14134it [6:09:02,  5.01it/s]

Simmons_Eullett_110612_1003.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Simmons_Eullett_110612_1003.000
index 2629800 is out of bounds for axis 0 with size 2629800

14138it [6:09:25,  2.71it/s]

Roberts_Stacy_073114_0917.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Roberts_Stacy_073114_0917.000
index 5004800 is out of bounds for axis 0 with size 5004800

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
14165it [6:09:51,  2.01it/s]

Cirulli_Franco_081815_0451.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cirulli_Franco_081815_0451.000
Cannot convert non-finite values (NA or inf) to integer

14197it [6:09:56,  2.60it/s]

Widell_Joan_010409_2229.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Widell_Joan_010409_2229.000
argument of type 'float' is not iterable

14364it [6:10:00,  8.09it/s]

Cabrero_Christophe_092112_2201.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cabrero_Christophe_092112_2201.000
Cannot convert non-finite values (NA or inf) to integer

14407it [6:10:04,  8.49it/s]

Cirulli_Franco_081715_2236.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cirulli_Franco_081715_2236.000
Cannot convert non-finite values (NA or inf) to integer

14410it [6:10:07,  7.33it/s]

Celmaster_Livia_032114_1001.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Celmaster_Livia_032114_1001.000
Cannot convert non-finite values (NA or inf) to integer

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
14464it [6:10:11,  8.62it/s]

Cabrero_Christophe_092212_0348.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cabrero_Christophe_092212_0348.000
Cannot convert non-finite values (NA or inf) to integer

14531it [6:10:23,  6.89it/s]

Pellegrino_Emily_011410_2153.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Pellegrino_Emily_011410_2153.000
local variable 'samples_limit' referenced before assignment

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
14637it [6:10:50,  5.77it/s]

Galuski_Marjorie_082311_2115.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Galuski_Marjorie_082311_2115.000
float division by zero

14771it [6:11:15,  5.57it/s]

Milne_Olivia_010615_0904.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Milne_Olivia_010615_0904.000
index 5893600 is out of bounds for axis 0 with size 5893600

14836it [6:11:18,  6.90it/s]

Lanik_Gregory_033012_2304.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lanik_Gregory_033012_2304.000
Cannot convert non-finite values (NA or inf) to integer

14859it [6:11:45,  3.80it/s]

Bacigalupe_Bethania_040110_0855.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bacigalupe_Bethania_040110_0855.000
index 6330000 is out of bounds for axis 0 with size 6330000

14907it [6:11:54,  4.08it/s]

Jerry_Yu_Theresa_021914_0826.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Jerry_Yu_Theresa_021914_0826.000
local variable 'samples_limit' referenced before assignment

15013it [6:12:07,  5.19it/s]

Aldoukhi_Murtadha_011416_0808.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Aldoukhi_Murtadha_011416_0808.000
local variable 'samples_limit' referenced before assignment

15028it [6:12:11,  5.10it/s]

Taylor_Matthew_101814_0136.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Taylor_Matthew_101814_0136.000
Cannot convert non-finite values (NA or inf) to integer

15079it [6:12:11,  7.11it/s]

Um_Stephen_081809_2229.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Um_Stephen_081809_2229.000
Unable to open file (file signature not found)

15139it [6:12:36,  4.33it/s]

Tricomi_Briana_010815_0904.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Tricomi_Briana_010815_0904.000
index 5874400 is out of bounds for axis 0 with size 5874400

15141it [6:12:46,  3.28it/s]

Aquino_Kennevie_020311_0853.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Aquino_Kennevie_020311_0853.000
local variable 'samples_limit' referenced before assignment

15178it [6:12:50,  4.09it/s]

Bell_Eric_071411_2202.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bell_Eric_071411_2202.000
Cannot convert non-finite values (NA or inf) to integer

15178it [6:13:03,  4.09it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15253it [6:13:47,  1.99it/s]

Todd_Douglas_072811_0848.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Todd_Douglas_072811_0848.000
index 6000000 is out of bounds for axis 0 with size 6000000

15317it [6:14:16,  2.09it/s]

Crowley_Christopher_010515_0851.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Crowley_Christopher_010515_0851.000
index 6249600 is out of bounds for axis 0 with size 6249600

15319it [6:14:17,  2.06it/s]

Verrecchia_Donald_081111_1100.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Verrecchia_Donald_081111_1100.000
Cannot convert non-finite values (NA or inf) to integer

15324it [6:14:19,  2.08it/s]

Armstrong_Debra_090111_0848.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Armstrong_Debra_090111_0848.000
Cannot convert non-finite values (NA or inf) to integer

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15408it [6:14:46,  2.24it/s]

Karimi_Khatidja_061815_0853.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Karimi_Khatidja_061815_0853.000
index 5978400 is out of bounds for axis 0 with size 5978400

15495it [6:15:09,  2.89it/s]

Paton_Robert_052912_0903.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Paton_Robert_052912_0903.000
index 5344000 is out of bounds for axis 0 with size 5344000

15502it [6:16:20,  1.09it/s]

Mcpherson_Lanne_092611_2206.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mcpherson_Lanne_092611_2206.000
index 16208000 is out of bounds for axis 0 with size 16208000

15544it [6:16:24,  1.54it/s]

LEUNG_SUIKAU_021412_2219.000, M:\Datasets_ConvertedData\sleeplab\grass_data\LEUNG_SUIKAU_021412_2219.000
Cannot convert non-finite values (NA or inf) to integer

15554it [6:16:49,  1.20it/s]

Bonetti_Christine_071014_0904.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bonetti_Christine_071014_0904.000
index 5764000 is out of bounds for axis 0 with size 5764000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15629it [6:16:59,  2.33it/s]

Paige_Heather_021413_0208.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Paige_Heather_021413_0208.000
Cannot convert non-finite values (NA or inf) to integer

15632it [6:17:13,  1.71it/s]

Menicucci_Matias_R_110915_2300.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Menicucci_Matias_R_110915_2300.000
float division by zero

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15656it [6:17:58,  1.01it/s]

Decker_Kerry_010611_0837.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Decker_Kerry_010611_0837.000
index 5857000 is out of bounds for axis 0 with size 5857000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15664it [6:18:22,  1.30s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15712it [6:18:48,  1.17it/s]

Powell_Robert_W_090315_0907.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Powell_Robert_W_090315_0907.000
index 4196000 is out of bounds for axis 0 with size 4196000

15774it [6:19:14,  1.67it/s]

Flaherty_Sean_110410_0834.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Flaherty_Sean_110410_0834.000
index 5963000 is out of bounds for axis 0 with size 5963000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15797it [6:19:28,  1.71it/s]

Becerril_Valentin_022712_2248.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Becerril_Valentin_022712_2248.000
Cannot convert non-finite values (NA or inf) to integer

15963it [6:19:29,  7.35it/s]

Lynch_Mark A._083017_2116.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lynch_Mark A._083017_2116.000
float division by zero
Jenkins_Shirley_120814_2258.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Jenkins_Shirley_120814_2258.000
float division by zero

16079it [6:19:34, 11.17it/s]

Sparks_Ronald_022612_2203.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Sparks_Ronald_022612_2203.000
Cannot convert non-finite values (NA or inf) to integer
Cofield_Charles_092009_2221.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Cofield_Charles_092009_2221.000
float division by zero

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16105it [6:19:37, 11.04it/s]

Mazzola_Salvatore_062209_2218.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mazzola_Salvatore_062209_2218.000
float division by zero

16105it [6:19:52, 11.04it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16211it [6:20:06,  5.71it/s]

Lewis_Donna_022612_2115.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lewis_Donna_022612_2115.000
Cannot convert non-finite values (NA or inf) to integer

16220it [6:20:32,  2.74it/s]

SLOCUM_KIMBERLY_050511_0821.000, M:\Datasets_ConvertedData\sleeplab\grass_data\SLOCUM_KIMBERLY_050511_0821.000
index 6226000 is out of bounds for axis 0 with size 6226000

16255it [6:20:53,  2.31it/s]

Gribbin_Nicola_040614_2058.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Gribbin_Nicola_040614_2058.000
float division by zero

16314it [6:20:57,  3.52it/s]

Doyle_Sarah_110112_0832.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Doyle_Sarah_110112_0832.000
Cannot convert non-finite values (NA or inf) to integer

16344it [6:20:58,  4.43it/s]

Verrecchia_Donald_081111_0734.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Verrecchia_Donald_081111_0734.000
Cannot convert non-finite values (NA or inf) to integer

16344it [6:21:12,  4.43it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16378it [6:21:22,  2.78it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16494it [6:22:09,  2.80it/s]

Hansen_Tor_080714_0855.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hansen_Tor_080714_0855.000
index 4354400 is out of bounds for axis 0 with size 4354400

16564it [6:22:31,  2.89it/s]

McCooey_Candice_031711_0843.000, M:\Datasets_ConvertedData\sleeplab\grass_data\McCooey_Candice_031711_0843.000
index 5869000 is out of bounds for axis 0 with size 5869000

16570it [6:22:32,  2.99it/s]

Copy of Marulli_Ralph_022010_2141.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Copy of Marulli_Ralph_022010_2141.000
float division by zero

16732it [6:38:43, 24.43s/it]

Hosford_Christian_053012_0905.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hosford_Christian_053012_0905.000
Cannot convert non-finite values (NA or inf) to integer

16743it [6:46:27, 46.41s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16745it [6:48:19, 49.18s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16747it [6:49:46, 45.56s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16755it [6:55:07, 39.16s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16764it [7:01:43, 36.84s/it]

Kaser_Amy_072314_0857.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Kaser_Amy_072314_0857.000
index 4283200 is out of bounds for axis 0 with size 4283200

16767it [7:03:15, 31.69s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16772it [7:05:09, 21.79s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16792it [7:17:36, 45.36s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16807it [7:26:13, 33.50s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16812it [7:28:20, 20.86s/it]

Schaefer_Donald_052709_2252.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Schaefer_Donald_052709_2252.000
float division by zero

16812it [7:28:37, 20.86s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16816it [7:30:38, 27.64s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16821it [7:32:42, 28.85s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16823it [7:33:23, 25.01s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16833it [7:38:45, 30.22s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16838it [7:40:47, 24.86s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16839it [7:41:31, 30.53s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16850it [7:46:47, 22.52s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16853it [7:48:32, 30.78s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16855it [7:49:46, 33.15s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16856it [7:50:32, 36.92s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16861it [7:53:10, 31.07s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16863it [7:54:18, 33.37s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16867it [7:56:28, 30.60s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16870it [7:57:29, 23.84s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16872it [7:58:10, 23.16s/it]

Quade_Benjamin_R_010716_0840.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Quade_Benjamin_R_010716_0840.000
index 5379200 is out of bounds for axis 0 with size 5379200

16881it [8:03:59, 35.65s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16890it [8:09:17, 35.25s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16897it [8:14:23, 43.31s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16905it [8:18:14, 26.63s/it]

Browner_Brandon_092914_2309.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Browner_Brandon_092914_2309.000
Cannot convert non-finite values (NA or inf) to integer

16915it [8:23:19, 29.02s/it]

Baker_Jameson_061914_0922.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Baker_Jameson_061914_0922.000
index 5573600 is out of bounds for axis 0 with size 5573600

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16923it [8:27:32, 31.82s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16924it [8:28:10, 33.64s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16940it [8:36:30, 32.02s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16947it [8:39:39, 30.35s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16973it [8:52:04, 26.00s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16974it [8:52:46, 30.85s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16977it [8:54:18, 31.53s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16992it [9:02:17, 28.19s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
16999it [9:06:44, 34.16s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17005it [9:10:06, 32.58s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17007it [9:10:58, 28.91s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17011it [9:13:00, 28.31s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17012it [9:14:02, 38.48s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17013it [9:14:40, 38.35s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17020it [9:18:39, 32.06s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17022it [9:19:31, 29.04s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17033it [9:23:58, 21.56s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17048it [9:31:46, 29.97s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17058it [9:37:22, 29.36s/it]

Campbell_Marlyne_M_040815_2243.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Campbell_Marlyne_M_040815_2243.000
float division by zero

17063it [9:39:32, 23.57s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17068it [9:42:17, 29.05s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17075it [9:45:37, 28.21s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17082it [9:48:53, 24.12s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17088it [9:51:20, 24.93s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17107it [10:00:41, 25.73s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17109it [10:01:56, 31.17s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17112it [10:03:40, 33.85s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17114it [10:04:52, 35.06s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
17118it [10:06:36, 27.52s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17124it [10:09:18, 27.83s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17126it [10:10:03, 24.87s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17127it [10:10:29, 25.44s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17130it [10:12:32, 33.96s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17134it [10:14:10, 25.78s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17143it [10:18:22, 31.92s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17165it [10:28:27, 25.42s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17188it [10:38:25, 27.26s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17189it [10:39:03, 30.51s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17191it [10:40:28, 37.08s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17195it [10:42:05, 28.29s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17210it [10:48:02, 24.42s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17214it [10:50:00, 26.88s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17220it [10:53:52, 34.24s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17223it [10:55:57, 37.29s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17236it [11:02:45, 27.53s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17238it [11:03:31, 25.06s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17240it [11:04:37, 28.59s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17245it [11:06:55, 29.23s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17247it [11:08:00, 27.92s/it]

Falta_Richard_090117_2137.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Falta_Richard_090117_2137.000
float division by zero

17251it [11:09:49, 27.71s/it]

Lobel_Kathryn_101714_0848.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lobel_Kathryn_101714_0848.000
index 6147200 is out of bounds for axis 0 with size 6147200

17256it [11:12:41, 31.22s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17266it [11:16:48, 23.34s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17278it [11:21:25, 15.73s/it]

Apodaca_Albert_112008_2241.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Apodaca_Albert_112008_2241.000
argument of type 'float' is not iterable

17288it [11:26:41, 33.24s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17296it [11:31:13, 30.76s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17298it [11:32:15, 31.02s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17299it [11:32:51, 32.39s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17312it [11:38:48, 19.79s/it]

BrokenOuellette_Adrian_052612_0449.000, M:\Datasets_ConvertedData\sleeplab\grass_data\BrokenOuellette_Adrian_052612_0449.000
Cannot convert non-finite values (NA or inf) to integer

17320it [11:42:35, 31.17s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17330it [11:47:46, 25.95s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17333it [11:49:24, 33.01s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17334it [11:49:50, 31.09s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17335it [11:50:29, 33.34s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17344it [11:55:01, 31.27s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17360it [12:03:16, 39.86s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17361it [12:03:54, 39.10s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17369it [12:07:49, 30.90s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17371it [12:10:17, 56.95s/it]

Bugden_Charles_052914_2200.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bugden_Charles_052914_2200.000
index 14923200 is out of bounds for axis 0 with size 14923200

17385it [12:16:28, 27.46s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17386it [12:16:56, 27.52s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17388it [12:17:59, 29.03s/it]

Mimouni_Rachid_030817_2314.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mimouni_Rachid_030817_2314.000
index 5205000 is out of bounds for axis 0 with size 5205000

17390it [12:19:02, 30.18s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17395it [12:21:48, 30.04s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17425it [12:24:36,  3.35s/it]

Matour_Stephanie_010714_0838.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Matour_Stephanie_010714_0838.000
index 5499200 is out of bounds for axis 0 with size 5499200

17448it [12:24:52,  1.91s/it]

Piretti_Ronald_022613_2244.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Piretti_Ronald_022613_2244.000
float division by zero

17472it [12:25:13,  1.44s/it]

Farber_Shoshana_050114_1021.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Farber_Shoshana_050114_1021.000
index 5284000 is out of bounds for axis 0 with size 5284000

17489it [12:25:13,  1.01it/s]

Rosenfield_Jack_080917_2204.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Rosenfield_Jack_080917_2204.000
float division by zero

17525it [12:25:42,  1.11it/s]

MacDonald_Anne C_110517_2102.000, M:\Datasets_ConvertedData\sleeplab\grass_data\MacDonald_Anne C_110517_2102.000
index 6390800 is out of bounds for axis 0 with size 6390800

17602it [12:26:08,  1.76it/s]

Sears_Andrea_052611_0806.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Sears_Andrea_052611_0806.000
index 6073000 is out of bounds for axis 0 with size 6073000

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
17640it [12:26:54,  1.33it/s]

Pure_Julie_071311_0914.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Pure_Julie_071311_0914.000
index 4853000 is out of bounds for axis 0 with size 4853000

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
17730it [12:27:38,  1.66it/s]

Sullivan_Carl_082416_2128.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Sullivan_Carl_082416_2128.000
index 6090400 is out of bounds for axis 0 with size 6090400

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
17757it [12:28:11,  1.38it/s]

Friday_Susan_092108_2307.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Friday_Susan_092108_2307.000
argument of type 'float' is not iterable

17760it [12:28:54,  1.29s/it]

Contreras_William_050616_2323.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Contreras_William_050616_2323.000
index 5208600 is out of bounds for axis 0 with size 5208600

17801it [12:29:36,  1.17s/it]

Sofia_Robert_091413_2227.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Sofia_Robert_091413_2227.000
cannot convert float NaN to integer

17987it [12:29:42,  3.08it/s]

Gallotto_Rosanna_110808_2210.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Gallotto_Rosanna_110808_2210.000
argument of type 'float' is not iterable

18021it [12:29:42,  3.66it/s]

Previte_Anthony_052715_2158.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Previte_Anthony_052715_2158.000
Cannot convert non-finite values (NA or inf) to integer

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
18129it [12:29:49,  5.52it/s]

Consentino_Matthew_041410_0804.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Consentino_Matthew_041410_0804.000
Cannot convert non-finite values (NA or inf) to integer

18189it [12:30:12,  4.05it/s]

Appleby_Shaun_111711_0822.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Appleby_Shaun_111711_0822.000
index 5818000 is out of bounds for axis 0 with size 5818000

18202it [12:30:25,  3.19it/s]

Fontaine_Peter_020613_2356.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Fontaine_Peter_020613_2356.000
index 2272800 is out of bounds for axis 0 with size 2272800

18250it [12:30:42,  3.07it/s]

Romero_Zoila_081414_0920.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Romero_Zoila_081414_0920.000
index 4224000 is out of bounds for axis 0 with size 4224000

18297it [12:30:44,  4.20it/s]

Langone_Filomena_030812_1313.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Langone_Filomena_030812_1313.000
Cannot convert non-finite values (NA or inf) to integer

18338it [12:30:47,  5.25it/s]

Santos_Dorothy_021412_2228.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Santos_Dorothy_021412_2228.000
Cannot convert non-finite values (NA or inf) to integer

18376it [12:31:02,  4.05it/s]

Beecham_Deborah_020911_0840.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Beecham_Deborah_020911_0840.000
index 5248000 is out of bounds for axis 0 with size 5248000

18392it [12:31:03,  4.60it/s]

Afshari_Naseema_102808_2157.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Afshari_Naseema_102808_2157.000
float division by zero

18405it [12:32:12,  1.08it/s]

Beatty_Joseph_032210_2352.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Beatty_Joseph_032210_2352.000
index 15120000 is out of bounds for axis 0 with size 15120000

18468it [12:32:15,  2.02it/s]

Diruzza_Christopher_062211_0959.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Diruzza_Christopher_062211_0959.000
Cannot convert non-finite values (NA or inf) to integer

18535it [12:32:41,  2.23it/s]

Gross_Sandra_041514_0847.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Gross_Sandra_041514_0847.000
index 6174400 is out of bounds for axis 0 with size 6174400

18537it [12:33:01,  1.61it/s]

Chang_Timothy_020714_0855.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Chang_Timothy_020714_0855.000
index 4508000 is out of bounds for axis 0 with size 4508000

18575it [12:33:13,  1.90it/s]

Hague_Kendra_060911_0112.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hague_Kendra_060911_0112.000
index 2962000 is out of bounds for axis 0 with size 2962000

18579it [12:33:19,  1.76it/s]

Goff_Jonathan_072310_0828.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Goff_Jonathan_072310_0828.000
Cannot convert non-finite values (NA or inf) to integer

18621it [12:33:22,  2.73it/s]

Lopes_Mirlaine_012314_0941.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Lopes_Mirlaine_012314_0941.000
Cannot convert non-finite values (NA or inf) to integer

18756it [12:33:23,  7.60it/s]

Desir_Claude_042211_2312.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Desir_Claude_042211_2312.000
Cannot convert non-finite values (NA or inf) to integer

18786it [12:33:24,  9.01it/s]

Dole_Charlotte_021710_2326.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Dole_Charlotte_021710_2326.000
float division by zero

18786it [12:33:39,  9.01it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
18805it [12:33:53,  3.07it/s]

Vicari_Anthony_120512_2311.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Vicari_Anthony_120512_2311.000
Cannot convert non-finite values (NA or inf) to integer

18852it [12:33:55,  4.79it/s]

Burrell_Charles_021716_2143.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Burrell_Charles_021716_2143.000
Cannot convert non-finite values (NA or inf) to integer

18879it [12:34:14,  3.05it/s]

Herlihy_Lillian_012810_2200.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Herlihy_Lillian_012810_2200.000
local variable 'samples_limit' referenced before assignment

19000it [12:34:28,  5.05it/s]

Capuano_Rita-ann_102810_2220.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Capuano_Rita-ann_102810_2220.000
float division by zero

19051it [12:34:42,  4.53it/s]

Frost_John_093009_2306.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Frost_John_093009_2306.000
float division by zero

19071it [12:35:07,  2.82it/s]

Gillam_Jessica_032113_0831.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Gillam_Jessica_032113_0831.000
index 6101600 is out of bounds for axis 0 with size 6101600

19096it [12:35:14,  2.93it/s]

Regan_Frances_090508_2152.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Regan_Frances_090508_2152.000
argument of type 'float' is not iterable

19132it [12:35:18,  3.57it/s]

Catricala_Paul_022512_2334.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Catricala_Paul_022512_2334.000
Cannot convert non-finite values (NA or inf) to integer

19144it [12:35:27,  3.02it/s]

King_Cheryl_040814_2146.000, M:\Datasets_ConvertedData\sleeplab\grass_data\King_Cheryl_040814_2146.000
Cannot convert non-finite values (NA or inf) to integer

19144it [12:35:47,  3.02it/s]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
19173it [12:36:24,  1.25it/s]

Hunter_Hattie_052717_2104.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hunter_Hattie_052717_2104.000
index 6443200 is out of bounds for axis 0 with size 6443200

19263it [12:36:27,  2.72it/s]

Kelley_Michael_080911_0339.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Kelley_Michael_080911_0339.000
Cannot convert non-finite values (NA or inf) to integer

19320it [12:36:29,  3.88it/s]

Schonback_David_120411_0400.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Schonback_David_120411_0400.000
Cannot convert non-finite values (NA or inf) to integer

19320it [12:36:43,  3.88it/s]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
19367it [12:37:03,  2.56it/s]

Stroman_Richard_021509_2254.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Stroman_Richard_021509_2254.000
index 5296400 is out of bounds for axis 0 with size 5296400

19373it [12:37:41,  1.46it/s]

Judge_Catherine A_092916_2132.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Judge_Catherine A_092916_2132.000
index 5826600 is out of bounds for axis 0 with size 5826600

19377it [12:37:42,  1.51it/s]

Gregory_Michael_022111_2233.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Gregory_Michael_022111_2233.000
Cannot convert non-finite values (NA or inf) to integer

19433it [12:37:54,  2.23it/s]

Gandolfo_Emanuele_022712_2207.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Gandolfo_Emanuele_022712_2207.000
float division by zero

19493it [12:37:59,  3.35it/s]

Bezeredy_Felix_021513_0229.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bezeredy_Felix_021513_0229.000
Cannot convert non-finite values (NA or inf) to integer

19525it [12:38:01,  4.11it/s]

Nadel_Robert_071715_0104.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Nadel_Robert_071715_0104.000
Cannot convert non-finite values (NA or inf) to integer

19555it [12:38:09,  4.00it/s]

BRENNAN_STEPHEN_030713_2154.001, M:\Datasets_ConvertedData\sleeplab\grass_data\BRENNAN_STEPHEN_030713_2154.001
Cannot convert non-finite values (NA or inf) to integer

19560it [12:38:14,  3.50it/s]

Simmons_James_121708_2316.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Simmons_James_121708_2316.000
argument of type 'float' is not iterable

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
19593it [12:38:48,  2.04it/s]

Dyer_Mary_021809_2318.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Dyer_Mary_021809_2318.000
argument of type 'float' is not iterable

19602it [12:38:55,  1.87it/s]

Adrien_Gabriel_111712_2321.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Adrien_Gabriel_111712_2321.000
Cannot convert non-finite values (NA or inf) to integer

19633it [12:39:01,  2.52it/s]

Masters_Susan_111610_2220.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Masters_Susan_111610_2220.000
Cannot convert non-finite values (NA or inf) to integer

19651it [12:39:06,  2.68it/s]

YASSIN_DIANA_040813_2306.001, M:\Datasets_ConvertedData\sleeplab\grass_data\YASSIN_DIANA_040813_2306.001
Cannot convert non-finite values (NA or inf) to integer

19689it [12:39:09,  4.09it/s]

Ruiz_Kendrick_052909_2157.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ruiz_Kendrick_052909_2157.000
Cannot convert non-finite values (NA or inf) to integer

19820it [12:39:26,  6.11it/s]

CHAMPION_DANIELLE_011513_0808.000 - Copy, M:\Datasets_ConvertedData\sleeplab\grass_data\CHAMPION_DANIELLE_011513_0808.000 - Copy
index 5384400 is out of bounds for axis 0 with size 5384400

19836it [12:39:32,  5.42it/s]

Hersh_Harry_040614_2245.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hersh_Harry_040614_2245.000
Cannot convert non-finite values (NA or inf) to integer

19862it [12:39:37,  5.26it/s]

Becker_Jonathan_062610_2147.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Becker_Jonathan_062610_2147.000
Cannot convert non-finite values (NA or inf) to integer

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1389: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
19902it [12:40:14,  2.43it/s]

Weaver_Clifford_022609_2335.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Weaver_Clifford_022609_2335.000
index 4637925 is out of bounds for axis 0 with size 4637925

20104it [12:40:21,  6.50it/s]

Hylen_Eva-Marie_100514_2351.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hylen_Eva-Marie_100514_2351.000
Cannot convert non-finite values (NA or inf) to integer

20116it [12:40:46,  3.87it/s]

Levine_Jonathan_072111_0904.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Levine_Jonathan_072111_0904.000
index 5780000 is out of bounds for axis 0 with size 5780000

20153it [12:40:54,  3.99it/s]

Bell, Barbara, M:\Datasets_ConvertedData\sleeplab\grass_data\Bell, Barbara
argument of type 'float' is not iterable

20213it [12:41:04,  4.42it/s]

Sera_David_090215_2319.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Sera_David_090215_2319.000
'spo2'

20214it [12:41:47,  1.85it/s]

Culhane_Ann B._022016_2132.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Culhane_Ann B._022016_2132.000
index 6408400 is out of bounds for axis 0 with size 6408400

20259it [12:42:12,  1.84it/s]

Carpenter_Scott_052915_0839.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Carpenter_Scott_052915_0839.000
index 5628800 is out of bounds for axis 0 with size 5628800

20270it [12:42:16,  1.90it/s]

Hines_Margot_020209_2254.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hines_Margot_020209_2254.000
argument of type 'float' is not iterable

20403it [12:42:38,  3.36it/s]

Weinkopf_Madeleine_061714_2057.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Weinkopf_Madeleine_061714_2057.000
index 5368000 is out of bounds for axis 0 with size 5368000

20426it [12:42:39,  3.85it/s]

Hosford_Christian_053012_0848.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Hosford_Christian_053012_0848.000
Cannot convert non-finite values (NA or inf) to integer

20554it [12:42:39,  7.92it/s]

Dunn_Michael A _102317_2304.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Dunn_Michael A _102317_2304.000
float division by zero

20568it [12:42:46,  6.58it/s]

Karimi_Khatidja_110411_2300.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Karimi_Khatidja_110411_2300.000
Cannot convert non-finite values (NA or inf) to integer

20634it [12:42:53,  7.33it/s]

O'connor_Patricia_060911_2326.000, M:\Datasets_ConvertedData\sleeplab\grass_data\O'connor_Patricia_060911_2326.000
Cannot convert non-finite values (NA or inf) to integer

20662it [12:43:19,  3.67it/s]

Iandolo_Barbara_042513_0845.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Iandolo_Barbara_042513_0845.000
index 5883200 is out of bounds for axis 0 with size 5883200

20666it [12:43:51,  1.87it/s]

Bukoski_Kenneth_072315_2308.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Bukoski_Kenneth_072315_2308.000
index 5142400 is out of bounds for axis 0 with size 5142400

20716it [12:44:18,  1.86it/s]

KELLEY_COLBY_011713_0856.000, M:\Datasets_ConvertedData\sleeplab\grass_data\KELLEY_COLBY_011713_0856.000
index 6433600 is out of bounds for axis 0 with size 6433600

20727it [12:44:53,  1.23it/s]

Robart_Cornelia_040717_2303.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Robart_Cornelia_040717_2303.000
index 5761600 is out of bounds for axis 0 with size 5761600

20868it [12:45:01,  3.20it/s]

Farris_Jane_093010_2252.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Farris_Jane_093010_2252.000
Cannot convert non-finite values (NA or inf) to integer

20874it [12:45:01,  3.30it/s]

Resca_Anne Marie_092211_2312.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Resca_Anne Marie_092211_2312.000
float division by zero

20874it [12:45:20,  3.30it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
20942it [12:45:53,  2.12it/s]

Segal_Harriet_031111_0849.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Segal_Harriet_031111_0849.000
index 6173000 is out of bounds for axis 0 with size 6173000

20956it [12:46:15,  1.65it/s]

Ismaili_Ahmed_110811_0842.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Ismaili_Ahmed_110811_0842.000
index 5816000 is out of bounds for axis 0 with size 5816000

20958it [12:46:16,  1.66it/s]

Mattson_Eric_012215_2237.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Mattson_Eric_012215_2237.000
float division by zero

20958it [12:46:32,  1.66it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
21007it [12:46:40,  1.98it/s]

Scrivanos_Matoula_052615_2145.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Scrivanos_Matoula_052615_2145.000
Cannot convert non-finite values (NA or inf) to integer

21007it [12:46:58,  1.98it/s]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
21131it [12:47:18,  2.64it/s]

Dikeman_Peter_031714_2323.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Dikeman_Peter_031714_2323.000
float division by zero

21219it [12:47:22,  4.57it/s]

Darrell_Kevin_050312_0118.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Darrell_Kevin_050312_0118.000
Cannot convert non-finite values (NA or inf) to integer

24436it [12:47:45, 111.99it/s]

Kolchinsky_Evelina_090210_0819.000, M:\Datasets_ConvertedData\sleeplab\grass_data\Kolchinsky_Evelina_090210_0819.000
index 5930000 is out of bounds for axis 0 with size 5930000

25231it [12:47:45,  1.83s/it]

In [ ]:
sleeplab_table = sleeplab_table.reset_index()

In [16]:
sleeplab_table.shape

(25231, 17)

In [17]:
st.shape

(25231, 11)

In [18]:
# last step: add the natus files that have been computed in parallel to the above table.

In [27]:
ht2_new = pd.read_csv('sleeplab_table_hypoxia_2.csv')
ht2_new.drop(['Unnamed: 0'], axis=1, inplace=True)

In [28]:
ht2_new.shape

(7831, 18)

In [32]:
sleeplab_table.set_index('FolderName', inplace=True)
ht2_new.set_index('FolderName', inplace=True)

In [39]:
sleeplab_table.loc[ht2_new.index, hypoxia_columns] = ht2_new[hypoxia_columns].values

In [41]:
sleeplab_table.to_csv('sleeplab_table_hypoxia.csv')

In [42]:
sleeplab_table.columns

Index(['PatientID', 'MRN', 'LastName', 'FirstName', 'Sex', 'DateOfBirth',
       'DateOfVisit', 'TypeOfTest', 'Path', 'path_signal', 'path_annotations',
       'Total_Sleep_Time', 'AHI', 'HypoxiaBurden', 'T90_minutes',
       'T90_minutes_desat', 'T90_minutes_unspecific'],
      dtype='object')

### Found a big in hypoxic bruden code that resulted in HB==0. so therefore, run the code again for all patients with HB==0.

In [44]:
sleeplab_table.reset_index(inplace=True)

In [45]:
sleeplab_table.head(2)

,FolderName,PatientID,MRN,LastName,FirstName,Sex,DateOfBirth,DateOfVisit,TypeOfTest,Path,path_signal,path_annotations,Total_Sleep_Time,AHI,HypoxiaBurden,T90_minutes,T90_minutes_desat,T90_minutes_unspecific
0,Anatasia_Lori_091611_2209.000,Z11530888,424-66-43,Anastasia,Lori E,Female,1972-08-11,2011-09-16,PSG Diagnostic,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,6.641667,0.3,0.7,0.000000,0.000000,0.000000
1,Gronewold_Catherine W_041615_2224.000,Z8592929,237-74-50,Gronewold,Catherine,Female,1948-12-13,2015-04-16,PSG Split night,M:\Datasets_ConvertedData\sleeplab\grass_data\...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,/media/mad3/Datasets_ConvertedData/sleeplab/gr...,5.816667,26.1,33.7,16.903167,13.744833,3.158333

In [46]:
part = 5
n_patients_fixed = 0

for jloc, row in tqdm(sleeplab_table.iterrows()):
    
    try:
        if pd.isna(row.path_signal) | pd.isna(row.path_annotations):
            continue
        
        if row.HypoxiaBurden != 0:
            continue
                    
        # read in raw data:
        signal, params = load_mgh_signal(row.path_signal)
        annotations = pd.read_csv(row.path_annotations)

        fs = int(params['Fs'])
        signal_len = signal.shape[0]

        # get respiratory event and sleep stage array:
        annotations = annotations_preprocess(annotations, fs)
        resp = vectorize_respiratory_events(annotations, signal_len)
        sleep_stage = vectorize_sleep_stages(annotations, signal_len)

        hypoxia_burden, ahi, total_sleep_time, T90burden, T90desaturation, T90nonspecific = compute_hypoxia_statistics(signal, resp, sleep_stage, fs)

        n_patients_fixed += 1

        sleeplab_table.loc[jloc, 'AHI'] = ahi
        sleeplab_table.loc[jloc, 'HypoxiaBurden'] = hypoxia_burden
        sleeplab_table.loc[jloc, 'Total_Sleep_Time'] = total_sleep_time
        sleeplab_table.loc[jloc, 'T90_minutes'] = T90burden
        sleeplab_table.loc[jloc, 'T90_minutes_desat'] = T90desaturation
        sleeplab_table.loc[jloc, 'T90_minutes_unspecific'] = T90nonspecific

        sleeplab_table.to_csv(f'sleeplab_table_hypoxia_{part}.csv')
        
    except Exception as e:
        print(f'{jloc}, {row.Path}')
        print(e)

sleeplab_table.to_csv(f'sleeplab_table_hypoxia_{part}.csv')

67it [04:44,  3.88s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
310it [23:22,  5.48s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
673it [41:24,  3.68s/it]

672, M:\Datasets_ConvertedData\sleeplab\grass_data\Webster_Ann_063009_2211.000
axis 1 is out of bounds for array of dimension 1

717it [44:03,  3.54s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
758it [47:48,  4.65s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
857it [56:12,  5.30s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
885it [58:46,  4.52s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
1081it [1:17:18,  5.74s/it]

1080, M:\Datasets_ConvertedData\sleeplab\grass_data\Connelly_Carolyn_F._062915_2314.000
axis 1 is out of bounds for array of dimension 1

1135it [1:21:00,  4.59s/it]

1134, M:\Datasets_ConvertedData\sleeplab\grass_data\Rizzo_Edward_012613_2147.000
axis 1 is out of bounds for array of dimension 1

1401it [1:39:10,  2.04s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
1434it [1:43:04,  3.68s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
1642it [1:57:07,  4.00s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
2120it [2:24:48,  1.98s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
2278it [2:36:15,  3.62s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
2405it [2:45:51,  4.40s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
2447it [2:50:56,  9.79s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
2579it [2:55:59,  2.68s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2815it [3:10:40,  5.62s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2924it [3:18:16,  2.89s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
2965it [3:21:33,  4.14s/it]

2964, M:\Datasets_ConvertedData\sleeplab\grass_data\Jameyson_Jennifer_012813_2309.000
axis 1 is out of bounds for array of dimension 1

3073it [3:29:36,  6.16s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
3126it [3:32:11,  2.91s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
3351it [3:47:02,  6.74s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
3506it [3:57:54,  3.12s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
3581it [4:00:44,  2.58s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
4150it [4:42:15,  6.60s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
4506it [5:20:35,  6.17s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
4567it [5:30:07,  7.48s/it]

4566, M:\Datasets_ConvertedData\sleeplab\grass_data\Casanova_Kenneth_081810_2314.000
axis 1 is out of bounds for array of dimension 1

4590it [5:31:54,  5.54s/it]

4589, M:\Datasets_ConvertedData\sleeplab\grass_data\Kaplan_Linda_120713_2126.000
axis 1 is out of bounds for array of dimension 1

4795it [5:48:35,  4.72s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
4960it [5:59:58,  2.04s/it]

4959, M:\Datasets_ConvertedData\sleeplab\grass_data\Arrowood_Lisa_020812_2212.000
axis 1 is out of bounds for array of dimension 1

<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
4984it [6:03:39,  6.56s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
4996it [6:03:52,  4.12s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5100it [6:13:40,  7.85s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5154it [6:16:24,  3.15s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5178it [6:18:07,  3.30s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
5241it [6:23:01,  3.45s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5302it [6:27:29,  3.88s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
5715it [6:48:08,  2.91s/it]

5714, M:\Datasets_ConvertedData\sleeplab\grass_data\Connelly_Carolyn F._062915_2314.000
axis 1 is out of bounds for array of dimension 1

5958it [6:56:53,  2.11s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6001it [7:00:02,  4.14s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
6308it [7:13:15,  3.96s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6523it [7:26:59,  3.59s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
6671it [7:34:49,  1.99s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6824it [7:44:14,  3.76s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6873it [7:46:43,  4.21s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
6903it [7:48:50,  4.05s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7231it [8:15:45,  6.75s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
7239it [8:16:13,  5.52s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7365it [8:24:04,  3.11s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7415it [8:30:41,  6.75s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7695it [8:47:30,  5.42s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7750it [8:50:00,  1.85s/it]

7749, M:\Datasets_ConvertedData\sleeplab\grass_data\Luan_Joshua_052509_2217.000
axis 1 is out of bounds for array of dimension 1

7765it [8:52:24,  6.36s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
7978it [9:02:14,  4.51s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
7982it [9:02:51,  5.69s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
8181it [9:11:31,  1.99s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
8199it [9:13:07,  3.98s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
8324it [9:17:39,  2.22s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
8448it [9:25:26,  4.41s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
8852it [9:50:30,  7.22s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
9126it [10:06:13,  8.38s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
9637it [10:39:10,  5.38s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
9783it [10:47:02,  2.05s/it]

9782, M:\Datasets_ConvertedData\sleeplab\grass_data\Briscoe_Jane_021009_2203.000
axis 1 is out of bounds for array of dimension 1

9913it [10:53:39,  5.32s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
10390it [11:19:03,  5.11s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
10453it [11:23:21,  4.64s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
10731it [11:46:24,  7.42s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
10902it [11:57:06,  2.43s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
11069it [12:04:55,  1.65s/it]

11068, M:\Datasets_ConvertedData\sleeplab\grass_data\Larocca_Michael_031111_2149.000
axis 1 is out of bounds for array of dimension 1

11266it [12:11:26,  2.36s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
11516it [12:24:38,  3.24s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
11647it [12:31:32,  2.27s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12075it [12:57:14,  4.06s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12219it [13:07:24,  4.59s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12356it [13:16:42,  3.39s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12495it [13:25:20,  4.17s/it]

12494, M:\Datasets_ConvertedData\sleeplab\grass_data\Davis_Joseph_121415_2300.000
axis 1 is out of bounds for array of dimension 1

12621it [13:33:37,  3.41s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
12635it [13:34:48,  3.79s/it]

12634, M:\Datasets_ConvertedData\sleeplab\grass_data\Soni_Rabindra_080612_2355.000
axis 1 is out of bounds for array of dimension 1

12652it [13:36:13,  5.45s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12787it [13:43:35,  4.89s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
12955it [13:53:57,  2.46s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
13036it [13:57:57,  2.92s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
13173it [14:04:55,  2.74s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
13378it [14:14:39,  4.92s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
13411it [14:17:29,  5.77s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
13442it [14:17:54,  2.24s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
13689it [14:36:48,  2.29s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
13775it [14:43:29,  5.15s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
14109it [15:04:21,  3.56s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
14145it [15:06:17,  4.18s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
14451it [15:27:54,  3.71s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
14535it [15:30:56,  1.48s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
14581it [15:34:59,  3.67s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
14648it [15:38:13,  3.06s/it]

14647, M:\Datasets_ConvertedData\sleeplab\grass_data\Jennings Cranford_Laura_042212_2213.000
axis 1 is out of bounds for array of dimension 1

14779it [15:48:04,  6.20s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
14870it [15:52:29,  2.27s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
14992it [16:00:06,  3.27s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
15218it [16:12:59,  3.37s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15393it [16:24:56,  3.57s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15474it [16:31:50,  3.66s/it]

15473, M:\Datasets_ConvertedData\sleeplab\grass_data\Trott_Jennie Ajoriga_020617_2157.000
axis 1 is out of bounds for array of dimension 1

15561it [16:36:26,  2.92s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15636it [16:40:17,  4.47s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15651it [16:42:13,  6.36s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15683it [16:44:14,  3.95s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15780it [16:48:46,  2.78s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
15831it [16:52:32,  3.09s/it]

15830, M:\Datasets_ConvertedData\sleeplab\grass_data\Tricomi_Briana_010715_2149.000
axis 1 is out of bounds for array of dimension 1

/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
15833it [16:52:53,  3.74s/it]

15832, M:\Datasets_ConvertedData\sleeplab\grass_data\Gribbin_Nicola_030513_2131.000
tuple index out of range

16083it [17:11:55,  6.11s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16123it [17:12:59,  2.13s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16368it [17:32:40,  3.46s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16404it [17:35:44,  5.50s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16461it [17:38:28,  1.99s/it]

16460, M:\Datasets_ConvertedData\sleeplab\grass_data\Herlihy_Lillian_050517_2115.000
axis 1 is out of bounds for array of dimension 1

16815it [17:57:22,  4.06s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16858it [17:59:08,  2.46s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
16881it [18:00:20,  3.08s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
17108it [18:16:31,  8.44s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
17594it [18:52:43,  6.87s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
17746it [19:00:32,  4.54s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
17960it [19:13:24,  5.28s/it]

17959, M:\Datasets_ConvertedData\sleeplab\grass_data\Hollins_Jamila_042012_2213.000
axis 1 is out of bounds for array of dimension 1

18060it [19:21:27,  4.69s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
18090it [19:23:23,  3.75s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
18587it [19:55:47,  2.75s/it]

18586, M:\Datasets_ConvertedData\sleeplab\grass_data\Parnes_Joseph_110909_2145.000
axis 1 is out of bounds for array of dimension 1

18800it [20:09:29,  3.34s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
18974it [20:19:27,  2.40s/it]

18973, M:\Datasets_ConvertedData\sleeplab\grass_data\Denuccio_Alyssa_031818_2137.000
axis 1 is out of bounds for array of dimension 1

19019it [20:22:36,  3.81s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
19558it [20:55:40,  4.78s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
19761it [21:13:47, 11.41s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
19921it [21:23:52,  5.35s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
20791it [22:24:16,  2.90s/it]/home/wolfgang/repos/ICU-Sleep/code1/sleep_analysis_functions.py:437: RuntimeWarning: Mean of empty slice
  mean_spo2_firsthalf = mean_spo2[:mean_spo2.shape[0]//2]
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
20877it [22:27:11,  1.86s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
20976it [22:32:32,  3.66s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
21023it [22:36:01,  3.73s/it]/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:233: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
21089it [22:40:37,  2.94s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
21691it [32:14:24, 91.90s/it] <ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
22155it [43:10:10, 102.49s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
23489it [75:21:19, 109.90s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
23703it [80:51:00, 111.54s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
24494it [101:17:21, 114.25s/it]<ipython-input-10-219ea860a567>:25: RuntimeWarning: invalid value encountered in double_scalars
  AHI = np.round(sum(data['apnea_end'])/hours_sleep,1)
25231it [118:29:41, 16.91s/it]

In [10]:
# fig, ax = plt.subplots(4, 1, figsize=(10, 8), sharex=True)

# ax[0].plot(resp)
# ax[0].plot(sleep_stage)
# ax[1].plot(signal['spo2'])
# ax[1].set_ylim([80,100])
# # ax[2].plot(signal['ptaf'])
# ax[3].plot(signal['chest'])
# ax[3].plot(signal['abd'])