In [1]:
import pandas as pd
import numpy as np
import os
import sys
%load_ext autoreload
%autoreload 2
# sys.path.append('/home/wolfgang/repos/sleep_research_io')
# from sleep_research_functions import *
%matplotlib widget
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import mannwhitneyu, kruskal, f_oneway
from icu_sleep_breathing_2020_help_functions import * 

pd.options.display.max_rows = 300
pd.options.display.max_columns = 300

font = {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 7}

font_headers =  {'family' : 'sans-serif',
        'weight' : 'normal',
        'size'   : 8}

matplotlib.rc('font', **font)

In [2]:
plots_savedir = '/media/mad3/Projects/ICU_SLEEP_STUDY/Sleep_And_Breathing/plots'

[summary_subjects_icu, summary_subjects_sleeplab, 
 summary_days_icu, summary_days_sleeplab] = load_summary_data_with_inclusion_criteria()

/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3338: DtypeWarning: Columns (15,91,92,93,6455,6456,6457,12819,12820,12821,19185,19186,19187,21491,21492,21493,21519,21520,21521,21526,21527,21528,25549,25550,25551,31913,31914,31915,38279,38280,38281,44643,44644,44645,46851,46852,46853,46865,46866,46867,46879,46880,46881,46949,46950,46951,46956,46957,46958,46963,46964,46965,46970,46971,46972,46977,46978,46979,46984,46985,46986,51007,51008,51009,53336,53337,53338,57305,57373,57374,57375,59588,59589,59590,59602,59603,59604,59686,59687,59688,63669,63737,63738,63739,65952,65953,65954,65959,65960,65961,65980,65981,65982,66036,66037,66038,66043,66044,66045,66050,66051,66052,66057,66058,66059,66071,66072,66073,66078,66079,66080,70033,70101,70102,70103,72318,72319,72320,72332,72333,72334,72402,72403,72404,72416,72417,72418,76399,76467,76468,76469,78682,78683,78684,78696,78697,78698,78710,78711,78712,78766,78767,78768,78787,78788,78789,78801,78802,78803,78808,78809,78810,82763,82831,82832,82833,85039,85040,85041,85046,85047,85048,85053,85054,85055,85060,85061,85062,85067,85068,85069,85074,85075,85076,85137,85138,85139,85144,85145,85146,85151,85152,85153,89127,89195,89196,89197,91405,91406,91407,91412,91413,91414,91419,91420,91421,91426,91427,91428,91433,91434,91435,91440,91441,91442,91496,91497,91498,91503,91504,91505,91510,91511,91512,91517,91518,91519,91531,91532,91533,91538,91539,91540,95493,95561,95562,95563,97776,97777,97778,97783,97784,97785,97790,97791,97792,97804,97805,97806,97867,97868,97869,97874,97875,97876,97881,97882,97883,97888,97889,97890,97895,97896,97897,97902,97903,97904,101857,101925,101926,101927,104126,104127,104128,104133,104134,104135,104140,104141,104142,104154,104155,104156,104161,104162,104163,104168,104169,104170,104224,104225,104226,104231,104232,104233,104238,104239,104240,104245,104246,104247,104259,104260,104261,104266,104267,104268,108221,108289,108290,108291,110492,110493,110494,110499,110500,110501,110506,110507,110508,110513,110514,110515,110520,110521,110522,110527,110528,110529,110534,110535,110536,110590,110591,110592,110597,110598,110599,110604,110605,110606,110611,110612,110613,110618,110619,110620,110625,110626,110627,110632,110633,110634,114587,114655,114656,114657,116863,116864,116865,116870,116871,116872,116877,116878,116879,116884,116885,116886,116891,116892,116893,116898,116899,116900,116961,116962,116963,116968,116969,116970,116975,116976,116977,116989,116990,116991,116996,116997,116998,120951,121019,121020,121021,123234,123235,123236,123241,123242,123243,123248,123249,123250,123262,123263,123264,123318,123319,123320,123325,123326,123327,123332,123333,123334,123339,123340,123341,123353,123354,123355,123360,123361,123362,127315,127383,127384,127385,129593,129594,129595,129600,129601,129602,129607,129608,129609,129614,129615,129616,129621,129622,129623,129628,129629,129630,129684,129685,129686,129691,129692,129693,129698,129699,129700,129705,129706,129707,129719,129720,129721,129726,129727,129728,133681,133749,133750,133751,135964,135965,135966,135978,135979,135980,135992,135993,135994,136069,136070,136071,136090,136091,136092,140045,140113,140114,140115,142328,142329,142330,142342,142343,142344,142356,142357,142358,142412,142413,142414,142419,142420,142421,142447,142448,142449,142454,142455,142456,146409,146477,146478,146479,148694,148695,148696,148708,148709,148710,148722,148723,148724,148778,148779,148780,148785,148786,148787,148792,148793,148794,148799,148800,148801,148813,148814,148815,148820,148821,148822,152775,159139,159207,159208,159209,165503) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
/home/wolfgang/anaconda3/envs/analysis/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3338: DtypeWarning: Columns (15,93,94,95,2294,2295,2296,2301,2302,2303,2308,2309,2310,2315,2316,2317,2322,2323,2324,2329,2330,2331,2336,2337,2338,2392,2393,2394,2399,2400,2401,2406,2407,2408,2413,2414,2415,2420,2421,2422,2427,2428,2429,2434,2435,2436) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

# of subjects ICU before inclusion criteria: 102
# of 12-hour segments ICU before inclusion criteria: 1161
# of subjects ICU after inclusion criteria: 102
# of 12-hour segments ICU after inclusion criteria: 1161
24-hour segments: 387
12-hour segments: 774

# of subjects sleeplab before inclusion criteria: 412
# of 12-hour segments sleeplab before inclusion criteria: 412

In [3]:
for agreement in ['all', 'agreement_relaxed', 'disagreement_relaxed', 'agreement', 'disagreement']:
    for modality in ['amendsumeffort', 'ecg_nn']:
        var_n2 = 'perc_N2_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        var_n3 = 'perc_N3_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        var_sum = 'perc_N2N3_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)

        summary_days_icu[var_sum] = summary_days_icu[var_n2] + summary_days_icu[var_n3]
        summary_days_sleeplab[var_sum] = summary_days_sleeplab[var_n2] + summary_days_sleeplab[var_n3]

In [4]:
for agreement in ['agreement_relaxed', 'agreement']:
    for modality in ['amendsumeffort', 'ecg_nn']:
        var_sleep = 'hours_sleep_MODALITY_all'.replace('MODALITY', modality) # all overlap sleep
        var_agreeing = 'hours_sleep_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)
        
        if agreement == 'agreement_relaxed':
             # all overlap sleep
            var_discordant = 'hours_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement) # discordant sleep among overlap sleep
        elif agreement == 'agreement':
            var_discordant = 'hours_discordant_MODALITY_AGREEMENT'.replace('MODALITY', modality).replace('AGREEMENT', agreement)

            
        summary_days_icu[var_discordant] = summary_days_icu[var_sleep] - summary_days_icu[var_agreeing]
        summary_days_sleeplab[var_discordant] = summary_days_sleeplab[var_sleep] - summary_days_sleeplab[var_agreeing]
        
        
        sleep_total =  f'hours_sleep_{modality}_all'
        sleep_agree = f'hours_sleep_{modality}_{agreement}'
        sleep_discordant = f'hours_discordant_{modality}_{agreement}'
        discordant_proportion = f'discordant_proportion_{modality}_{agreement}'
        
        summary_days_icu[discordant_proportion] = np.divide(summary_days_icu[sleep_discordant], summary_days_icu[sleep_total])

In [5]:
summary_days_icu.loc[:, ['stages_distribution' in x for x in summary_days_icu.columns]] *= 100
summary_days_sleeplab.loc[:, ['stages_distribution' in x for x in summary_days_sleeplab.columns]] *= 100

summary_f_icu = summary_days_icu.loc[summary_days_icu.day_cat == 'f', :]
summary_dn_icu = summary_days_icu.loc[summary_days_icu.day_cat != 'f', :]

summary_days_sleeplab_full = summary_days_sleeplab.copy()

In [6]:
# compare ICU group 2 and sleeplab group 2:
# agreement = 'all'
# min_hours_sleep_icu = 0.01
# inclusion_agreement = 'all'
# do_agreement_for_sleeplab = False

# # ### compare ICU group 3 and sleeplab group 3, compute sleep statistics on ALL sleep:
agreement = 'all'
min_hours_sleep_icu = 2
inclusion_agreement = 'agreement_relaxed'
do_agreement_for_sleeplab = True

# ### compare ICU group 3 and sleeplab group 3, compute sleep statistics on CONCORDANT sleep:
# agreement = 'agreement_relaxed'
# min_hours_sleep_icu = 2
# inclusion_agreement = 'agreement_relaxed'
# do_agreement_for_sleeplab = True

In [7]:
days = 'full'

min_hours_sleep_icu = 2
if days == 'day_night':
    Xy_icu = summary_dn_icu.loc[np.any([summary_dn_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                                   summary_dn_icu[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :].copy()
elif days == 'full':
    Xy_icu = summary_f_icu.loc[np.any([summary_f_icu[f'hours_sleep_amendsumeffort_{inclusion_agreement}'] >= min_hours_sleep_icu, 
                                                   summary_f_icu[f'hours_sleep_ecg_nn_{inclusion_agreement}'] >= min_hours_sleep_icu],
                                                   axis=0), :].copy()

print(f'Segments: {Xy_icu.shape[0]}')
print(f'Subjects: {Xy_icu.study_id.unique().shape[0]}')

Segments: 163
Subjects: 80

In [8]:
Xy_icu_subject = Xy_icu.loc[:, Xy_icu.dtypes != 'object'].copy()
for study_id_tmp in Xy_icu.study_id.unique():
    
    new_values = pd.DataFrame(Xy_icu_subject.loc[Xy_icu_subject.study_id == study_id_tmp].mean()).transpose()
    Xy_icu_subject = Xy_icu_subject[Xy_icu_subject.study_id != study_id_tmp]
    Xy_icu_subject = pd.concat([Xy_icu_subject, new_values], axis=0, ignore_index=True)

In [9]:
### 3x2 plot
# cols: data type, rows: stage version (resp, ecg, expert)

variables_template = [
 'hours_sleep_MODALITY_all', # overall sleep duration.
 'hours_sleep_MODALITY_agreement_relaxed',
 'hours_discordant_MODALITY_agreement_relaxed', 
 'discordant_proportion_MODALITY_agreement_relaxed',
 'perc_S_MODALITY_AGREEMENT',
 'perc_R_MODALITY_AGREEMENT',
 'perc_N1_MODALITY_AGREEMENT',
 'perc_N2_MODALITY_AGREEMENT',
 'perc_N3_MODALITY_AGREEMENT',
 'perc_N2N3_MODALITY_AGREEMENT',
 'sfi_MODALITY_AGREEMENT',
 'arousali_MODALITY_AGREEMENT',
]

x_labels = ['Total Sleep (h)', 'Concordant S. (h)', 'Discordant S. (h)', 'Discordant S. (%)', 'Sleep (%)', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'SFI', 'Wake Trans./h']
x_labels_short = ['TS', 'CS', 'DS', 'DS%' 'S', 'R', 'N1', 'N2', 'N3', 'SFI', 'WT']

### load the diagnosis categorization and add to Xy_icu

In [10]:
diagnosis_df = pd.read_excel('/scr/wolfgang/Dropbox (Partners HealthCare)/SleepInICUandSleeplabPaper/Analysis/summary_subjects_icu_inclusion_diagnoses_deid.xlsx', engine='openpyxl')
diagnosis2_df = pd.read_excel('/scr/wolfgang/Dropbox (Partners HealthCare)/SleepInICUandSleeplabPaper/Analysis/summary_subjects_icu_inclusion_diagnoses_deid.xlsx', sheet_name=3, header=None, engine='openpyxl')

print(diagnosis_df['sepsis'].unique())
diagnosis_df['sepsis'] = diagnosis_df['sepsis'] == 'yes'
print(diagnosis_df['respiratory_failure'].unique())
diagnosis_df['resp_failure'] = diagnosis_df['respiratory_failure'] == 'yes'

print(diagnosis_df['hemorrhage_or_shock'].unique())
diagnosis_df['hemorrhage'] = np.isin(diagnosis_df['hemorrhage_or_shock'].values, ['hemorrhage', 'shock and hemorrhage', 'hemorrhage and shock', 'hemorrhage, shock', 'yes'])
diagnosis_df['shock'] = np.isin(diagnosis_df['hemorrhage_or_shock'].values, ['shock', 'shock and hemorrhage', 'hemorrhage and shock', 'hemorrhage, shock', 'yes'])

diagnosis_df['sp_liver_transplant'] = diagnosis_df['s/p_liver_transplant'] == 'yes'

diagnosis_df['resp_disease'] = np.isin(diagnosis_df['resp_disease_norespfailure'].values,['yes', 'yes?'])

diagnosis_df['heart_failure'] = np.isin(diagnosis_df['heart_failure'].values,['yes'])

diagnoses = ['resp_failure', 'resp_disease', 'heart_failure', 'sepsis', 'hemorrhage', 'shock', 'sp_liver_transplant']

diagnosis_df['other'] = ~ diagnosis_df[diagnoses].any(axis=1)

diagnoses += ['other']

[nan 'yes']
[nan 'yes']
['shock' nan 'yes' 'shock and hemorrhage' 'hemorrhage'
 'hemorrhage and shock' 'hemorrhage, shock']

# new tables/sheets from parimala

In [11]:
idx_medical = np.where(diagnosis2_df[0] == 'Medical highlighted conditions')[0][0]
idx_surgical = np.where(diagnosis2_df[0] == 'Surgical')[0][0]
idx_unhighlighted = np.where(diagnosis2_df[0] == 'Unhighlighted conditions')[0][0]

In [12]:
diagnosis_medical = diagnosis2_df.iloc[idx_medical : idx_surgical, :].transpose()
diagnosis_medical.columns = diagnosis_medical.iloc[0]
diagnosis_medical.drop(0, axis=0, inplace=True)
diagnosis_medical.drop(['Medical highlighted conditions'], axis=1, inplace=True)

diagnosis_surgical = diagnosis2_df.iloc[idx_surgical : idx_unhighlighted, :].transpose()
diagnosis_unhighlighted = diagnosis2_df.iloc[idx_unhighlighted, :].transpose()

diagnosis_surgical.columns = diagnosis_surgical.iloc[0]
diagnosis_surgical.drop(0, axis=0, inplace=True)
diagnosis_surgical.drop(['Surgical'], axis=1, inplace=True)

diagnosis_unhighlighted = diagnosis2_df.iloc[idx_unhighlighted, :].transpose()

In [13]:
diagnosis_medical.head()

,GI hemorrhage,Shock,Sepsis,Heart failure,Anemia,Hepatic encephalopathy,Hemorrhage,Encephalopathy,Pneumonia,UTI,Resp failure,AKI,AMS,COPD exacerbation,NSTEMI,Pneumothorax,Mixed resp & met acidosis,ILD,Pulm edema,Pl eff,SBO,ARDS,Panenterocolitis,Fall,SAH,MVC,Heart block,Gastric outlet obstruction,Hemothorax,SIRS,ATN,Trauma,Resp insufficiency,IPH,Cardiorenal synd,GB perf,Cryptogenic hep cirrhosis,Pulm emboli,HTN emergency,PRES,Parkinson's disease SIADH,Suicidal ideation,Parox VT,Subdural hematoma,PEA,Acute epiglottitis,Flash facial burn injury,Aortic dissection,NaN,NaN
1,1.0,1.0,3.0,3.0,12.0,21.0,24.0,25.0,25.0,3.0,25.0,3.0,33.0,45.0,45.0,49.0,69.0,79.0,83.0,84.0,86.0,88.0,109.0,121.0,121.0,122.0,122.0,126.0,128.0,131.0,133.0,135.0,135.0,121.0,139.0,140.0,145.0,151.0,155.0,155.0,156.0,157.0,158.0,165.0,176.0,177.0,178.0,186.0,NaN,NaN
2,14.0,3.0,12.0,47.0,14.0,86.0,123.0,77.0,33.0,12.0,31.0,15.0,56.0,47.0,82.0,52.0,NaN,111.0,176.0,145.0,NaN,178.0,NaN,137.0,137.0,128.0,NaN,NaN,179.0,NaN,NaN,NaN,160.0,NaN,NaN,NaN,NaN,154.0,161.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,82.0,12.0,25.0,49.0,18.0,180.0,133.0,NaN,45.0,25.0,33.0,31.0,77.0,91.0,180.0,NaN,NaN,158.0,178.0,179.0,NaN,180.0,NaN,165.0,NaN,NaN,NaN,NaN,187.0,NaN,NaN,NaN,169.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,83.0,15.0,31.0,79.0,21.0,NaN,135.0,NaN,46.0,63.0,45.0,33.0,79.0,NaN,NaN,NaN,NaN,164.0,181.0,187.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,24.0,33.0,82.0,25.0,NaN,149.0,NaN,49.0,101.0,46.0,34.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
diagnosis_surgical.head()

,Cervical stenosis with complete quadriplegia,Jugular foramen schwannoma,Nephrolithiasis,Myaesthenia gravis,Bronchopleural fistula,Incarcerated umb hernia,PAD,Aortic dissection,Necrotising soft tissue inf,Retroperitoneal hemorrhage,AAA,Cord compression,Gastric perf,Craniopharyngioma,Vocal fold necrosis & pharyngeal stenosis,MVA with multiple rib fractures,Perf sigmoid colon,Lung adenoca with LUL lobectomy,Degenerative lumbar stenosis,Lung tumor thoracotomy with chest wall resection,SBO,Bladder rupture,Ischemic stroke,Eso perf,HCV/alc cirrhosis s/p liver transplant,Carotid art sten,HCV cirrhosis HCC s/p liver transplant,Spinal myxoid chondrosarcoma,HCV cirrhosis cholangioca HCC s/p liver transpl,Bilateral hydronephrosis,Hip fracture,NASH cirrhosis s/p liver transplant,Ischemic colitis,Scoliosis,Cervical spondylotic myelopathy,ESRD PKD s/p renal transplant,Meningioma,Bladder carcinoma,Pancreatic cancer,HCC s/p IR hep art embolization,Sacral chordoma,Sigmoid diverticulitis,Fall,Degenerative lumbar kyphosis,NaN,NaN
1,6.0,11.0,12.0,13.0,18.0,21.0,24.0,29.0,34.0,35.0,37.0,48.0,49.0,50.0,51.0,52.0,56.0,63.0,68.0,69.0,72.0,74.0,81.0,84.0,87.0,90.0,97.0,100.0,103.0,130.0,131.0,133.0,139.0,68.0,153.0,160.0,167.0,168.0,169.0,171.0,173.0,179.0,187.0,188.0,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,175.0,NaN,142.0,NaN,54.0,157.0,NaN,NaN,NaN,NaN,182.0,NaN,143.0,NaN,83.0,NaN,NaN,NaN,NaN,161.0,104.0,NaN,NaN,NaN,NaN,NaN,180.0,188.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189.0,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,183.0,NaN,NaN,NaN,89.0,176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.0,NaN,NaN,NaN,NaN,NaN,120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
study_ids_medical = Xy_icu_subject.loc[Xy_icu_subject.med_surg == 1, 'study_id'].values
study_ids_surgical = Xy_icu_subject.loc[Xy_icu_subject.med_surg == 0, 'study_id'].values

In [16]:
diagnoses = {}
diagnoses['sepsis'] = list(diagnosis_medical['Sepsis'].dropna())
diagnoses['shock'] = list(diagnosis_medical['Shock'].dropna())
diagnoses['heart_failure'] = list(diagnosis_medical['Heart failure'].dropna())
diagnoses['encephalopathy'] = list(diagnosis_medical['Hepatic encephalopathy'].dropna()) + list(diagnosis_medical['Encephalopathy'].dropna()) + list(diagnosis_medical['AMS'].dropna())
diagnoses['anemia'] = list(diagnosis_medical['Anemia'].dropna())
diagnoses['hemorrhage'] = list(diagnosis_medical['Hemorrhage'].dropna()) + list(diagnosis_medical['GI hemorrhage'].dropna())
diagnoses['pneumonia'] = list(diagnosis_medical['Pneumonia'].dropna())
diagnoses['respiratory_failure'] = list(diagnosis_medical['Resp failure'].dropna())
diagnoses['aki'] = list(diagnosis_medical['AKI'].dropna())
diagnoses['pneumothorax'] = list(diagnosis_medical['Pneumothorax'].dropna()) + list(diagnosis_medical['Pulm edema'].dropna()) + list(diagnosis_medical['Hemothorax'].dropna()) + list(diagnosis_medical['Pl eff'].dropna())
diagnoses['copd'] = list(diagnosis_medical['COPD exacerbation'].dropna()) + list(diagnosis_medical['ILD'].dropna())
other_medical = set(study_ids_medical)
for diagnosis in diagnoses.keys():
    other_medical = other_medical - set(diagnoses[diagnosis])
diagnoses['other_medical'] = list(other_medical)

diagnoses['gi_hernia_ischemic'] = list(diagnosis_surgical['Gastric perf'].dropna()) + list(diagnosis_surgical['Incarcerated umb hernia'].dropna()) + list(diagnosis_surgical['Perf sigmoid colon'].dropna()) + list(diagnosis_surgical['Eso perf'].dropna()) + list(diagnosis_surgical['Sigmoid diverticulitis'].dropna()) + list(diagnosis_surgical['Ischemic colitis'].dropna())
diagnoses['cirrhosis_liver'] = list(diagnosis_surgical['HCV cirrhosis cholangioca HCC s/p liver transpl'].dropna()) + list(diagnosis_surgical['HCV cirrhosis HCC s/p liver transplant'].dropna()) + list(diagnosis_surgical['NASH cirrhosis s/p liver transplant'].dropna()) + list(diagnosis_surgical['Eso perf'].dropna()) + list(diagnosis_surgical['HCV/alc cirrhosis s/p liver transplant'].dropna())
other_surgical = set(study_ids_surgical)
for diagnosis in ['gi_hernia_ischemic', 'cirrhosis_liver']:
    other_surgical = other_surgical - set(diagnoses[diagnosis])
diagnoses['other_surgical'] = list(other_surgical)

In [17]:
Xy_icu_subject.iloc[8:14]

,inclusion_subject,study_id,mrn,age,bmi,sex,osa_diagnosis,icu_mortality,3_month_mortality,icu_los,hospital_los,chf,copd,med_surg,CCI,CCI_weighted,Belt_Length,day_no,hr_mean,hr_std,hr_median,hr_q25,hr_q75,hr_sda,hr_asd,spo2_mean,spo2_std,spo2_median,spo2_q25,spo2_q75,spo2_sda,spo2_asd,spo2_airgo_mean,spo2_airgo_std,spo2_airgo_median,spo2_airgo_q25,spo2_airgo_q75,spo2_airgo_sda,spo2_airgo_asd,spo2_clean_mean,spo2_clean_std,spo2_clean_median,spo2_clean_q25,spo2_clean_q75,spo2_clean_sda,spo2_clean_asd,spo2_airgo_clean_mean,spo2_airgo_clean_std,spo2_airgo_clean_median,spo2_airgo_clean_q25,spo2_airgo_clean_q75,spo2_airgo_clean_sda,spo2_airgo_clean_asd,edw_bp_systolic_mean,edw_bp_systolic_std,edw_bp_systolic_median,edw_bp_systolic_q25,edw_bp_systolic_q75,edw_bp_diastolic_mean,edw_bp_diastolic_std,edw_bp_diastolic_median,edw_bp_diastolic_q25,edw_bp_diastolic_q75,edw_bp_map_mean,edw_bp_map_std,edw_bp_map_median,edw_bp_map_q25,edw_bp_map_q75,cpc_hfc_lfc_ratio_mean,cpc_hfc_lfc_ratio_std,cpc_hfc_lfc_ratio_median,cpc_hfc_lfc_ratio_q25,cpc_hfc_lfc_ratio_q75,cpc_hfc_mean,cpc_hfc_std,cpc_hfc_median,cpc_hfc_q25,cpc_hfc_q75,cpc_hfc_sum,cpc_lfc_mean,cpc_lfc_std,cpc_lfc_median,cpc_lfc_q25,cpc_lfc_q75,cpc_lfc_sum,hrv_nn_q25,hrv_nn_q75,hrv_nn_sda,hrv_nn_asd,hco3_arterial_mean,hco3_arterial_min,hco3_arterial_max,pco2_arterial_mean,pco2_arterial_min,pco2_arterial_max,po2_arterial_mean,po2_arterial_min,po2_arterial_max,ph_arterial_mean,ph_arterial_min,ph_arterial_max,oxygen_flow_rate_max,sofa_score_mean,sofa_score_min,sofa_score_max,ahi_va_a3,ahi_va_a3_ss,ahi_vb_a3,ahi_vb_a3_ss,ahi_ro_a3,ahi_ro_a3_ss,ahi_rsr_a3,ahi_rsr_a3_ss,ahi_expert,ahi_va_a3_ss_aswti,ahi_vb_a3_ss_aswti,ahi_ro_a3_ss_aswti,ahi_rsr_a3_ss_aswti,hypoxic_burden_va_a3,hypoxic_burden_va_a3_ss,hypoxic_burden_vb_a3,hypoxic_burden_vb_a3_ss,hypoxic_burden_ro_a3,hypoxic_burden_ro_a3_ss,hypoxic_burden_rsr_a3,hypoxic_burden_rsr_a3_ss,hypoxic_burden_expert,hypoxic_burden_va_a3_ss_aswti,hypoxic_burden_vb_a3_ss_aswti,hypoxic_burden_ro_a3_ss_aswti,hypoxic_burden_rsr_a3_ss_aswti,hypoxia_LDI,hypoxia_SDI,hypoxia_TDI,hypoxia_pu90,hypoxia_ss_LDI,hypoxia_ss_SDI,hypoxia_ss_TDI,hypoxia_ss_pu90,hypoxia_ss_aswti_LDI,hypoxia_ss_aswti_SDI,hypoxia_ss_aswti_TDI,hypoxia_ss_aswti_pu90,self_similarity_sleep,self_similarity_sleep_q50,self_similarity_sleep_q75,self_similarity_apnea,self_similarity_apnea_q50,self_similarity_apnea_q75,opioids_sum,...,hours_data_ecg_nn_agreement_relaxed,hours_sleep_ecg_nn_agreement_relaxed,perc_W_ecg_nn_agreement_relaxed,perc_S_ecg_nn_agreement_relaxed,perc_R_ecg_nn_agreement_relaxed,perc_N1_ecg_nn_agreement_relaxed,perc_N2_ecg_nn_agreement_relaxed,perc_N3_ecg_nn_agreement_relaxed,sfi_ecg_nn_agreement_relaxed,sfi_w_ecg_nn_agreement_relaxed,arousali_ecg_nn_agreement_relaxed,hours_data_ecg_nn_disagreement_relaxed,hours_sleep_ecg_nn_disagreement_relaxed,perc_W_ecg_nn_disagreement_relaxed,perc_S_ecg_nn_disagreement_relaxed,perc_R_ecg_nn_disagreement_relaxed,perc_N1_ecg_nn_disagreement_relaxed,perc_N2_ecg_nn_disagreement_relaxed,perc_N3_ecg_nn_disagreement_relaxed,sfi_ecg_nn_disagreement_relaxed,sfi_w_ecg_nn_disagreement_relaxed,arousali_ecg_nn_disagreement_relaxed,hours_data_amendsumeffort_all,hours_sleep_amendsumeffort_all,perc_W_amendsumeffort_all,perc_S_amendsumeffort_all,perc_R_amendsumeffort_all,perc_N1_amendsumeffort_all,perc_N2_amendsumeffort_all,perc_N3_amendsumeffort_all,sfi_amendsumeffort_all,sfi_w_amendsumeffort_all,arousali_amendsumeffort_all,hours_data_amendsumeffort_agreement,hours_sleep_amendsumeffort_agreement,perc_W_amendsumeffort_agreement,perc_S_amendsumeffort_agreement,perc_R_amendsumeffort_agreement,perc_N1_amendsumeffort_agreement,perc_N2_amendsumeffort_agreement,perc_N3_amendsumeffort_agreement,sfi_amendsumeffort_agreement,sfi_w_amendsumeffort_agreement,arousali_amendsumeffort_agreement,hours_data_amendsumeffort_disagreement,hours_sleep_amendsumeffort_disagreement,perc_W_amendsumeffort_disagreement,perc_S_amendsumeffort_disagreement,perc_R_amendsumeffort_disagreement,perc_N1_amendsumeffort_disagreement,perc_N2_amendsumeffort_disagreement,perc_N3_amendsumeffort_disagreement,sfi_amendsumeffort_disagreement,sfi_w_amendsumeffort_disagreement,arousali_amendsumeffort_disagreement,hours_data_amendsumeffort_agreement_relaxed,hours_sleep_amendsumeffort_agreement_relaxed,perc_W_amendsumeffort_agreement_relaxed,perc_S_amendsumeffort_agreement_relaxed,perc_R_amendsumeffort_agreement_relaxed,perc_N1_amendsumeffort_agreement_relaxed,perc_N2_amendsumeffort_agreement_relaxed,perc_N3_amendsumeffort_agreement_relaxed,sfi_amendsumeffort_agreement_relaxed,sfi_w_amendsumeffort_agreement_relaxed,arousali_amendsumeffort_agreement_relaxed,hours_data_amendsumeffort_disagreement_relaxed,hours_sleep_amendsumeffort_disagreement_relaxed,perc_W_amendsumeffort_disagreement_relaxed,perc_S_amendsumeffort_disagreement_relaxed,perc_R_amendsumeffort_disagreement_relaxed,perc_N1_amendsumeffort_disagreement_relaxed,perc_N2_amendsumeffort_disagreement_relaxed,perc_N3_amendsumeffort_disagreement_relaxed,sfi_amendsumeffort_disagreement_relaxed,sfi_w_amendsumeffort_disagreement_relaxed,arousali_amendsumeffort_disagreement_relaxed,hours_data_expert_all,hours_sleep_expert_all,perc_W_expert_all,perc_S_expert_all,perc_R_expert_all,perc_N1_expert_all,perc_N2_expert_all,perc_N3_expert_all,sfi_expert_all,sfi_w_expert_all,arousali_expert_all,hours_data_expert_agreement,hours_sleep_expert_agreement,perc_W_expert_agreement,perc_S_expert_agreement,perc_R_expert_agreement,perc_N1_expert_agreement,perc_N2_expert_agreement,perc_N3_expert_agreement,sfi_expert_agreement,sfi_w_expert_agreement,arousali_expert_agreement,hours_data_expert_disagreement,hours_sleep_expert_disagreement,perc_W_expert_disagreement,perc_S_expert_disagreement,perc_R_expert_disagreement,perc_N1_expert_disagreement,perc_N2_expert_disagreement,perc_N3_expert_disagreement,sfi_expert_disagreement,sfi_w_expert_disagreement,arousali_expert_disagreement,hours_data_expert_agreement_relaxed,hours_sleep_expert_agreement_relaxed,perc_W_expert_agreement_relaxed,perc_S_expert_agreement_relaxed,perc_R_expert_agreement_relaxed,perc_N1_expert_agreement_relaxed,perc_N2_expert_agreement_relaxed,perc_N3_expert_agreement_relaxed,sfi_expert_agreement_relaxed,sfi_w_expert_agreement_relaxed,arousali_expert_agreement_relaxed,hours_data_expert_disagreement_relaxed,hours_sleep_expert_disagreement_relaxed,perc_W_expert_disagreement_relaxed,perc_S_expert_disagreement_relaxed,perc_R_expert_disagreement_relaxed,perc_N1_expert_disagreement_relaxed,perc_N2_expert_disagreement_relaxed,perc_N3_expert_disagreement_relaxed,sfi_expert_disagreement_relaxed,sfi_w_expert_disagreement_relaxed,arousali_expert_disagreement_relaxed,perc_N2N3_amendsumeffort_all,perc_N2N3_ecg_nn_all,perc_N2N3_amendsumeffort_agreement_relaxed,perc_N2N3_ecg_nn_agreement_relaxed,perc_N2N3_amendsumeffort_disagreement_relaxed,perc_N2N3_ecg_nn_disagreement_relaxed,perc_N2N3_amendsumeffort_agreement,perc_N2N3_ecg_nn_agreement,perc_N2N3_amendsumeffort_disagreement,perc_N2N3_ecg_nn_disagreement,hours_discordant_amendsumeffort_agreement_relaxed,discordant_proportion_amendsumeffort_agreement_relaxed,hours_discordant_ecg_nn_agreement_relaxed,discordant_proportion_ecg_nn_agreement_relaxed,hours_discordant_amendsumeffort_agreement,discordant_proportion_amendsumeffort_agreement,hours_discordant_ecg_nn_agreement,discordant_proportion_ecg_nn_agreement
8,1.0,18.0,6407422.0,66.0,26.23,0.0,0.0,0.0,0.0,4.0,6.0,0.0,1.0,0.0,0.0,0.0,100.0,2.5,70.402889,7.062772,71.000000,64.500000,75.343750,6.832766,1.278050,97.020401,2.709020,97.500000,95.250000,99.500000,2.539540,0.716005,97.037487,2.918518,98.000,95.000000,99.500000,2.774604,0.646593,97.022522,2.702738,97.500000,95.250000,99.500000,2.538409,0.706859,97.039608,2.912236,98.000,95.000000,99.500000,2.773473,0.637446,82.000000,NaN,82.000000,82.000000,82.000000,46.000000,NaN,46.000000,46.000000,46.000000,58.000000,NaN,58.000000,58.000000,58.000000,-1.152934,2.386446,-1.780735,-2.972577,0.700573,0.333680,0.383199,0.192855,0.039484,0.516310,275361.191406,3.823225,7.715719,0.674776,0.008800,4.293077,2.801289e+06,0.772917,0.916667,0.099862,0.083154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.500000,0.583333,0.0,1.500000,8.186645,2.584603,3.840465,0.306122,8.186645,2.584603,4.132128,0.000000,NaN,2.538221,0.259740,2.538221,0.000000,1.409500e+02,0.000000,0.0,0.0,1.409500e+02,0.000000,6.265000e+01,0.0,NaN,0.000000,0.000000,0.000000,0.000000,3.112269,2.207494,5.319762,0.014785,0.759493,1.065615,1.825107,0.000000,0.759493,1.019233,1.778725,0.000000,0.000004,0.034119,0.034119,0.000000,0.003326,0.003326,23.351110,...,15.641668,2.866668,0.815770,0.184230,0.016746,0.302894,0.216250,0.464110,4.800000,3.050000,7.250000,2.970834,2.312501,0.211386,0.788613,0.143116,0.000000,0.220436,0.636447,1.600000,1.600000,1.600000,18.612501,3.562501,0.791672,0.208328,0.008274,0.365051,0.618400,0.008274,7.000000,2.550000,5.800000,13.120834,0.766668,0.955518,0.044482,0.291664,0.385657,0.322674,0.000000,6.400000,5.350000,15.350000,5.491668,2.795834,0.497424,0.502575,0.000000,0.398694,0.592789,0.008516,6.90,1.850000,3.450000,15.641668,2.595834,0.815792,0.184208,0.013619,0.398811,0.587570,0.000000,4.650000,1.550000,4.600000,2.970834,0.966668,0.688285,0.311715,0.000000,0.266064,0.712851,0.021084,3.050000,1.450000,4.700000,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.626674,0.738500,0.587570,0.680359,0.733935,0.856884,0.322674,0.322674,0.601305,0.744091,0.966667,0.272606,2.312500,0.462552,2.795833,0.786741,4.412500,0.863205
9,1.0,21.0,1886786.0,66.0,30.53,1.0,1.0,0.0,0.0,3.0,10.0,0.0,0.0,0.0,3.0,5.0,90.0,3.5,76.767193,9.172382,74.593750,70.000000,81.250000,7.993925,3.521532,98.531441,1.859951,99.000000,98.000000,99.937500,1.286847,0.940097,98.527405,1.862262,99.000,98.000000,99.937500,1.287021,0.942103,98.535740,1.839659,99.000000,98.000000,99.937500,1.217442,0.914851,98.531734,1.841882,99.000,98.000000,99.937500,1.217229,0.916667,123.840000,11.712867,122.500000,118.000000,129.500000,64.304445,3.899820,64.500000,61.000000,67.000000,84.149628,5.858677,83.833332,80.333332,87.166664,-1.763094,0.884199,-1.799901,-2.343856,-1.217068,0.147441,0.284108,0.000000,0.000000,0.189392,96107.865234,1.030985,2.355882,0.000000,0.000000,1.014725,6.745757e+05,0.706250,0.845833,0.087197,0.219716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.250000,0.0,0.500000,13.341355,28.493789,13.341355,28.493789,13.341355,28.493789,8.611079,25.776398,NaN,28.734508,28.734508,28.734508,25.994781,8.496500e+02,3.300000,0.0,0.0,8.598500e+02,3.300000,9.341000e+02,16.4,NaN,33.400000,33.400000,33.250000,54.100000,4.685411,3.790267,8.475678,0.006521,10.745267,9.114833,19.860100,0.041461,11.311045,8.799663,20.110708,0.041789,0.000009,0.001374,0.001374,0.000769,0.001374,0.001374,0.000000,...,14.862501,3.654168,0.734264,0.265736,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,14.250000,1.195834,0.037501,0.933822,0.066176,0.000000,0.000000,0.499993,0.000000,0.000000,0.000000,0.000000,16.058334,3.233334,0.774458,0.225542,0.009363,0.633128,0.317234,0.040275,2.400000,1.350000,4.000000,9.483334,0.087501,0.994342,0.005657,0.000000,0.499997,0.000000,0.000000,0.000000,0.000000,11.450000,6.575001,3.145834,0.520541,0.479459,0.009363,0.622095,0.326533,0.042008,2.20,0.450000,0.700000,14.862501,2.075001,0.830612,0.169387,0.000000,0.927586,0.072414,0.000000,0.600000,0.200000,5.900000,1.195834,1.158334,0.066176,0.933822,0.042373,0.000000,0.864019,0.093607,1.000000,1.000000,1.000000,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.357509,0.015734,0.072414,0.000000,0.957626,0.499993,0.000000,0.000000,0.368542,0.015734,1.158333,0.325614,0.037500,0.015734,3.145833,0.979371,3.604167,0.982500
10,1.0,24.0,1737814.0,55.0,26.41,1.0,0.0,0.0,0.0,4.0,5.0,0.0,1.0,0.0,4.0,6.0,81.0,2.5,82.409367,11.080640,81.843750,74.500000,89.156250,9.608364,5.047350,94.989864,2.419292,95.500000,93.500000,96.500000,2.031941,1.048410,94.128620,2.255726,94.500,92.500000,95.500000,1.767825,1.086975,94.989864,2.419292,95.500000,93.500000,96.500000,2.031941,1.048410,94.128620,2.255726,94.500,92.500000,95.500000,1.767825,1.086975,103.375000,7.783083,104.000000,101.250000,106.125000,52.125000,1.103553,51.750000,51.625000,52.250000,69.208336,2.753694,69.166668,68.333334,70.041668,-4.486033,1.651561,-4.471238,-5.725736,-3.271956,0.035268,0.063542,0.011872,0.003030,0.040287,28660.608521,1.946177,3.388361,0.809641,0.285832,2.282463,1.372386e+06,0.652083,0.775000,0.082887,0.050513,28.0,28.0,28.0,40.0,40.0,40.0,107.0,107.0,107.0,7.46,7.46,7.46,0.000000,3.750000,2.0,5.500000,16.745174,21.732283,16.256389,21.732283,16.745174,21.732283,14.881404,24.678597,NaN,21.732283,21.732283,21.732283,24.678597,6.961000e+02,48.750000,0.0,0.0,6.961000e+02,48.750000,6.429500e+02,33.5,NaN,32.550000,32.550000,32.550000,29.400000,9.268193,8.667927,17.936120,0.024420,15.702199,8.795980,24.498179,0.015785,15.702199,8.795980,24.498179,0.015785,0.000001,0.018433,0.026672,0.000589,0.026672,0.052460,5.000000,...,13.929168,7.675001,0.372053,0.627947,0.000000,0.978054,0.021945,0.000000,1.200000,0.500000,10.700000,3.837501,3.566668,0.076636,0.923363,0.850308,0.000000,0.126543,0.023148,0.700000,0.700000,0.700000,17.766668,8.583334,0.506762,0.493238,0.000000,0.825289,0.174711,0.000000,5.100000,0.650000,7.350000,6.562501,2.941668,0.448957,0.551043,0.000000,0.991749,0.008251,0.000000,0.400000,0.200000,5.200000,11.204168,5.641668,0.512900,0.487100,0.000000,0.709826,0.290174,0.000000,6.60,0.850000,4.900000,13.929168,6.404168,0.512362,0.487638,0.000000,0.854042,0.145958,0.000000,3.250000,0.500000,8.650000,3.837501,2.179168,0.458699,0.541300,0.000000,0.728512,0.271487,0.000000,8.050000,1.600000,4.750000,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.174711,0.057412,0.145958,0.021945,0.271487,0.149691,0.008251,0.008251,0.290174,0.074653,2.179167,0.243584,3.566667,0.312560,5.641667,0.639568,8.300000,0.738567
11,1.0,25.0,5503616.0,68.0,20.53,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,1.0,1.0,2.0,77.0,3.0,88.525294,4.142526,88.375000,85.958333,91.250000,3.515897,1.572411,95.494850,2.317989,95.625000,94.270833,97.333333,2.066307,0.783072,95.170944,2.148157,95.625,93.937500,96.666667,1.877190,0.801542,95.494850,2.317989,95.625000,94.270833,97.333333,2.066307,0.783072,95.170944,2.148157,95.625,93.937500,96.666667,1.877190,0.801542,135.606753,16.052401,136.000000,126.750000,144.833333,69.635159,10.028088,68.833333,62.000000,77.083333,91.625694,10.241249,92.000003,84.388888,98.472223,-1.820059,1.037566,-1.790043,-2.467853,-1.109518,0.045908,0.076148,0.016866,0.005956,0.063837,31235.936849,0.477391,1.355538,0.093779,0.012586,0.392405,3.427791e+05,0.515278,0.804167,0.059658,0.251077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.055556,0.0,2.000000,9.232939,14.491634,9.232939,14.491634,7.934091,14.015444,3.374828,0.476190,NaN,14.491634,14.491634,14.015444,0.476190,9.681901e+07,0.000000,0.0,0.0,5.177258e+07,0.000000,9.695138e+07,0.0,NaN,0.000000,0.000000,0.000000,0.000000,1.890292,3.667792,5.558084,0.006946,1.904760,0.952380,2.857140,0.013527,1.904760,0.952380,2.857140,0.013527,0.000003,0.001355,0.008188,0.003788,0.006041,0.066706,0.000000,...,12.916668,2.683334,0.811132,0.188867,0.000000,0.959983,0.002720,0.037296,0.333333,0.200000,20.066667,7.058334,2.319445,0.679327,0.320673,0.001601,0.344918,0.016006,0.304122,0.300000,0.233333,40.400000,19.975001,8.438890,0.517069,0.482931,0.204807,0.396335,0.354572,0.044286,4.566667,1.100000,3.800000,8.086112,0.352779,0.937390,0.062609,0.000000,0.956706,0.000000,0.043290,0.533333,0.533333,9.333333,11.888890,8.086112,0.255194,0.744806,0.211380,0.369707,0.377958,0.040955,4.40,0.800000,1.233333,12.916668,3.405557,0.669418,0.330582,0.000000,0.833913,0.157937,0.008150,1.766667,0.866667,7.400000,7.058334,5.033334,0.279954,0.720046,0.353580,0.170264,0.384430,0.091726,0.866667,0.566667,0.866667,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.398858,0.178001,0.166087,0.040016,0.476156,0.320128,0.043290,0.043290,0.418913,0.184428,5.033333,0.532760,2.319444,0.172750,8.086111,0.939736,4.650000,0.642139
12,1.0,29.0,6545068.0,69.0,22.23,1.0,0.0,0.0,0.0,6.0,8.0,0.0,0.0,0.0,1.0,1.0,74.0,2.5,73.806778,9.333688,73.500000,66.500000,80.156250,8.498710,3.444667,94.633160,1.466744,95.000000,93.500000,95.906250,1.265869,0.629065,94.931232,1.469702,95.000,94.000000,95.906250,1.279558,0.610144,94.633160,1.466744,95.000000,93.500000,95.906250,1.265869,0.629065,94.931232,1.469702,95.000,94.000000,95.906250,1.279558,0.610144,163.500000,0.707107,163.500000,163.250000,163.750000,82.000000,7.071068,82.000000,79.500000,84.500000,109.166664,4.949748,109.166664,107.416664,110.916664,-1.696920,1.344463,-1.678762,-2.567568,-0.835823,0.429764,0.781333,0.112291,0.027527,0.486268,312186.023438,2.278733,3.886164,0.610521,0.102442,2.782274,1.693453e+06,0.727083,0.881250,0.099991,0.074332,19.0,19.0,19.0,23.0,23.0,23.0,133.0,133.0,133.0,7.54,7.54,7.54,1.500000,1.229167,1.0,2.000000,10.157919,5.173247,9.991254,5.173247,10.157919,5.173247,0.960211,0.821918,NaN,4.877726,4.877726,4.877726,0.674157,1.727500e+02,0.000000,0.0,0.0,1.727500e+02,0.000000,1.108000e+02,0.0,NaN,0.450000,0.450000,0.450000,0.000000,0.934609,1.117570,2.052179,0.002092,7.880690,0.000000,7.880690,0.000000,7.732905,0.000000,7.732905,0.000000,0.000008,0.025326,0.028152,0.107143,0.078674,0.078674,3.333333,...,14.458334,5.366668,0.600293,0.399707,0.014118,0.710446,0.244848,0.030588,3.550000,1.100000,14.650000,4.283334,3.791668,0.159601,0.840398,0.391068,0.024194,0.308254,0.276484,2.600000,2.600000,2.600000,18.741668,4.625001,0.766795,0.233205,0.029855,0.655642,0.300323,0.014180,2.850000,0.750000,6.000000,9.712501,1.283334,0.875960,0.124039,0.047809,0.578457,0.373733,0.000000,2.250000,1.550000,7.250000,9.029168,3.341668,0.628161,0.371839,0.021097,0.687042,0.271325,0.020536,2.75,1.050000,4.500000,14.458334,3.008334,0.792604,0.207396,0.022770,0.696574,0.270218,0.010436,2.050000,0.550000,6.700000,4.283334,1.616668,0.525740,0.474260,0.043066,0.579496,0.356311,0.021127,2.200000,2.000000,5.100000,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000001,0.000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.314503,0.468928,0.280655,0.275436,0.377438,0.584738,0.373733,0.373733,0.291861,0.431024,1.616667,0.349005,3.791667,0.413842,3.341667,0.749935,7.875000,0.859792

In [18]:
Xy_icu_subject.shape

(80, 6521)

In [19]:
for diagnosis in diagnoses.keys():
    print(f"{diagnosis:>20}: {len(diagnoses[diagnosis])}")
    
    Xy_icu[diagnosis] = 0
    Xy_icu_subject[diagnosis] = 0
    
    for study_id_diagnosis_tmp in diagnoses[diagnosis]:
        Xy_icu.loc[Xy_icu.study_id == study_id_diagnosis_tmp, diagnosis] = 1
        Xy_icu_subject.loc[Xy_icu_subject.study_id == study_id_diagnosis_tmp, diagnosis] = 1

              sepsis: 19
               shock: 30
       heart_failure: 10
      encephalopathy: 14
              anemia: 20
          hemorrhage: 10
           pneumonia: 15
 respiratory_failure: 21
                 aki: 33
        pneumothorax: 13
                copd: 7
       other_medical: 3
  gi_hernia_ischemic: 8
     cirrhosis_liver: 7
      other_surgical: 43

In [20]:
variables_template

['hours_sleep_MODALITY_all',
 'hours_sleep_MODALITY_agreement_relaxed',
 'hours_discordant_MODALITY_agreement_relaxed',
 'discordant_proportion_MODALITY_agreement_relaxed',
 'perc_S_MODALITY_AGREEMENT',
 'perc_R_MODALITY_AGREEMENT',
 'perc_N1_MODALITY_AGREEMENT',
 'perc_N2_MODALITY_AGREEMENT',
 'perc_N3_MODALITY_AGREEMENT',
 'perc_N2N3_MODALITY_AGREEMENT',
 'sfi_MODALITY_AGREEMENT',
 'arousali_MODALITY_AGREEMENT']

## start analysis

In [21]:
if 0: # V1 of parimala table (sheet 1)

    print(f"{diagnosis_tmp}: {diagnosis_df[diagnosis_tmp].sum()}")
    Xy_icu = Xy_icu.merge(diagnosis_df[diagnoses + ['study_id']])
    Xy_icu_subject = Xy_icu_subject.merge(diagnosis_df[diagnoses + ['study_id']])
    


modality = 'amendsumeffort'
modality = 'ecg_nn'

discordant_proportion = f'discordant_proportion_{modality}_agreement_relaxed'
print(discordant_proportion)

variables = [x.replace('MODALITY', modality).replace('AGREEMENT', agreement) for x in variables_template]
print(variables)

sleep_vars = variables

discordant_proportion_ecg_nn_agreement_relaxed
['hours_sleep_ecg_nn_all', 'hours_sleep_ecg_nn_agreement_relaxed', 'hours_discordant_ecg_nn_agreement_relaxed', 'discordant_proportion_ecg_nn_agreement_relaxed', 'perc_S_ecg_nn_all', 'perc_R_ecg_nn_all', 'perc_N1_ecg_nn_all', 'perc_N2_ecg_nn_all', 'perc_N3_ecg_nn_all', 'perc_N2N3_ecg_nn_all', 'sfi_ecg_nn_all', 'arousali_ecg_nn_all']

In [22]:
variables

['hours_sleep_ecg_nn_all',
 'hours_sleep_ecg_nn_agreement_relaxed',
 'hours_discordant_ecg_nn_agreement_relaxed',
 'discordant_proportion_ecg_nn_agreement_relaxed',
 'perc_S_ecg_nn_all',
 'perc_R_ecg_nn_all',
 'perc_N1_ecg_nn_all',
 'perc_N2_ecg_nn_all',
 'perc_N3_ecg_nn_all',
 'perc_N2N3_ecg_nn_all',
 'sfi_ecg_nn_all',
 'arousali_ecg_nn_all']

In [23]:
df_results = pd.DataFrame(index = sleep_vars)

values_groups = {}
for sleep_var in sleep_vars:
    values_groups[sleep_var] = []

dec = [1]*3 + [2]*7 + [1]*2

for diagnosis in diagnoses:

    df_results[diagnosis + '_median'] = np.nan
    df_results[diagnosis + '_iqr'] = np.nan

    Xy_icu_subject_group = Xy_icu_subject.query(f"{diagnosis} == 1")
    
    df_results.loc['N', diagnosis + '_median'] = Xy_icu_subject_group.shape[0]
    
    for i, sleep_var in enumerate(sleep_vars):
        df_results.loc[sleep_var, f"{diagnosis}_median"] = str(np.round(Xy_icu_subject_group[sleep_var].median(), dec[i]))
        df_results.loc[sleep_var, f"{diagnosis}_iqr"] = f"[{Xy_icu_subject_group[sleep_var].quantile(0.25).round(dec[i])}, {Xy_icu_subject_group[sleep_var].quantile(0.75).round(dec[i])}]"

    for i, sleep_var in enumerate(sleep_vars):

        values_0 = Xy_icu_subject.query(f"{diagnosis} == 0")[sleep_var].values
        values_1 = Xy_icu_subject.query(f"{diagnosis} == 1")[sleep_var].values

        if 0:
            df_results.loc[sleep_var, f"{diagnosis}_mwu"] = f"{mannwhitneyu(values_0, values_1)[0].round(1), mannwhitneyu(values_0, values_1)[1].round(4)}"

            if mannwhitneyu(values_0, values_1)[1].round(4) < 0.01:
                print('** ' + sleep_var + ' ' + diagnosis)
            elif mannwhitneyu(values_0, values_1)[1].round(4) < 0.05:
                print('* ' + sleep_var + ' ' + diagnosis)

        values_groups[sleep_var].append(values_1)
        
        
for sleep_var in sleep_vars:
    values_tmp = values_groups[sleep_var]
    assert len(values_tmp) == len(diagnoses), 'For each diagnosis group, there must be one list of values'
    # apply kruskal test:
    df_results.loc[sleep_var, f"kruskal"] = f"{np.round(kruskal(*values_tmp)[0], 1)}, {np.round(kruskal(*values_tmp)[1], 3)}"

In [24]:
df_results

,sepsis_median,sepsis_iqr,shock_median,shock_iqr,heart_failure_median,heart_failure_iqr,encephalopathy_median,encephalopathy_iqr,anemia_median,anemia_iqr,hemorrhage_median,hemorrhage_iqr,pneumonia_median,pneumonia_iqr,respiratory_failure_median,respiratory_failure_iqr,aki_median,aki_iqr,pneumothorax_median,pneumothorax_iqr,copd_median,copd_iqr,other_medical_median,other_medical_iqr,gi_hernia_ischemic_median,gi_hernia_ischemic_iqr,cirrhosis_liver_median,cirrhosis_liver_iqr,other_surgical_median,other_surgical_iqr,kruskal
hours_sleep_ecg_nn_all,6.2,"[4.4, 7.5]",6.0,"[3.2, 7.5]",6.7,"[1.3, 8.3]",7.4,"[5.0, 7.6]",5.9,"[4.4, 7.3]",7.3,"[4.7, 9.5]",6.1,"[4.9, 7.5]",5.5,"[3.6, 9.0]",6.6,"[4.6, 8.7]",6.9,"[6.0, 7.9]",7.8,"[5.5, 10.0]",6.4,"[6.4, 10.7]",7.0,"[5.0, 7.5]",4.8,"[3.9, 6.2]",6.8,"[4.9, 9.2]","7.7, 0.904"
hours_sleep_ecg_nn_agreement_relaxed,3.5,"[2.1, 4.1]",3.7,"[1.8, 4.7]",3.2,"[1.1, 5.0]",3.7,"[2.7, 4.1]",3.3,"[2.7, 4.5]",4.2,"[3.2, 6.4]",2.7,"[1.5, 3.8]",2.6,"[1.5, 4.3]",3.7,"[2.1, 5.2]",3.5,"[2.7, 4.4]",4.9,"[3.0, 6.4]",3.4,"[2.5, 3.9]",3.2,"[2.8, 3.7]",2.7,"[2.6, 3.3]",4.1,"[2.8, 5.7]","12.5, 0.565"
hours_discordant_ecg_nn_agreement_relaxed,2.8,"[1.0, 3.8]",1.7,"[0.6, 3.8]",2.0,"[0.3, 3.8]",2.3,"[0.6, 4.7]",2.3,"[1.3, 3.1]",3.2,"[0.5, 4.1]",3.1,"[2.3, 4.5]",2.3,"[0.8, 5.3]",2.8,"[0.6, 3.8]",3.6,"[1.5, 5.3]",2.6,"[1.3, 3.5]",4.8,"[3.4, 8.3]",3.7,"[2.6, 4.2]",1.7,"[1.2, 3.5]",2.3,"[1.1, 3.7]","8.0, 0.888"
discordant_proportion_ecg_nn_agreement_relaxed,0.38,"[0.17, 0.5]",0.31,"[0.14, 0.45]",0.43,"[0.08, 0.61]",0.54,"[0.17, 0.62]",0.36,"[0.2, 0.46]",0.32,"[0.12, 0.42]",0.49,"[0.28, 0.59]",0.51,"[0.25, 0.59]",0.35,"[0.12, 0.54]",0.53,"[0.41, 0.63]",0.36,"[0.35, 0.45]",0.75,"[0.53, 0.75]",0.5,"[0.45, 0.55]",0.54,"[0.31, 0.54]",0.34,"[0.18, 0.48]","16.6, 0.278"
perc_S_ecg_nn_all,0.42,"[0.22, 0.53]",0.37,"[0.25, 0.49]",0.41,"[0.07, 0.52]",0.45,"[0.25, 0.53]",0.32,"[0.27, 0.51]",0.42,"[0.39, 0.69]",0.37,"[0.25, 0.53]",0.37,"[0.25, 0.54]",0.43,"[0.32, 0.64]",0.42,"[0.38, 0.53]",0.49,"[0.32, 0.57]",0.62,"[0.54, 0.71]",0.39,"[0.34, 0.46]",0.32,"[0.26, 0.32]",0.5,"[0.3, 0.66]","10.8, 0.705"
perc_R_ecg_nn_all,0.04,"[0.0, 0.13]",0.04,"[0.0, 0.2]",0.04,"[0.01, 0.08]",0.01,"[0.0, 0.13]",0.0,"[0.0, 0.06]",0.34,"[0.04, 0.7]",0.07,"[0.0, 0.26]",0.1,"[0.0, 0.43]",0.06,"[0.0, 0.22]",0.19,"[0.08, 0.25]",0.05,"[0.02, 0.09]",0.04,"[0.02, 0.31]",0.11,"[0.03, 0.23]",0.34,"[0.3, 0.63]",0.12,"[0.02, 0.34]","18.4, 0.191"
perc_N1_ecg_nn_all,0.33,"[0.16, 0.82]",0.28,"[0.07, 0.77]",0.26,"[0.04, 0.36]",0.33,"[0.17, 0.82]",0.31,"[0.12, 0.78]",0.36,"[0.18, 0.6]",0.31,"[0.24, 0.81]",0.18,"[0.04, 0.31]",0.22,"[0.08, 0.46]",0.15,"[0.08, 0.28]",0.09,"[0.04, 0.15]",0.09,"[0.06, 0.19]",0.17,"[0.13, 0.25]",0.16,"[0.15, 0.19]",0.17,"[0.06, 0.41]","16.6, 0.279"
perc_N2_ecg_nn_all,0.01,"[0.0, 0.06]",0.05,"[0.0, 0.13]",0.01,"[0.0, 0.04]",0.04,"[0.02, 0.07]",0.03,"[0.01, 0.13]",0.03,"[0.0, 0.1]",0.06,"[0.01, 0.09]",0.02,"[0.0, 0.08]",0.02,"[0.0, 0.08]",0.03,"[0.01, 0.12]",0.03,"[0.01, 0.14]",0.01,"[0.01, 0.02]",0.05,"[0.02, 0.06]",0.14,"[0.01, 0.33]",0.11,"[0.01, 0.21]","15.7, 0.33"
perc_N3_ecg_nn_all,0.41,"[0.06, 0.6]",0.3,"[0.05, 0.51]",0.59,"[0.32, 0.89]",0.17,"[0.05, 0.48]",0.37,"[0.06, 0.72]",0.06,"[0.01, 0.18]",0.17,"[0.06, 0.41]",0.23,"[0.07, 0.58]",0.44,"[0.1, 0.59]",0.57,"[0.42, 0.62]",0.86,"[0.64, 0.91]",0.91,"[0.51, 0.91]",0.6,"[0.42, 0.68]",0.09,"[0.08, 0.12]",0.24,"[0.05, 0.55]","21.9, 0.081"
perc_N2N3_ecg_nn_all,0.46,"[0.15, 0.72]",0.3,"[0.07, 0.75]",0.63,"[0.36, 0.91]",0.18,"[0.08, 0.7]",0.54,"[0.15, 0.84]",0.1,"[0.05, 0.39]",0.3,"[0.15, 0.52]",0.31,"[0.18, 0.6]",0.5,"[0.11, 0.73]",0.62,"[0.49, 0.7]",0.87,"[0.77, 0.94]",0.91,"[0.52, 0.92]",0.7,"[0.54, 0.74]",0.43,"[0.22, 0.5]",0.45,"[0.18, 0.77]","18.4, 0.189"
sfi_ecg_nn_all,3.1,"[0.9, 4.4]",2.4,"[1.5, 3.4]",2.0,"[0.7, 3.4]",2.4,"[0.6, 2.8]",1.9,"[0.9, 3.0]",4.1,"[2.9, 4.9]",2.4,"[0.6, 3.5]",2.2,"[1.0, 2.8]",2.2,"[1.3, 3.0]",3.1,"[2.7, 4.1]",2.0,"[1.6, 4.1]",2.0,"[1.8, 2.1]",2.8,"[2.4, 4.2]",5.2,"[4.4, 5.6]",2.7,"[1.4, 4.1]","19.2, 0.158"
arousali_ecg_nn_all,7.9,"[4.1, 11.9]",7.0,"[2.6, 10.9]",6.4,"[2.1, 26.2]",4.8,"[3.5, 19.0]",5.8,"[3.0, 12.9]",6.4,"[3.9, 9.3]",5.8,"[4.8, 10.7]",4.1,"[2.0, 7.3]",4.4,"[3.2, 9.0]",4.4,"[3.6, 5.6]",3.2,"[1.4, 5.2]",3.0,"[2.3, 4.9]",4.1,"[3.6, 5.9]",4.7,"[4.6, 8.2]",4.3,"[2.1, 7.2]","11.6, 0.64"
N,13.000000,NaN,23.000000,NaN,8.000000,NaN,9.000000,NaN,15.000000,NaN,8.000000,NaN,13.000000,NaN,14.000000,NaN,24.000000,NaN,10.000000,NaN,6.000000,NaN,3.000000,NaN,7.000000,NaN,5.000000,NaN,43.000000,NaN,NaN

In [25]:
df_results.loc['perc_N2N3_ecg_nn_all', [x for x in df_results.columns if 'median' in x]].astype(float).sort_values()

hemorrhage_median             0.10
encephalopathy_median         0.18
shock_median                  0.30
pneumonia_median              0.30
respiratory_failure_median    0.31
cirrhosis_liver_median        0.43
other_surgical_median         0.45
sepsis_median                 0.46
aki_median                    0.50
anemia_median                 0.54
pneumothorax_median           0.62
heart_failure_median          0.63
gi_hernia_ischemic_median     0.70
copd_median                   0.87
other_medical_median          0.91
Name: perc_N2N3_ecg_nn_all, dtype: float64

In [26]:
df_results.loc['perc_N1_ecg_nn_all', [x for x in df_results.columns if 'median' in x]].astype(float).sort_values()

copd_median                   0.09
other_medical_median          0.09
pneumothorax_median           0.15
cirrhosis_liver_median        0.16
gi_hernia_ischemic_median     0.17
other_surgical_median         0.17
respiratory_failure_median    0.18
aki_median                    0.22
heart_failure_median          0.26
shock_median                  0.28
anemia_median                 0.31
pneumonia_median              0.31
sepsis_median                 0.33
encephalopathy_median         0.33
hemorrhage_median             0.36
Name: perc_N1_ecg_nn_all, dtype: float64

In [27]:
df_results.loc['perc_R_ecg_nn_all', [x for x in df_results.columns if 'median' in x]].astype(float).sort_values()

anemia_median                 0.00
encephalopathy_median         0.01
sepsis_median                 0.04
shock_median                  0.04
heart_failure_median          0.04
other_medical_median          0.04
copd_median                   0.05
aki_median                    0.06
pneumonia_median              0.07
respiratory_failure_median    0.10
gi_hernia_ischemic_median     0.11
other_surgical_median         0.12
pneumothorax_median           0.19
hemorrhage_median             0.34
cirrhosis_liver_median        0.34
Name: perc_R_ecg_nn_all, dtype: float64

In [28]:
df_results.loc['discordant_proportion_ecg_nn_agreement_relaxed', [x for x in df_results.columns if 'median' in x]].astype(float).sort_values()

shock_median                  0.31
hemorrhage_median             0.32
other_surgical_median         0.34
aki_median                    0.35
anemia_median                 0.36
copd_median                   0.36
sepsis_median                 0.38
heart_failure_median          0.43
pneumonia_median              0.49
gi_hernia_ischemic_median     0.50
respiratory_failure_median    0.51
pneumothorax_median           0.53
encephalopathy_median         0.54
cirrhosis_liver_median        0.54
other_medical_median          0.75
Name: discordant_proportion_ecg_nn_agreement_relaxed, dtype: float64

In [29]:
df_results.to_csv('sleep_statistics_diagnoses_groups.csv')
df_results.transpose().to_csv('sleep_statistics_diagnoses_groupsT.csv')

In [30]:
print(discordant_proportion)
df_results.loc[discordant_proportion]

discordant_proportion_ecg_nn_agreement_relaxed

sepsis_median                         0.38
sepsis_iqr                     [0.17, 0.5]
shock_median                          0.31
shock_iqr                     [0.14, 0.45]
heart_failure_median                  0.43
heart_failure_iqr             [0.08, 0.61]
encephalopathy_median                 0.54
encephalopathy_iqr            [0.17, 0.62]
anemia_median                         0.36
anemia_iqr                     [0.2, 0.46]
hemorrhage_median                     0.32
hemorrhage_iqr                [0.12, 0.42]
pneumonia_median                      0.49
pneumonia_iqr                 [0.28, 0.59]
respiratory_failure_median            0.51
respiratory_failure_iqr       [0.25, 0.59]
aki_median                            0.35
aki_iqr                       [0.12, 0.54]
pneumothorax_median                   0.53
pneumothorax_iqr              [0.41, 0.63]
copd_median                           0.36
copd_iqr                      [0.35, 0.45]
other_medical_median                  0.75
other_medical_iqr             [0.53, 0.75]
gi_hernia_ischemic_median              0.5
gi_hernia_ischemic_iqr        [0.45, 0.55]
cirrhosis_liver_median                0.54
cirrhosis_liver_iqr           [0.31, 0.54]
other_surgical_median                 0.34
other_surgical_iqr            [0.18, 0.48]
kruskal                        16.6, 0.278
Name: discordant_proportion_ecg_nn_agreement_relaxed, dtype: object

In [31]:
# df_results = pd.read_csv('/scr/wolfgang/Dropbox (Partners HealthCare)/SleepInICUandSleeplabPaper/Results/sleep_statistics_diagnoses_groups_A2.csv', index_col=0)

In [32]:
df_results

,sepsis_median,sepsis_iqr,shock_median,shock_iqr,heart_failure_median,heart_failure_iqr,encephalopathy_median,encephalopathy_iqr,anemia_median,anemia_iqr,hemorrhage_median,hemorrhage_iqr,pneumonia_median,pneumonia_iqr,respiratory_failure_median,respiratory_failure_iqr,aki_median,aki_iqr,pneumothorax_median,pneumothorax_iqr,copd_median,copd_iqr,other_medical_median,other_medical_iqr,gi_hernia_ischemic_median,gi_hernia_ischemic_iqr,cirrhosis_liver_median,cirrhosis_liver_iqr,other_surgical_median,other_surgical_iqr,kruskal
hours_sleep_ecg_nn_all,6.2,"[4.4, 7.5]",6.0,"[3.2, 7.5]",6.7,"[1.3, 8.3]",7.4,"[5.0, 7.6]",5.9,"[4.4, 7.3]",7.3,"[4.7, 9.5]",6.1,"[4.9, 7.5]",5.5,"[3.6, 9.0]",6.6,"[4.6, 8.7]",6.9,"[6.0, 7.9]",7.8,"[5.5, 10.0]",6.4,"[6.4, 10.7]",7.0,"[5.0, 7.5]",4.8,"[3.9, 6.2]",6.8,"[4.9, 9.2]","7.7, 0.904"
hours_sleep_ecg_nn_agreement_relaxed,3.5,"[2.1, 4.1]",3.7,"[1.8, 4.7]",3.2,"[1.1, 5.0]",3.7,"[2.7, 4.1]",3.3,"[2.7, 4.5]",4.2,"[3.2, 6.4]",2.7,"[1.5, 3.8]",2.6,"[1.5, 4.3]",3.7,"[2.1, 5.2]",3.5,"[2.7, 4.4]",4.9,"[3.0, 6.4]",3.4,"[2.5, 3.9]",3.2,"[2.8, 3.7]",2.7,"[2.6, 3.3]",4.1,"[2.8, 5.7]","12.5, 0.565"
hours_discordant_ecg_nn_agreement_relaxed,2.8,"[1.0, 3.8]",1.7,"[0.6, 3.8]",2.0,"[0.3, 3.8]",2.3,"[0.6, 4.7]",2.3,"[1.3, 3.1]",3.2,"[0.5, 4.1]",3.1,"[2.3, 4.5]",2.3,"[0.8, 5.3]",2.8,"[0.6, 3.8]",3.6,"[1.5, 5.3]",2.6,"[1.3, 3.5]",4.8,"[3.4, 8.3]",3.7,"[2.6, 4.2]",1.7,"[1.2, 3.5]",2.3,"[1.1, 3.7]","8.0, 0.888"
discordant_proportion_ecg_nn_agreement_relaxed,0.38,"[0.17, 0.5]",0.31,"[0.14, 0.45]",0.43,"[0.08, 0.61]",0.54,"[0.17, 0.62]",0.36,"[0.2, 0.46]",0.32,"[0.12, 0.42]",0.49,"[0.28, 0.59]",0.51,"[0.25, 0.59]",0.35,"[0.12, 0.54]",0.53,"[0.41, 0.63]",0.36,"[0.35, 0.45]",0.75,"[0.53, 0.75]",0.5,"[0.45, 0.55]",0.54,"[0.31, 0.54]",0.34,"[0.18, 0.48]","16.6, 0.278"
perc_S_ecg_nn_all,0.42,"[0.22, 0.53]",0.37,"[0.25, 0.49]",0.41,"[0.07, 0.52]",0.45,"[0.25, 0.53]",0.32,"[0.27, 0.51]",0.42,"[0.39, 0.69]",0.37,"[0.25, 0.53]",0.37,"[0.25, 0.54]",0.43,"[0.32, 0.64]",0.42,"[0.38, 0.53]",0.49,"[0.32, 0.57]",0.62,"[0.54, 0.71]",0.39,"[0.34, 0.46]",0.32,"[0.26, 0.32]",0.5,"[0.3, 0.66]","10.8, 0.705"
perc_R_ecg_nn_all,0.04,"[0.0, 0.13]",0.04,"[0.0, 0.2]",0.04,"[0.01, 0.08]",0.01,"[0.0, 0.13]",0.0,"[0.0, 0.06]",0.34,"[0.04, 0.7]",0.07,"[0.0, 0.26]",0.1,"[0.0, 0.43]",0.06,"[0.0, 0.22]",0.19,"[0.08, 0.25]",0.05,"[0.02, 0.09]",0.04,"[0.02, 0.31]",0.11,"[0.03, 0.23]",0.34,"[0.3, 0.63]",0.12,"[0.02, 0.34]","18.4, 0.191"
perc_N1_ecg_nn_all,0.33,"[0.16, 0.82]",0.28,"[0.07, 0.77]",0.26,"[0.04, 0.36]",0.33,"[0.17, 0.82]",0.31,"[0.12, 0.78]",0.36,"[0.18, 0.6]",0.31,"[0.24, 0.81]",0.18,"[0.04, 0.31]",0.22,"[0.08, 0.46]",0.15,"[0.08, 0.28]",0.09,"[0.04, 0.15]",0.09,"[0.06, 0.19]",0.17,"[0.13, 0.25]",0.16,"[0.15, 0.19]",0.17,"[0.06, 0.41]","16.6, 0.279"
perc_N2_ecg_nn_all,0.01,"[0.0, 0.06]",0.05,"[0.0, 0.13]",0.01,"[0.0, 0.04]",0.04,"[0.02, 0.07]",0.03,"[0.01, 0.13]",0.03,"[0.0, 0.1]",0.06,"[0.01, 0.09]",0.02,"[0.0, 0.08]",0.02,"[0.0, 0.08]",0.03,"[0.01, 0.12]",0.03,"[0.01, 0.14]",0.01,"[0.01, 0.02]",0.05,"[0.02, 0.06]",0.14,"[0.01, 0.33]",0.11,"[0.01, 0.21]","15.7, 0.33"
perc_N3_ecg_nn_all,0.41,"[0.06, 0.6]",0.3,"[0.05, 0.51]",0.59,"[0.32, 0.89]",0.17,"[0.05, 0.48]",0.37,"[0.06, 0.72]",0.06,"[0.01, 0.18]",0.17,"[0.06, 0.41]",0.23,"[0.07, 0.58]",0.44,"[0.1, 0.59]",0.57,"[0.42, 0.62]",0.86,"[0.64, 0.91]",0.91,"[0.51, 0.91]",0.6,"[0.42, 0.68]",0.09,"[0.08, 0.12]",0.24,"[0.05, 0.55]","21.9, 0.081"
perc_N2N3_ecg_nn_all,0.46,"[0.15, 0.72]",0.3,"[0.07, 0.75]",0.63,"[0.36, 0.91]",0.18,"[0.08, 0.7]",0.54,"[0.15, 0.84]",0.1,"[0.05, 0.39]",0.3,"[0.15, 0.52]",0.31,"[0.18, 0.6]",0.5,"[0.11, 0.73]",0.62,"[0.49, 0.7]",0.87,"[0.77, 0.94]",0.91,"[0.52, 0.92]",0.7,"[0.54, 0.74]",0.43,"[0.22, 0.5]",0.45,"[0.18, 0.77]","18.4, 0.189"
sfi_ecg_nn_all,3.1,"[0.9, 4.4]",2.4,"[1.5, 3.4]",2.0,"[0.7, 3.4]",2.4,"[0.6, 2.8]",1.9,"[0.9, 3.0]",4.1,"[2.9, 4.9]",2.4,"[0.6, 3.5]",2.2,"[1.0, 2.8]",2.2,"[1.3, 3.0]",3.1,"[2.7, 4.1]",2.0,"[1.6, 4.1]",2.0,"[1.8, 2.1]",2.8,"[2.4, 4.2]",5.2,"[4.4, 5.6]",2.7,"[1.4, 4.1]","19.2, 0.158"
arousali_ecg_nn_all,7.9,"[4.1, 11.9]",7.0,"[2.6, 10.9]",6.4,"[2.1, 26.2]",4.8,"[3.5, 19.0]",5.8,"[3.0, 12.9]",6.4,"[3.9, 9.3]",5.8,"[4.8, 10.7]",4.1,"[2.0, 7.3]",4.4,"[3.2, 9.0]",4.4,"[3.6, 5.6]",3.2,"[1.4, 5.2]",3.0,"[2.3, 4.9]",4.1,"[3.6, 5.9]",4.7,"[4.6, 8.2]",4.3,"[2.1, 7.2]","11.6, 0.64"
N,13.000000,NaN,23.000000,NaN,8.000000,NaN,9.000000,NaN,15.000000,NaN,8.000000,NaN,13.000000,NaN,14.000000,NaN,24.000000,NaN,10.000000,NaN,6.000000,NaN,3.000000,NaN,7.000000,NaN,5.000000,NaN,43.000000,NaN,NaN

In [33]:
%matplotlib widget
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
def get_variable_values(variable):

    list_median = []
    list_iqr = []
    list_n = []
    
    for diagnosis in diagnoses.keys():
        tmp_median = float(df_results.loc[variable, diagnosis + '_median'])
        tmp_iqr = df_results.loc[variable, diagnosis + '_iqr']
        tmp_q25 = float(tmp_iqr.split(',')[0].replace('[', ''))
        tmp_q75 = float(tmp_iqr.split(',')[1].replace(']', ''))

        list_median.append(tmp_median)
        list_iqr.append(np.array([tmp_median - tmp_q25, tmp_q75 - tmp_median]))
        list_n.append(df_results.loc['N', diagnosis + '_median'] )
        
    list_iqr = np.array(list_iqr).transpose()
    
    return list_median, list_iqr, list_n

In [35]:
len(diagnoses.keys())

15

In [36]:
y_labels = ['Total Sleep (h)', 'Concordant S. (h)', 'Discordant S. (h)', 'Discordant S. (%)', 'Sleep (%)', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2 (%)', 'Stage N3 (%)', 'Stage N2+N3 (%)', 'SFI', 'Wake Trans./h']
# y_labels_short = ['TS', 'CS', 'DS', 'DS%', 'S', 'R', 'N1', 'N2', 'N3', 'N2+N3', 'SFI', 'WT']
y_labels_short = ['Total\nSleep (h)', 'Concor.\nSleep(h)', 'Discor.\nSleep (h)', 'Discor.\nSleep (%)', 'Sleep(%)', 'R (%)', 'N1 (%)', 'N2 (%)', 'N3 (%)', 'N2+N3\n(%)', 'SFI', 'Wake\nTrans./h']

In [37]:
df_results.index[:-1]

vars_to_plot = ['hours_sleep_ecg_nn_all', 'hours_sleep_ecg_nn_agreement_relaxed',
       'hours_discordant_ecg_nn_agreement_relaxed',
       'discordant_proportion_ecg_nn_agreement_relaxed', 'perc_S_ecg_nn_all',
       'perc_R_ecg_nn_all', 'perc_N1_ecg_nn_all', 'perc_N2N3_ecg_nn_all', 'sfi_ecg_nn_all',
       'arousali_ecg_nn_all']

y_labels = ['Total Sleep (h)', 'Concordant S. (h)', 'Discordant S. (h)', 'Discordant S. (%)', 'Sleep (%)', 'Stage R (%)', 'Stage N1 (%)', 'Stage N2+N3 (%)', 'SFI', 'Wake Trans./h']
# y_labels_short = ['TS', 'CS', 'DS', 'DS%', 'S', 'R', 'N1', 'N2', 'N3', 'N2+N3', 'SFI', 'WT']
y_labels_short = ['Total\nSleep (h)', 'Concor.\nSleep(h)', 'Discor.\nSleep (h)', 'Discor.\nSleep (%)', 'Sleep(%)', 'R (%)', 'N1 (%)', 'N2+N3\n(%)', 'SFI', 'Wake\nTrans./h']

In [38]:
list_median_DS, list_iqr_DS, list_n = get_variable_values('discordant_proportion_ecg_nn_agreement_relaxed')
argsort_discordant = np.argsort(list_median_DS)

In [39]:
diagnoses.keys()

dict_keys(['sepsis', 'shock', 'heart_failure', 'encephalopathy', 'anemia', 'hemorrhage', 'pneumonia', 'respiratory_failure', 'aki', 'pneumothorax', 'copd', 'other_medical', 'gi_hernia_ischemic', 'cirrhosis_liver', 'other_surgical'])

In [40]:
diagnoses_labels = {
    'sepsis': 'Sepsis',
    'shock': 'Shock',
    'heart_failure': 'Heart failure',
    'encephalopathy': 'Encephalopathy',
    'anemia': 'Anemia', 
    'hemorrhage': 'Hemorrhage', 
    'pneumonia': 'Pneumonia',
    'respiratory_failure': 'Respiratory failure',
    'aki': 'AKI',
    'pneumothorax': 'Pneumothorax',
    'copd': 'COPD',
    'other_medical': 'Other - medical',
    'gi_hernia_ischemic': 'GI, hernia,\nischemic colitis',
    'cirrhosis_liver': 'Liver transplant,\ncirrhosis',
    'other_surgical': 'Other - surgical'
}

diagnoses_colors = {
    'sepsis': 'green',
    'shock': 'green',
    'heart_failure': 'red',
    'encephalopathy': 'orange',
    'anemia': 'red', 
    'hemorrhage': 'red', 
    'pneumonia': 'blue',
    'respiratory_failure': 'blue',
    'aki': 'brown',
    'pneumothorax': 'blue',
    'copd': 'blue',
    'other_medical': 'gray',
    'gi_hernia_ischemic': 'brown',
    'cirrhosis_liver': 'brown',
    'other_surgical': 'gray',
}

todo:
    sort by DS%
    
    format xtick labels
    improve y labels
    improve order of variables?

In [41]:
fig, ax = plt.subplots(len(vars_to_plot) // 2, 2, figsize = (7.6, 5), sharex=True)
ax = ax.flatten()

for iv, variable in enumerate(vars_to_plot):

    list_median, list_iqr, list_n = get_variable_values(variable)
    list_median = np.array(list_median)[argsort_discordant]
    list_iqr = [np.array(list_iqr[0])[argsort_discordant], np.array(list_iqr[1])[argsort_discordant]]
    list_n = np.array(list_n)[argsort_discordant]
    
    diagnoses_sorted = np.array(list(diagnoses.keys()))[argsort_discordant]
    
    sns.barplot(x=np.arange(len(diagnoses.keys())), y=list_median, 
                linewidth=1, yerr = list_iqr, errwidth=0.01,
#                 facecolor=(1, 1, 1, 0),
                palette = [diagnoses_colors[x] for x in diagnoses_sorted],
                errcolor=".2", edgecolor=".2", ax = ax[iv])

    ax[iv].set_ylabel(y_labels_short[iv])
    
    if variable == 'discordant_proportion_ecg_nn_agreement_relaxed':
        ax[iv].set_ylim([0, 1])
        ax[iv].set_yticks([0, 0.25, 0.5, 0.75])
    elif variable == 'arousali_ecg_nn_all':
        ax[iv].set_ylim([0, 15])
        ax[iv].set_yticks([0, 5, 10])
        
    
ax[-2].set_xticklabels([diagnoses_labels[x] + f' ({int(n)})' for x, n in zip(diagnoses_sorted, list_n)], rotation=90)
ax[-1].set_xticklabels([diagnoses_labels[x] + f' ({int(n)})' for x, n in zip(diagnoses_sorted, list_n)], rotation=90)

plt.subplots_adjust(hspace=0, left=0.07, right=0.995, bottom=0.25, top=0.995)

plt.savefig('sleep_statistics_diagnoses_groups.svg')
plt.savefig('sleep_statistics_diagnoses_groups.eps')
plt.savefig('sleep_statistics_diagnoses_groups.tiff', dpi=400)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [47]:
plt.figure()

sns.barplot(x=[0, 1], y=[2, 3], 

                 linewidth=2.5, yerr = [[1, 0.2], [0.1, 0.2]])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …