In [6]:
import numpy as np
import pandas as pd
import os

In [2]:
filedir = 'M:/Projects/ICU_SLEEP_STUDY/data/data_analysis/AirGo/airgo_research'

In [3]:
# patients 3,4 and 6 have both v4 breath and raw: merge those:

In [33]:
ids = ['003','004','006']
idsel = ids[2]

In [34]:
breath = pd.read_csv(os.path.join(filedir, 'airgo_'+idsel+'.csv'))
raw = pd.read_csv(os.path.join(filedir, 'airgo_rawv4_'+idsel+'.csv'))

In [35]:
breath = breath[breath.columns[1:]]
breath.head()

                  DateTime          Band   accX  accY  accZ  CRCStatus
0  2018-07-10 09:11:25.800  14695.798652  252.0   0.0  17.0        NaN
1  2018-07-10 09:11:25.900  14985.457118  252.0   0.0  17.0        NaN
2  2018-07-10 09:11:26.000  15267.438003  252.0   0.0  17.0        NaN
3  2018-07-10 09:11:26.100  15532.203912  252.0   0.0  17.0        NaN
4  2018-07-10 09:11:26.200  15770.217451  252.0   0.0  17.0        NaN

In [36]:
raw = raw[raw.columns[1:]]
raw.head()

                  DateTime   Band  accX  accY  accZ  CRCStatus
0  2018-07-10 20:46:21.200  15896     2   245   250        NaN
1  2018-07-10 20:46:21.300  15800     2   245   250        NaN
2  2018-07-10 20:46:21.400  15776     1   244   250        NaN
3  2018-07-10 20:46:21.500  16056     1   245   249        NaN
4  2018-07-10 20:46:21.600  15896     1   245   250        NaN

In [37]:
merged = pd.concat([breath, raw], axis = 0)

In [38]:
merged.head()

                  DateTime          Band   accX  accY  accZ  CRCStatus
0  2018-07-10 09:11:25.800  14695.798652  252.0   0.0  17.0        NaN
1  2018-07-10 09:11:25.900  14985.457118  252.0   0.0  17.0        NaN
2  2018-07-10 09:11:26.000  15267.438003  252.0   0.0  17.0        NaN
3  2018-07-10 09:11:26.100  15532.203912  252.0   0.0  17.0        NaN
4  2018-07-10 09:11:26.200  15770.217451  252.0   0.0  17.0        NaN

In [39]:
merged = merged.sort_values('DateTime')

In [40]:
merged.head()

                  DateTime          Band   accX  accY  accZ  CRCStatus
0  2018-07-10 09:11:25.800  14695.798652  252.0   0.0  17.0        NaN
1  2018-07-10 09:11:25.900  14985.457118  252.0   0.0  17.0        NaN
2  2018-07-10 09:11:26.000  15267.438003  252.0   0.0  17.0        NaN
3  2018-07-10 09:11:26.100  15532.203912  252.0   0.0  17.0        NaN
4  2018-07-10 09:11:26.200  15770.217451  252.0   0.0  17.0        NaN

In [41]:
merged.to_csv(os.path.join(filedir, 'airgo_merged'+idsel+'.csv'), index=False)